#!/bin/sh

cat << POLICY > /usr/share/polkit-1/actions/org.budgie.welcome.policy
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC
 "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/PolicyKit/1/policyconfig.dtd">
<policyconfig>
  <vendor>ubuntu-budgie</vendor>
  <vendor_url>http://hal.freedesktop.org/docs/PolicyKit/</vendor_url>

  <action id="org.budgie.welcome">
    <description>Ubuntu Budgie privileged actions utility</description>
    <message>Helper utility that will allow budgie-welcome to perform privileged actions</message>
    <icon_name>system-run</icon_name>
    <defaults>
      <allow_any>no</allow_any>
      <allow_inactive>no</allow_inactive>
      <allow_active>yes</allow_active>
    </defaults>
    <annotate key="org.freedesktop.policykit.exec.path">$SNAP/usr/lib/budgie-welcome/budgie-welcome-privileged-actions</annotate>
  </action>
</policyconfig>
POLICY

