# add-apt-repository
# Autogenerated from man page /usr/share/man/man1/add-apt-repository.1.gz
complete -c add-apt-repository -s h -l help -d 'Show help message and exit'
complete -c add-apt-repository -s d -l debug -d 'Print debug information to the command line'
complete -c add-apt-repository -s r -l remove -d 'Remove the specified repository'
complete -c add-apt-repository -s y -l yes -d 'Assume yes to all queries'
complete -c add-apt-repository -s n -l no-update -d 'After adding the repository, do not update the package cache'
complete -c add-apt-repository -s l -l login -d 'Login to Launchpad (this is only needed for private PPAs)'
complete -c add-apt-repository -s s -l enable-source -d 'Allow downloading of the source packages from the repository'
complete -c add-apt-repository -s c -l component -d 'Which component(s) should be used with the specified repository'
complete -c add-apt-repository -s p -l pocket -d 'What pocket to use'
complete -c add-apt-repository -l dry-run -d 'Show what would be done, but don\'t make any changes'
complete -c add-apt-repository -s L -l list -d 'List currently configured repositories'
complete -c add-apt-repository -s P -l ppa -d 'Add an Ubuntu Launchpad Personal Package Archive'
complete -c add-apt-repository -s C -l cloud -d 'Add an Ubuntu Cloud Archive'
complete -c add-apt-repository -s U -l uri -d 'Add an archive, specified as a single URI'
complete -c add-apt-repository -l sourceslist -d 'only one (or none) of them may be specified'
complete -c add-apt-repository -o updates -o proposed
complete -c add-apt-repository -s S -d 'Add an archive, specified as a full source entry line in one-line sources'

