# addgroup
# Autogenerated from man page /usr/share/man/man8/addgroup.8.gz
complete -c addgroup -l conf -d 'Use FILE instead of R /etc/adduser. conf '
complete -c addgroup -l disabled-login -d 'Do not run passwd to set the password'
complete -c addgroup -l disabled-password -d 'Like --disabled-login, but logins are still possible (for example using  SSH …'
complete -c addgroup -l force-badname -d 'By default, user and group names are checked against the configurable regular…'
complete -c addgroup -l gecos -d 'Set the gecos field for the new entry generated'
complete -c addgroup -l gid -d 'When creating a group, this option forces the new groupid to be the given num…'
complete -c addgroup -l group -d 'When combined with   --system , a group with the same name and ID as the syst…'
complete -c addgroup -l help -d 'Display brief instructions'
complete -c addgroup -l home -d 'Use DIR as the user\'s home directory, rather than the default specified by th…'
complete -c addgroup -l shell -d 'Use SHELL as the user\'s login shell, rather than the default specified by the…'
complete -c addgroup -l ingroup -d 'Add the new user to GROUP instead of a usergroup or the default group defined…'
complete -c addgroup -l no-create-home -d 'Do not create the home directory, even if it doesn\'t exist'
complete -c addgroup -l quiet -d 'Suppress informational messages, only show warnings and errors'
complete -c addgroup -l debug -d 'Be verbose, most useful if you want to nail down a problem with adduser'
complete -c addgroup -l system -d 'Create a system user or group'
complete -c addgroup -l uid -d 'Force the new userid to be the given number'
complete -c addgroup -l firstuid -d 'Override the first uid in the range that the uid is chosen from (overrides  F…'
complete -c addgroup -l lastuid -d 'Override the last uid in the range that the uid is chosen from (  LAST_UID )'
complete -c addgroup -l add_extra_groups -d 'Add new user to extra groups defined in the configuration file'
complete -c addgroup -l encrypt-home -d option
complete -c addgroup -l version -d 'Display version and copyright information'

