# agetty
# Autogenerated from man page /usr/share/man/man8/agetty.8.gz
complete -c agetty -s 8 -l 8bits
complete -c agetty -s a -l autologin
complete -c agetty -s c -l noreset
complete -c agetty -s E -l remote
complete -c agetty -s f -l issue-file
complete -c agetty -l show-issue
complete -c agetty -s h -l flow-control
complete -c agetty -s H -l host
complete -c agetty -s i -l noissue
complete -c agetty -s I -l init-string
complete -c agetty -s J -l noclear
complete -c agetty -s l -l login-program
complete -c agetty -s L -l local-line
complete -c agetty -s m -l extract-baud
complete -c agetty -l list-speeds
complete -c agetty -s n -l skip-login
complete -c agetty -s N -l nonewline
complete -c agetty -s o -l login-options
complete -c agetty -s p -l login-pause
complete -c agetty -s r -l chroot
complete -c agetty -s R -l hangup
complete -c agetty -s s -l keep-baud
complete -c agetty -s t -l timeout
complete -c agetty -s U -l detect-case
complete -c agetty -s w -l wait-cr
complete -c agetty -l nohints
complete -c agetty -l nohostname
complete -c agetty -l long-hostname
complete -c agetty -l erase-chars
complete -c agetty -l kill-chars
complete -c agetty -l chdir
complete -c agetty -l delay
complete -c agetty -l nice
complete -c agetty -l reload
complete -c agetty -l version
complete -c agetty -l help

