# alsabat
# Autogenerated from man page /usr/share/man/man1/alsabat.1.gz
complete -c alsabat -s h -l help -d 'Help: show syntax'
complete -c alsabat -s D -d 'Select sound card to be tested by name'
complete -c alsabat -s P -d 'Select the playback PCM device'
complete -c alsabat -s C -d 'Select the capture PCM device'
complete -c alsabat -s f -d 'Sample format . br Recognized sample formats are: U8 S16_LE S24_3LE S32_LE '
complete -c alsabat -s c -d 'The number of channels.  The default is one channel'
complete -c alsabat -s r -d 'Sampling rate in Hertz.  The default rate is 44100 Hertz'
complete -c alsabat -s n -d 'Duration of generated signal.  The value could be either of the two forms: '
complete -c alsabat -s k -d 'Sigma k value for analysis'
complete -c alsabat -s F -d 'Target frequency for signal generation and analysis, in Hertz'
complete -c alsabat -s p -d 'Total number of periods to play or capture'
complete -c alsabat -l log -d 'Write stderr and stdout output to this log file'
complete -c alsabat -l file -d 'Input WAV file for playback'
complete -c alsabat -l saveplay -d 'Target WAV file to save capture test content'
complete -c alsabat -l local -d 'Internal loopback mode'
complete -c alsabat -l standalone -d 'Add support for standalone mode where ALSABAT will run on a different machine…'
complete -c alsabat -l roundtriplatency -d 'Round trip latency test'
complete -c alsabat -l snr-db -d 'Noise detection threshold in SNR (dB).  26dB indicates 5% noise in amplitude'
complete -c alsabat -o c2 -o r44100
complete -c alsabat -o r48000
complete -c alsabat -l snr-pc -d 'Noise detection threshold in percentage of noise amplitude (%)'

