# alsaucm
# Autogenerated from man page /usr/share/man/man1/alsaucm.1.gz
complete -c alsaucm -s h -l help -d 'this help'
complete -c alsaucm -s c -l card -d 'open card NAME'
complete -c alsaucm -s i -l interactive -d 'interactive mode'
complete -c alsaucm -s b -l batch -d 'batch mode (use \\(aq-\\(aq for the stdin input)'
complete -c alsaucm -s n -l no-open -d 'do not open first card found'

