# alsa-info
# Autogenerated from man page /usr/share/man/man8/alsa-info.8.gz
complete -c alsa-info -l upload -d 'Upload contents to the server (www. alsa-project. org or pastebin. ca)'
complete -c alsa-info -l no-upload -d 'Do not upload contents to the remote server'
complete -c alsa-info -l stdout -d 'Print information to standard output'
complete -c alsa-info -l output -d 'Specify file for output in no-upload mode'
complete -c alsa-info -l debug -d 'Run utility as normal, but will not delete file (usually /tmp/alsa-info. txt)'
complete -c alsa-info -l with-aplay -d 'Includes output from aplay -l'
complete -c alsa-info -l with-amixer -d 'Includes output from amixer'
complete -c alsa-info -l with-alsactl -d 'Includes output from alsactl'
complete -c alsa-info -l with-configs -d 'Includes output from ~/. asoundrc and /etc/asound. conf if they exist'
complete -c alsa-info -l update -d 'Check server for updates'
complete -c alsa-info -l about -d 'Print information about authors'

