# amixer
# Autogenerated from man page /usr/share/man/man1/amixer.1.gz
complete -c amixer -s c -d 'Select the card number to control'
complete -c amixer -s D -d 'Select the device name to control.  The default control name is \'default\''
complete -c amixer -s s -l stdin -d 'Read from stdin and execute the command on each line sequentially'
complete -c amixer -s h -d 'Help: show syntax'
complete -c amixer -s q -d 'Quiet mode.  Do not show results of changes'
complete -c amixer -s R -d 'Use the raw value for evaluating the percentage representation'
complete -c amixer -s M -d 'Use the mapped volume for evaluating the percentage representation like alsam…'

