# anacron
# Autogenerated from man page /usr/share/man/man8/anacron.8.gz
complete -c anacron -s f -d 'Force execution of the jobs, ignoring the timestamps'
complete -c anacron -s u -d 'Only update the timestamps of the jobs, to the current date, but don\'t run an…'
complete -c anacron -s s -d 'Serialize execution of jobs'
complete -c anacron -s n -d 'Run jobs now.   Ignore the delay specifications in the  /etc/anacrontab file'
complete -c anacron -s d -d 'Don\'t fork to the background'
complete -c anacron -s q -d 'Suppress messages to standard error.   Only applicable with -d'
complete -c anacron -s t -d 'Use specified anacrontab, rather than the default'
complete -c anacron -s T -d 'Anacrontab testing.  The configuration file will be tested for validity'
complete -c anacron -s S -d 'Use the specified spooldir to store timestamps in'
complete -c anacron -s V -d 'Print version information, and exit'
complete -c anacron -s h -d 'Print short usage message, and exit'

