# apgbfm
# Autogenerated from man page /usr/share/man/man1/apgbfm.1.gz
complete -c apgbfm -s f -d 'use filter as the name for Bloom filter filename'
complete -c apgbfm -s i -d 'print information about filter'
complete -c apgbfm -s n -d 'create new empty filter for numofwords number of words'
complete -c apgbfm -s d -d 'create new filter from dictfile'
complete -c apgbfm -s a -d 'add word to the filter'
complete -c apgbfm -s A -d 'add all words from dictfile to the filter'
complete -c apgbfm -s c -d 'check word for appearance in the filter'
complete -c apgbfm -s C -d 'check every word from dictfile for appearance in the filter'
complete -c apgbfm -s q -d 'quiet mode'
complete -c apgbfm -s s -d 'create new filter in case-insensitive mode'
complete -c apgbfm -s v -d 'print version information'

