# apt-config
# Autogenerated from man page /usr/share/man/man8/apt-config.8.gz
complete -c apt-config -l empty -d 'Include options which have an empty value'
complete -c apt-config -l format -d 'Defines the output of each config option'
complete -c apt-config -s h -l help -d 'Show a short usage summary'
complete -c apt-config -s v -l version -d 'Show the program version'
complete -c apt-config -s c -l config-file -d 'Configuration File; Specify a configuration file to use'
complete -c apt-config -s o -l option -d 'Set a Configuration Option; This will set an arbitrary configuration option'
complete -c apt-config -s f
complete -c apt-config -o f- -l no-f

