# apt-mark
# Autogenerated from man page /usr/share/man/man8/apt-mark.8.gz
complete -c apt-mark -s h -l help -d 'Show a short usage summary'
complete -c apt-mark -s v -l version -d 'Show the program version'
complete -c apt-mark -s c -l config-file -d 'Configuration File; Specify a configuration file to use'
complete -c apt-mark -s o -l option -d 'Set a Configuration Option; This will set an arbitrary configuration option'
complete -c apt-mark -s f -l file

