# apt-extracttemplates
# Autogenerated from man page /usr/share/man/man1/apt-extracttemplates.1.gz
complete -c apt-extracttemplates -s t -l tempdir -d 'Temporary directory in which to write extracted debconf template files and co…'
complete -c apt-extracttemplates -s h -l help -d 'Show a short usage summary'
complete -c apt-extracttemplates -s v -l version -d 'Show the program version'
complete -c apt-extracttemplates -s c -l config-file -d 'Configuration File; Specify a configuration file to use'
complete -c apt-extracttemplates -s o -l option -d 'Set a Configuration Option; This will set an arbitrary configuration option'
complete -c apt-extracttemplates -o f- -l no-f
complete -c apt-extracttemplates -s f -d 'or several other variations'

