# apt-cache
# Autogenerated from man page /usr/share/man/man8/apt-cache.8.gz
complete -c apt-cache -s p -l pkg-cache -d 'Select the file to store the package cache'
complete -c apt-cache -s s -l src-cache -d 'Select the file to store the source cache'
complete -c apt-cache -s q -l quiet -d 'Quiet; produces output suitable for logging, omitting progress indicators'
complete -c apt-cache -s i -l important -d 'Print only important dependencies; for use with unmet and depends'
complete -c apt-cache -l no-pre-depends -l no-depends -l no-recommends -l no-suggests -l no-conflicts -l no-breaks -l no-replaces -l no-enhances -d 'Per default the depends and rdepends print all dependencies'
complete -c apt-cache -l implicit -d 'Per default depends and rdepends print only dependencies explicitly expressed…'
complete -c apt-cache -s f -l full -d 'Print full package records when searching'
complete -c apt-cache -s a -l all-versions -d 'Print full records for all available versions'
complete -c apt-cache -s g -l generate -d 'Perform automatic package cache regeneration, rather than use the cache as it…'
complete -c apt-cache -l names-only -s n -d 'Only search on the package and provided package names, not the long descripti…'
complete -c apt-cache -l all-names -d 'Make pkgnames print all names, including virtual packages and missing depende…'
complete -c apt-cache -l recurse -d 'Make depends and rdepends recursive so that all packages mentioned are printe…'
complete -c apt-cache -l installed -d 'Limit the output of depends and rdepends to packages which are currently inst…'
complete -c apt-cache -l with-source -d 'Adds the given file as a source for metadata'
complete -c apt-cache -s h -l help -d 'Show a short usage summary'
complete -c apt-cache -s v -l version -d 'Show the program version'
complete -c apt-cache -s c -l config-file -d 'Configuration File; Specify a configuration file to use'
complete -c apt-cache -s o -l option -d 'Set a Configuration Option; This will set an arbitrary configuration option'
complete -c apt-cache -l only-source -d 'to display only source package names.  dump'
complete -c apt-cache -o f- -l no-f
complete -c apt-cache -l no-all-versions
complete -c apt-cache -l no-generate -d APT::Cache::Generate

