# aptd
# Autogenerated from man page /usr/share/man/man1/aptd.1.gz
complete -c aptd -s d -l debug -d 'Show additional information on the command line'
complete -c aptd -s h -l help -d 'Show information about the usage of the command'
complete -c aptd -s r -l replace -d 'Replace another aptd instance if it is running'
complete -c aptd -s p -d 'Write profiling data to  PROFILE_FILE using Python\'s profiler'
complete -c aptd -s t -l disable-timeout -d 'Do not shutdown the daemon after an idle time'
complete -c aptd -l dummy -d 'Instead of applying the changes to the system only show a progress'

