# ar
# Autogenerated from man page /usr/share/man/man1/ar.1.gz
complete -c ar -l help -d 'Displays the list of command-line options supported by ar and then exits'
complete -c ar -l version -d 'Displays the version information of ar and then exits'
complete -c ar -o X32_64 -d 'ar ignores an initial option spelled -X32_64, for compatibility with \\s-1AIX'
complete -c ar -l plugin -d 'The optional command-line switch --plugin name causes ar to load the plugin c…'
complete -c ar -l target -d 'The optional command-line switch --target bfdname specifies that the archive …'
complete -c ar -l output -d 'The --output option can be used to specify a path to a directory into which a…'
complete -c ar -l record-libdeps -d 'The --record-libdeps option is identical to the l modifier, just handled in l…'
complete -c ar -l thin -d 'Make the specified archive a thin archive'

