# arj-register
# Autogenerated from man page /usr/share/man/man1/arj-register.1.gz
complete -c arj-register -o arj -d 'Registers all ARJ for Linux programs in the current directory'
complete -c arj-register -o arj32 -d 'Registers all ARJ32 (supplied by ARJ Software, Inc'

