# arptables-nft-save
# Autogenerated from man page /usr/share/man/man8/arptables-nft-save.8.gz
complete -c arptables-nft-save -s M -l modprobe -d 'Specify the path to the modprobe program'
complete -c arptables-nft-save -s c -l counters -d 'Include the current values of all packet and byte counters in the output'
complete -c arptables-nft-save -s V -l version -d 'Print version information and exit'

