# aseqdump
# Autogenerated from man page /usr/share/man/man1/aseqdump.1.gz
complete -c aseqdump -s h -l help -d 'Prints a list of options'
complete -c aseqdump -s V -l version -d 'Prints the current version'
complete -c aseqdump -s l -l list -d 'Prints a list of possible input ports'
complete -c aseqdump -s p -l port -d 'Sets the sequencer port(s) from which events are received'

