# avahi-set-host-name
# Autogenerated from man page /usr/share/man/man1/avahi-set-host-name.1.gz
complete -c avahi-set-host-name -s v -l verbose -d 'Enable verbose mode'
complete -c avahi-set-host-name -s h -l help -d 'Show help'
complete -c avahi-set-host-name -s V -l version -d 'Show version information'

