# avahi-resolve-address
# Autogenerated from man page /usr/share/man/man1/avahi-resolve-address.1.gz
complete -c avahi-resolve-address -s n -l name -d 'Translate one or more fully qualified host names into addresses'
complete -c avahi-resolve-address -s a -l address -d 'Translate one or more addresses into fully qualified host names'
complete -c avahi-resolve-address -s v -l verbose -d 'Enable verbose mode'
complete -c avahi-resolve-address -s 6 -d 'When resolving a host name, look for IPv6 addresses exclusively'
complete -c avahi-resolve-address -s 4 -d 'When resolving a host name, look for IPv4 addresses exclusively'
complete -c avahi-resolve-address -s h -l help -d 'Show help'
complete -c avahi-resolve-address -s V -l version -d 'Show version information'

