# avahi-publish-address
# Autogenerated from man page /usr/share/man/man1/avahi-publish-address.1.gz
complete -c avahi-publish-address -s s -l service -d 'Register a service.  avahi-publish-service is equivalent to avahi-publish -s'
complete -c avahi-publish-address -s a -l address -d 'Register an address/host name mapping'
complete -c avahi-publish-address -s v -l verbose -d 'Enable verbose mode'
complete -c avahi-publish-address -s H -l host -d 'Specify a host name for this service, in case it doesn\'t reside on the local …'
complete -c avahi-publish-address -s d -l domain -d 'Publish the service in the specified domain'
complete -c avahi-publish-address -l subtype -d 'Register the service with an additional subtype in addition to the main type'
complete -c avahi-publish-address -s f -l no-fail -d 'Don\'t fail if the daemon is not found running'
complete -c avahi-publish-address -s h -l help -d 'Show help'
complete -c avahi-publish-address -s V -l version -d 'Show version information'

