# axfer-list
# Autogenerated from man page /usr/share/man/man1/axfer-list.1.gz
complete -c axfer-list -s l -d ','
complete -c axfer-list -l list-devices -d 'are handled as device operation.  Options of'
complete -c axfer-list -s L -d ','
complete -c axfer-list -l list-pcms -d 'are handled as pcm operation'

