# basename
# Autogenerated from man page /usr/share/man/man1/basename.1.gz
complete -c basename -s a -l multiple -d 'support multiple arguments and treat each as a NAME'
complete -c basename -s s -l suffix -d 'remove a trailing SUFFIX; implies -a'
complete -c basename -s z -l zero -d 'end each output line with NUL, not newline'
complete -c basename -l help -d 'display this help and exit'
complete -c basename -l version -d 'output version information and exit EXAMPLES'
complete -c basename -s '>'

