# base64
# Autogenerated from man page /usr/share/man/man1/base64.1.gz
complete -c base64 -s d -l decode -d 'decode data'
complete -c base64 -s i -l ignore-garbage -d 'when decoding, ignore non-alphabet characters'
complete -c base64 -s w -l wrap -d 'wrap encoded lines after COLS character (default 76)'
complete -c base64 -l help -d 'display this help and exit'
complete -c base64 -l version -d 'output version information and exit'

