# biosdecode
# Autogenerated from man page /usr/share/man/man8/biosdecode.8.gz
complete -c biosdecode -s d -l dev-mem -d 'Read memory from device FILE (default: /dev/mem)'
complete -c biosdecode -l pir -d 'Decode the details of the PCI IRQ routing table'
complete -c biosdecode -s h -l help -d 'Display usage information and exit'
complete -c biosdecode -s V -l version -d 'Display the version and exit'

