# blkdiscard
# Autogenerated from man page /usr/share/man/man8/blkdiscard.8.gz
complete -c blkdiscard -s f -l force
complete -c blkdiscard -s o -l offset
complete -c blkdiscard -s l -l length
complete -c blkdiscard -s p -l step
complete -c blkdiscard -s s -l secure
complete -c blkdiscard -s z -l zeroout
complete -c blkdiscard -s v -l verbose
complete -c blkdiscard -s V -l version
complete -c blkdiscard -s h -l help

