# blkstat
# Autogenerated from man page /usr/share/man/man1/blkstat.1.gz
complete -c blkstat -s f -d 'Specify the file system type'
complete -c blkstat -s i -d 'Identify the type of image file, such as raw'
complete -c blkstat -s o -d 'The sector offset where the file system starts in the image'
complete -c blkstat -s b -d 'The size, in bytes, of the underlying device sectors'
complete -c blkstat -s v -d 'Verbose output of debugging statements to stderr'
complete -c blkstat -s V -d 'Display version image [images] The disk or partition image to read, whose for…'

