# bluemoon
# Autogenerated from man page /usr/share/man/man1/bluemoon.1.gz
complete -c bluemoon -s A -l bdaddr -d 'Set Bluetooth address'
complete -c bluemoon -s F -l firmware -d 'Load firmware'
complete -c bluemoon -s C -l check -d 'Check firmware image'
complete -c bluemoon -s R -l reset -d 'Reset controller'
complete -c bluemoon -s B -l coldboot -d 'Cold boot controller'
complete -c bluemoon -s E -l exception -d 'Trigger exception'
complete -c bluemoon -s i -l index -d 'Use specified controller'
complete -c bluemoon -s h -l help -d 'Show help options'

