# boltd
# Autogenerated from man page /usr/share/man/man8/boltd.8.gz
complete -c boltd -s h -l help -d 'Prints a short help text and exits'
complete -c boltd -l version -d 'Shows the version number and exits'
complete -c boltd -s r -l replace -d 'Replace the currently running boltd instance'
complete -c boltd -l journal -d 'Force logging to the journal'
complete -c boltd -s v -l verbose -d 'Print debug output'

