# btattach
# Autogenerated from man page /usr/share/man/man1/btattach.1.gz
complete -c btattach -s B -l brder -d 'Attach a BR/EDR controller'
complete -c btattach -s A -l amp -d 'Attach an AMP controller'
complete -c btattach -s P -l protocol -d 'Specify the protocol type for talking to the device. sp Supported values are:'
complete -c btattach -s S -l speed -d 'Specify wich baudrate to use'
complete -c btattach -s N -l noflowctl -d 'Disable flow control'
complete -c btattach -s v -l version -d 'Show version'
complete -c btattach -s h -l help -d 'Show help options'

