# btmon
# Autogenerated from man page /usr/share/man/man1/btmon.1.gz
complete -c btmon -s r -l read -d 'Read traces in btsnoop format'
complete -c btmon -s w -l write -d 'Save traces in btsnoop format'
complete -c btmon -s a -l analyze -d 'Analyze traces in btsnoop format'
complete -c btmon -s s -l server -d 'Start monitor server socket '
complete -c btmon -s i -l index -d 'Show only specified controller'
complete -c btmon -s d -l tty -d 'Read data from TTY . HP -B, --tty-speed <rate> Set TTY speed (default 115200)'
complete -c btmon -s t -l time -d 'Show time instead of time offset'
complete -c btmon -s T -l date -d 'Show time and date information'
complete -c btmon -s S -l sco -d 'Dump SCO traffic'
complete -c btmon -s A -l a2dp -d 'Dump A2DP stream traffic'
complete -c btmon -s E -l ellisys -d 'Send Ellisys HCI Injection'
complete -c btmon -s p -l priority
complete -c btmon -s B -l tty-speed
complete -c btmon -s h -l help -d 'Show help options'

