# budgie-panel
# Autogenerated from man page /usr/share/man/man1/budgie-panel.1.gz
complete -c budgie-panel -s h -l help -d 'Show help options'
complete -c budgie-panel -l help-all -d 'Show all help options'
complete -c budgie-panel -l help-gtk -d 'Show GTK+ Options . SS "Application Options:"'
complete -c budgie-panel -l replace -d 'Replace currently running panel'
complete -c budgie-panel -l reset -d 'Reset the panel configuration'
complete -c budgie-panel -l display -d 'X display to use'

