# budgie-daemon
# Autogenerated from man page /usr/share/man/man1/budgie-daemon.1.gz
complete -c budgie-daemon -s h -l help -d 'Show help options'
complete -c budgie-daemon -l help-all -d 'Show all help options'
complete -c budgie-daemon -l help-gtk -d 'Show GTK+ Options . SS "Application Options:"'
complete -c budgie-daemon -l replace -d 'Replace currently running daemon'
complete -c budgie-daemon -l display -d 'X display to use'

