# budgie-run-dialog
# Autogenerated from man page /usr/share/man/man1/budgie-run-dialog.1.gz
complete -c budgie-run-dialog -s h -l help -d 'Show help options'
complete -c budgie-run-dialog -l help-all -d 'Show all help options'
complete -c budgie-run-dialog -l help-gapplication -d 'Show GApplication options'
complete -c budgie-run-dialog -l help-gtk -d 'Show GTK+ Options . SS "Application Options:"'
complete -c budgie-run-dialog -l display -d 'X display to use'

