# bzip2
# Autogenerated from man page /usr/share/man/man1/bzip2.1.gz
complete -c bzip2 -s c -l stdout -d 'Compress or decompress to standard output'
complete -c bzip2 -s d -l decompress -d 'Force decompression'
complete -c bzip2 -s z -l compress -d 'The complement to -d: forces compression, regardless of the invocation name'
complete -c bzip2 -s t -l test -d 'Check integrity of the specified file(s), but don\'t decompress them'
complete -c bzip2 -s f -l force -d 'Force overwrite of output files'
complete -c bzip2 -s k -l keep -d 'Keep (don\'t delete) input files during compression or decompression'
complete -c bzip2 -s s -l small -d 'Reduce memory usage, for compression, decompression and testing'
complete -c bzip2 -s q -l quiet -d 'Suppress non-essential warning messages'
complete -c bzip2 -s v -l verbose -d 'Verbose mode -- show the compression ratio for each file processed'
complete -c bzip2 -s h -l help -d 'Print a help message and exit'
complete -c bzip2 -s L -l license -s V -l version -d 'Display the software version, license terms and conditions'
complete -c bzip2 -s 1 -l fast -s 9 -l best -d 'Set the block size to 100 k, 200 k .   900 k when compressing'
complete -c bzip2 -l repetitive-fast -l repetitive-best -d 'These flags are redundant in versions 0. 9. 5 and above'
complete -c bzip2 -o vvvv

