# chcpu
# Autogenerated from man page /usr/share/man/man8/chcpu.8.gz
complete -c chcpu -s c -l configure
complete -c chcpu -s d -l disable
complete -c chcpu -s e -l enable
complete -c chcpu -s g -l deconfigure
complete -c chcpu -s p -l dispatch
complete -c chcpu -s r -l rescan
complete -c chcpu -s V -l version
complete -c chcpu -s h -l help

