# check-language-support
# Autogenerated from man page /usr/share/man/man1/check-language-support.1.gz
complete -c check-language-support -s h -l help -d 'show this help message and exit'
complete -c check-language-support -s l -l language -d 'target language code - if omitted, check for all languages on the system'
complete -c check-language-support -s d -l datadir -d 'use an alternative data directory instead of the default  /usr/share/language…'
complete -c check-language-support -s a -l all -d 'check all available languages'
complete -c check-language-support -l show-installed -d 'show installed packages as well as missing ones AUTHOR This manpage has been …'

