# chfn
# Autogenerated from man page /usr/share/man/man1/chfn.1.gz
complete -c chfn -s f -l full-nameFULL_NAME -d 'Change the user\\*(Aqs full name'
complete -c chfn -s h -l home-phoneHOME_PHONE -d 'Change the user\\*(Aqs home phone number'
complete -c chfn -s o -l otherOTHER -d 'Change the user\\*(Aqs other GECOS information'
complete -c chfn -s r -l roomROOM_NUMBER -d 'Change the user\\*(Aqs room number'
complete -c chfn -s R -l rootCHROOT_DIR -d 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c chfn -s u -l help -d 'Display help message and exit'
complete -c chfn -s w -l work-phoneWORK_PHONE -d 'Change the user\\*(Aqs office phone number'
complete -c chfn -l full-name
complete -c chfn -l home-phone
complete -c chfn -l other
complete -c chfn -l room
complete -c chfn -l root
complete -c chfn -l work-phone

