# chgpasswd
# Autogenerated from man page /usr/share/man/man8/chgpasswd.8.gz
complete -c chgpasswd -s c -l crypt-method -d 'Use the specified method to encrypt the passwords'
complete -c chgpasswd -s e -l encrypted -d 'Supplied passwords are in encrypted form'
complete -c chgpasswd -s h -l help -d 'Display help message and exit'
complete -c chgpasswd -s m -l md5 -d 'Use MD5 encryption instead of DES when the supplied passwords are not encrypt…'
complete -c chgpasswd -s R -l rootCHROOT_DIR -d 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c chgpasswd -s s -l sha-rounds -d 'Use the specified number of rounds to encrypt the passwords'
complete -c chgpasswd -l root

