# chpasswd
# Autogenerated from man page /usr/share/man/man8/chpasswd.8.gz
complete -c chpasswd -s c -l crypt-methodMETHOD -d 'Use the specified method to encrypt the passwords'
complete -c chpasswd -s e -l encrypted -d 'Supplied passwords are in encrypted form'
complete -c chpasswd -s h -l help -d 'Display help message and exit'
complete -c chpasswd -s m -l md5 -d 'Use MD5 encryption instead of DES when the supplied passwords are not encrypt…'
complete -c chpasswd -s R -l rootCHROOT_DIR -d 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c chpasswd -s s -l sha-roundsROUNDS -d 'Use the specified number of rounds to encrypt the passwords'
complete -c chpasswd -l crypt-method
complete -c chpasswd -l root
complete -c chpasswd -l sha-rounds

