# chrt
# Autogenerated from man page /usr/share/man/man1/chrt.1.gz
complete -c chrt -s o -l other
complete -c chrt -s f -l fifo
complete -c chrt -s r -l rr
complete -c chrt -s b -l batch
complete -c chrt -s i -l idle
complete -c chrt -s d -l deadline
complete -c chrt -s T -l sched-runtime
complete -c chrt -s P -l sched-period
complete -c chrt -s D -l sched-deadline
complete -c chrt -s R -l reset-on-fork
complete -c chrt -s a -l all-tasks
complete -c chrt -s m -l max
complete -c chrt -s p -l pid
complete -c chrt -s v -l verbose
complete -c chrt -s V -l version
complete -c chrt -s h -l help

