# ciptool
# Autogenerated from man page /usr/share/man/man1/ciptool.1.gz
complete -c ciptool -s i -d 'The command is applied to device hciX , which must be the name or the address…'
complete -c ciptool -s h -l help -d 'Show help options'

