# ckbcomp
# Autogenerated from man page /usr/share/man/man1/ckbcomp.1.gz
complete -c ckbcomp -s '?' -o help -d 'Print a usage message and exit'
complete -c ckbcomp -o charmap -d 'The encoding to use for the output keymap'
complete -c ckbcomp -s I -d 'Look in the top-level directory  dir for files included by the keymap descrip…'
complete -c ckbcomp -s v -d 'Set level of detail for listing'
complete -c ckbcomp -o compact -d 'Generate a compact keymap with at most two xkb groups and two levels in each …'
complete -c ckbcomp -o freebsd -d 'Generate a keymap for FreeBSD'
complete -c ckbcomp -o backspace -d 'Specifies the behaviour of the . SM <BackSpace> and . SM <Delete> keys'
complete -c ckbcomp -o symbols -d 'Specifies the symbols component name of the XKB keyboard description'
complete -c ckbcomp -o keycodes -d 'Specifies the keycodes component name of the XKB keyboard description'
complete -c ckbcomp -o rules -d 'The name of the rules file to use'
complete -c ckbcomp -o model -d 'Specifies the keyboard model used to choose the component names'
complete -c ckbcomp -o layout -d 'Specifies the layout used to choose the component names'
complete -c ckbcomp -o variant -d 'Specifies the layout variant used to choose the component names'
complete -c ckbcomp -o option -d 'Adds an option used to choose component names'

