# clear
# Autogenerated from man page /usr/share/man/man1/clear.1.gz
complete -c clear -s T -d 'indicates the type of terminal'
complete -c clear -s V -d 'reports the version of ncurses which was used in this program, and exits'
complete -c clear -s x -d 'do not attempt to clear the terminal\'s scrollback buffer using the extended E…'

