# codepage
# Autogenerated from man page /usr/share/man/man1/codepage.1.gz
complete -c codepage -s c -d 'Input file is a single codepage'
complete -c codepage -s L -d 'Print header info (you don\'t want to see this)'
complete -c codepage -s l -d 'List all codepages contained in the file'
complete -c codepage -s a -d 'Extract all codepages from the file'

