# column
# Autogenerated from man page /usr/share/man/man1/column.1.gz
complete -c column -s J -l json
complete -c column -s c -l output-width
complete -c column -s d -l table-noheadings
complete -c column -s o -l output-separator
complete -c column -s s -l separator
complete -c column -s t -l table
complete -c column -s N -l table-columns
complete -c column -s l -l table-columns-limit
complete -c column -s R -l table-right
complete -c column -s T -l table-truncate
complete -c column -s E -l table-noextreme
complete -c column -s e -l table-header-repeat
complete -c column -s W -l table-wrap
complete -c column -s H -l table-hide
complete -c column -s O -l table-order
complete -c column -s n -l table-name
complete -c column -s L -l keep-empty-lines
complete -c column -s r -l tree
complete -c column -s i -l tree-id
complete -c column -s p -l tree-parent
complete -c column -s x -l fillrows
complete -c column -s V -l version
complete -c column -s h -l help

