# compress
# Autogenerated from man page /usr/share/man/man1/compress.1.gz
complete -c compress -s f -d 'flag is given'
complete -c compress -s c -d 'option makes compress/uncompress'
complete -c compress -s r -d 'flag is specified,  compress will operate recursively'
complete -c compress -s V -d 'flag tells each of these programs to print its version and patchlevel, along …'
complete -c compress -s b -d 'flag is reached (default 16).  Bits must be between 9 and 16'
complete -c compress -s v -d 'option, a message is printed yielding the percentage of reduction for each fi…'

