# csplit
# Autogenerated from man page /usr/share/man/man1/csplit.1.gz
complete -c csplit -s b -l suffix-format -d 'use sprintf FORMAT instead of %02d'
complete -c csplit -s f -l prefix -d 'use PREFIX instead of \'xx\''
complete -c csplit -s k -l keep-files -d 'do not remove output files on errors'
complete -c csplit -l suppress-matched -d 'suppress the lines matching PATTERN'
complete -c csplit -s n -l digits -d 'use specified number of digits instead of 2'
complete -c csplit -s s -l quiet -l silent -d 'do not print counts of output file sizes'
complete -c csplit -s z -l elide-empty-files -d 'remove empty output files'
complete -c csplit -l help -d 'display this help and exit'
complete -c csplit -l version -d 'output version information and exit . SS "Each PATTERN may be:"'

