# ctie
# Autogenerated from man page /usr/share/man/man1/ctie.1.gz
complete -c ctie -s c -d 'Create a single change file from the given R changefile s'
complete -c ctie -s m -d 'Create a new master file by applying the given changefile s'

