# ctwill-twinx
# Autogenerated from man page /usr/share/man/man1/ctwill-twinx.1.gz
complete -c ctwill-twinx -l version -s c -s i -s o -d 'and +lX are new in CWEBbin and TeX Live'
complete -c ctwill-twinx -l verbose -d '[bu] 2 File lookup with the environment variable CWEBINPUTS is extended to pe…'
complete -c ctwill-twinx -l quiet -d '[bu] 2 +v/-v: shortcut for +bhp; also'
complete -c ctwill-twinx -s e -d '[bu] 2'
complete -c ctwill-twinx -s f -d 'output [bu] 2'
complete -c ctwill-twinx -s x -d '[bu] 2 +P: [rs]input ctproofmac. tex instead of ctwimac'
complete -c ctwill-twinx -l help -d '[bu] 2'

