# cups-browsed
# Autogenerated from man page /usr/share/man/man8/cups-browsed.8.gz
complete -c cups-browsed -s v -s d -l debug -d 'Debug mode, verbose logging to stderr'
complete -c cups-browsed -s l -l logfile -d 'Debug logging into /var/log/cups/cups-browsed_log file'
complete -c cups-browsed -s c -d 'Uses the alternative configuration file config-file instead of the standard o…'
complete -c cups-browsed -s o -s o -d 'Supply configuration options via the command line'
complete -c cups-browsed -l autoshutdown -d 'Auto shutdown mode, mode is off for no auto shutdown, on for auto shutdown be…'
complete -c cups-browsed -l autoshutdown-on -d 'What cups-browsed considers as inactivity for auto-shutdown'
complete -c cups-browsed -l autoshutdown-timeout -d 'timeout tells after how many seconds cups-browsed should shut down if it has …'
complete -c cups-browsed -s h -l help -l version -d 'Display usage and version info and do not start the daemon'

