# cupsctl
# Autogenerated from man page /usr/share/man/man8/cupsctl.8.gz
complete -c cupsctl -s E -d 'Enables encryption on the connection to the scheduler'
complete -c cupsctl -s U -d 'Specifies an alternate username to use when authenticating with the scheduler'
complete -c cupsctl -s h -d 'Specifies the server address'
complete -c cupsctl -l debug-logging -d 'Enables (disables) debug logging to the error_log file'
complete -c cupsctl -l remote-admin -d 'Enables (disables) remote administration'
complete -c cupsctl -l remote-any -d 'Enables (disables) printing from any address, e. g. , the Internet'
complete -c cupsctl -l share-printers -d 'Enables (disables) sharing of local printers with other computers'
complete -c cupsctl -l user-cancel-any -d 'Allows (prevents) users to cancel jobs owned by others'

