# cups-genppdupdate
# Autogenerated from man page /usr/share/man/man8/cups-genppdupdate.8.gz
complete -c cups-genppdupdate -s h -d 'Show a help message'
complete -c cups-genppdupdate -s n -d 'No action.   The program will run, but the old PPD files will not be replaced'
complete -c cups-genppdupdate -s q -d 'Quiet mode.   No messages will be issued, apart from errors'
complete -c cups-genppdupdate -s v -d 'Verbose mode.   More informative messages will be issued'
complete -c cups-genppdupdate -s s -d 'Use ppd-directory as the base directory to read PPD files from'
complete -c cups-genppdupdate -s o -d 'Place updated PPD files in output-directory'
complete -c cups-genppdupdate -s N -d 'Reset all options to their defaults (do not merge options from the current PP…'

