# cupsdisable
# Autogenerated from man page /usr/share/man/man8/cupsdisable.8.gz
complete -c cupsdisable -s E -d 'Forces encryption of the connection to the server'
complete -c cupsdisable -s U -d 'Uses the specified username when connecting to the server'
complete -c cupsdisable -s c -d 'Cancels all jobs on the named destination'
complete -c cupsdisable -s h -d 'Uses the specified server and port'
complete -c cupsdisable -l hold -d 'Holds remaining jobs on the named printer'
complete -c cupsdisable -s r -d 'Sets the message associated with the stopped state'
complete -c cupsdisable -l release -d 'Releases pending jobs for printing'

