# cvt
# Autogenerated from man page /usr/share/man/man1/cvt.1.gz
complete -c cvt -s v -l verbose -d 'Warn verbosely when a given mode does not completely correspond with CVT stan…'
complete -c cvt -s r -l reduced -d 'Create a mode with reduced blanking'

