# cweb
# Autogenerated from man page /usr/share/man/man1/cweb.1.gz
complete -c cweb -l version -s c -s i -s o -d 'and +lX are new in CWEBbin and TeX Live'
complete -c cweb -l verbose -d '[bu] 2 File lookup with the environment variable CWEBINPUTS is extended to pe…'
complete -c cweb -l quiet -d '[bu] 2 +v/-v: shortcut for +bhp; also'
complete -c cweb -l help -d '[bu] 2'
complete -c cweb -s e -d '[bu] 2'
complete -c cweb -s f -d 'output [bu] 2'
complete -c cweb -s x -d '[bu] 2 +lX/-lX: use macros for language X as of Xcwebmac'

