# dbus-monitor
# Autogenerated from man page /usr/share/man/man1/dbus-monitor.1.gz
complete -c dbus-monitor -l system -d 'Monitor the system message bus'
complete -c dbus-monitor -l session -d 'Monitor the session message bus.  (This is the default. )'
complete -c dbus-monitor -l address -d 'Monitor an arbitrary message bus given at ADDRESS'
complete -c dbus-monitor -l profile -d 'Use the profiling output format'
complete -c dbus-monitor -l monitor -d 'Use the monitoring output format.  (This is the default. )'
complete -c dbus-monitor -l binary
complete -c dbus-monitor -l pcap

