# dbus-send
# Autogenerated from man page /usr/share/man/man1/dbus-send.1.gz
complete -c dbus-send -l dest -d 'Specify the name of the connection to receive the message'
complete -c dbus-send -l print-reply -d 'Block for a reply to the message sent, and print any reply received in a huma…'
complete -c dbus-send -l reply-timeout -d 'Wait for a reply for up to MSEC milliseconds'
complete -c dbus-send -l system -d 'Send to the system message bus'
complete -c dbus-send -l session -d 'Send to the session message bus.  (This is the default. )'
complete -c dbus-send -l bus -d 'Register on a message bus at ADDRESS, typically a dbus-daemon'
complete -c dbus-send -l peer -d 'Send to a non-message-bus D-Bus server at ADDRESS'
complete -c dbus-send -l type -d 'Specify method_call or signal (defaults to "signal")'

