# dbus-daemon
# Autogenerated from man page /usr/share/man/man1/dbus-daemon.1.gz
complete -c dbus-daemon -l config-file -d 'Use the given configuration file'
complete -c dbus-daemon -l fork -d 'Force the message bus to fork and become a daemon, even if the configuration …'
complete -c dbus-daemon -l nofork -d 'Force the message bus not to fork and become a daemon, even if the configurat…'
complete -c dbus-daemon -l print-address -d 'Print the address of the message bus to standard output, or to the given file…'
complete -c dbus-daemon -l print-pid -d 'Print the process ID of the message bus to standard output, or to the given f…'
complete -c dbus-daemon -l session -d 'Use the standard configuration file for the per-login-session message bus'
complete -c dbus-daemon -l system -d 'Use the standard configuration file for the systemwide message bus'
complete -c dbus-daemon -l version -d 'Print the version of the daemon'
complete -c dbus-daemon -l introspect -d 'Print the introspection information for all D-Bus internal interfaces'
complete -c dbus-daemon -l address -d 'Set the address to listen on'
complete -c dbus-daemon -l systemd-activation -d 'Enable systemd-style service activation'
complete -c dbus-daemon -l nopidfile -d 'Don\\*(Aqt write a PID file even if one is configured in the configuration fil…'
complete -c dbus-daemon -l syslog -d 'Force the message bus to use the system log for messages, in addition to writ…'
complete -c dbus-daemon -l syslog-only -d 'Force the message bus to use the system log for messages, and not duplicate t…'
complete -c dbus-daemon -l nosyslog -d 'Force the message bus to use only standard error for messages, even if the co…'

