# ddstdecode
# Autogenerated from man page /usr/share/man/man1/ddstdecode.1.gz
complete -c ddstdecode -s d -d 'Basename of . pbm file for saving decompressed planes'
complete -c ddstdecode -s h -d 'Print hex file offsets'
complete -c ddstdecode -s o -d 'Print file offsets'
complete -c ddstdecode -s D -d 'Set Debug level [0]'

