# deallocvt
# Autogenerated from man page /usr/share/man/man1/deallocvt.1.gz
complete -c deallocvt -s V -l version -d 'print program version and exit'
complete -c deallocvt -s h -l help -d 'show this text and exit.  SEE ALSO chvt (1), openvt (1)'

