# debconf-show
# Autogenerated from man page /usr/share/man/man1/debconf-show.1.gz
complete -c debconf-show -l db -d 'Specify the database to query'
complete -c debconf-show -l listowners -d 'Lists all owners of questions in the database'

