# deja-dup
# Autogenerated from man page /usr/share/man/man1/deja-dup.1.gz
complete -c deja-dup -s h -l help -d 'Show help options'
complete -c deja-dup -l help-all -d 'Show all help options'
complete -c deja-dup -l help-gtk -d 'Show GTK Options'
complete -c deja-dup -l version -d 'Show version'
complete -c deja-dup -l restore -d 'Restore given files'
complete -c deja-dup -l backup -d 'Immediately start a backup SEE ALSO duplicity (1)'

