# deluser
# Autogenerated from man page /usr/share/man/man8/deluser.8.gz
complete -c deluser -l conf -d 'Use FILE instead of the default files R /etc/deluser. conf and R /etc/adduser'
complete -c deluser -l group -d 'Remove a group'
complete -c deluser -l help -d 'Display brief instructions'
complete -c deluser -l quiet -d 'Suppress progress messages'
complete -c deluser -l system -d 'Only delete if user/group is a system user/group'
complete -c deluser -l only-if-empty -d 'Only remove if no members are left'
complete -c deluser -l backup -d 'Backup all files contained in the userhome and the mailspool-file to a file n…'
complete -c deluser -l backup-to -d 'Place the backup files not in / but in the directory specified by this parame…'
complete -c deluser -l remove-home -d 'Remove the home directory of the user and its mailspool'
complete -c deluser -l remove-all-files -d 'Remove all files from the system owned by this user'
complete -c deluser -l force -d 'parameter; this may prevent to remove the root user by accident'
complete -c deluser -l version -d 'Display version and copyright information.  RETURN VALUE'

