# diff3
# Autogenerated from man page /usr/share/man/man1/diff3.1.gz
complete -c diff3 -s A -l show-all -d 'output all changes, bracketing conflicts'
complete -c diff3 -s e -l ed -d 'output ed script incorporating changes from OLDFILE to YOURFILE into MYFILE'
complete -c diff3 -s E -l show-overlap -d 'like -e, but bracket conflicts'
complete -c diff3 -s 3 -l easy-only -d 'like -e, but incorporate only nonoverlapping changes'
complete -c diff3 -s x -l overlap-only -d 'like -e, but incorporate only overlapping changes'
complete -c diff3 -s X -d 'like -x, but bracket conflicts'
complete -c diff3 -s i -d 'append \'w\' and \'q\' commands to ed scripts'
complete -c diff3 -s m -l merge -d 'output actual merged file, according to -A if no other options are given'
complete -c diff3 -s a -l text -d 'treat all files as text'
complete -c diff3 -l strip-trailing-cr -d 'strip trailing carriage return on input'
complete -c diff3 -s T -l initial-tab -d 'make tabs line up by prepending a tab'
complete -c diff3 -l diff-program -d 'use PROGRAM to compare files'
complete -c diff3 -s L -l label -d 'use LABEL instead of file name (can be repeated up to three times)'
complete -c diff3 -l help -d 'display this help and exit'
complete -c diff3 -s v -l version -d 'output version information and exit'

