# dig
# Autogenerated from man page /usr/share/man/man1/dig.1.gz
complete -c dig -s 4 -d 'This option indicates that only IPv4 should be used'
complete -c dig -s 6 -d 'This option indicates that only IPv6 should be used'
complete -c dig -s b -d 'This option sets the source IP address of the query'
complete -c dig -s c -d 'This option sets the query class'
complete -c dig -s f -d 'This option sets batch mode, in which dig reads a list of lookup requests to …'
complete -c dig -s k -d 'This option tells named to sign queries using TSIG using a key read from the …'
complete -c dig -s m -d 'This option enables memory usage debugging'
complete -c dig -s p -d 'This option sends the query to a non-standard port on the server, instead of …'
complete -c dig -s q -d 'This option specifies the domain name to query'
complete -c dig -s r -d 'This option indicates that options from ${HOME}/. digrc should not be read'
complete -c dig -s t -d 'This option indicates the resource record type to query, which can be any val…'
complete -c dig -s u -d 'This option indicates that print query times should be provided in microsecon…'
complete -c dig -s v -d 'This option prints the version number and exits'
complete -c dig -s x -d 'This option sets simplified reverse lookups, for mapping addresses to names'
complete -c dig -s y -d 'This option signs queries using TSIG with the given authentication key'

