# dircolors
# Autogenerated from man page /usr/share/man/man1/dircolors.1.gz
complete -c dircolors -s b -l sh -l bourne-shell -d 'output Bourne shell code to set LS_COLORS'
complete -c dircolors -s c -l csh -l c-shell -d 'output C shell code to set LS_COLORS'
complete -c dircolors -s p -l print-database -d 'output defaults'
complete -c dircolors -l help -d 'display this help and exit'
complete -c dircolors -l version -d 'output version information and exit'

