# distro-info
# Autogenerated from man page /usr/share/man/man1/distro-info.1.gz
complete -c distro-info -l date -d 'date for calculating the version (default: today)'
complete -c distro-info -s h -l help -d 'display help message and exit'
complete -c distro-info -s a -l all -d 'list all known versions'
complete -c distro-info -s y -l days -d 'display number of days until specified version reaches the specified milestone'
complete -c distro-info -s d -l devel -d 'latest development version'
complete -c distro-info -l series -d 'series to calculate the version for'
complete -c distro-info -s s -l stable -d 'latest stable version'
complete -c distro-info -l supported -d 'list of all supported versions, including development releases'
complete -c distro-info -l unsupported -d 'list of all unsupported stable versions'
complete -c distro-info -s c -l codename -d 'print the codename (default)'
complete -c distro-info -s r -l release -d 'print the release version'
complete -c distro-info -s f -l fullname -d 'print the full name SEE ALSO debian-distro-info (1), ubuntu-distro-info (1) A…'

