# dmesg
# Autogenerated from man page /usr/share/man/man1/dmesg.1.gz
complete -c dmesg -s C -l clear
complete -c dmesg -s c -l read-clear
complete -c dmesg -s D -l console-off
complete -c dmesg -s d -l show-delta
complete -c dmesg -s E -l console-on
complete -c dmesg -s e -l reltime
complete -c dmesg -s F -l file
complete -c dmesg -s f -l facility
complete -c dmesg -s H -l human
complete -c dmesg -s k -l kernel
complete -c dmesg -s L -l color
complete -c dmesg -s l -l level
complete -c dmesg -s n -l console-level
complete -c dmesg -l noescape
complete -c dmesg -s P -l nopager
complete -c dmesg -s p -l force-prefix
complete -c dmesg -s r -l raw
complete -c dmesg -s S -l syslog
complete -c dmesg -s s -l buffer-size
complete -c dmesg -s T -l ctime
complete -c dmesg -l since
complete -c dmesg -l until
complete -c dmesg -s t -l notime
complete -c dmesg -l time-format
complete -c dmesg -s u -l userspace
complete -c dmesg -s w -l follow
complete -c dmesg -s W -l follow-new
complete -c dmesg -s x -l decode
complete -c dmesg -s V -l version
complete -c dmesg -s h -l help

