# dosfslabel
# Autogenerated from man page /usr/share/man/man8/dosfslabel.8.gz
complete -c dosfslabel -s i -l volume-id -d 'Switch to volume ID mode'
complete -c dosfslabel -s r -l reset -d 'Remove label in label mode or generate new ID in volume ID mode'
complete -c dosfslabel -s c -l codepage -d 'Use DOS codepage PAGE to encode/decode label'
complete -c dosfslabel -s h -l help -d 'Display a help message and terminate'
complete -c dosfslabel -s V -l version -d 'Show version number and terminate'

