# dpkg-trigger
# Autogenerated from man page /usr/share/man/man1/dpkg-trigger.1.gz
complete -c dpkg-trigger -l admindir -d 'Change the location of the dpkg database'
complete -c dpkg-trigger -l root -d 'Set the root directory to directory, which sets the administrative directory …'
complete -c dpkg-trigger -l by-package -d 'Override trigger awaiter (normally set by dpkg through the \\s-1DPKG_MAINTSCRI…'
complete -c dpkg-trigger -l no-await -d 'This option arranges that the calling package T (if any) need not await the p…'
complete -c dpkg-trigger -l await -d 'This option does the inverse of --no-await (since dpkg 1. 17. 21)'

