# dpkg-split
# Autogenerated from man page /usr/share/man/man1/dpkg-split.1.gz
complete -c dpkg-split -l depotdir -d 'Specifies an alternative directory for the queue of parts awaiting automatic …'
complete -c dpkg-split -s S -l partsize -d 'Specifies the maximum part size when splitting, in kibibytes (1024 bytes)'
complete -c dpkg-split -s o -l output -d 'Specifies the output file name for a reassembly'
complete -c dpkg-split -s Q -l npquiet -d 'When doing automatic queue-or-reassembly dpkg-split usually prints a message …'

