# dpkg-reconfigure
# Autogenerated from man page /usr/share/man/man8/dpkg-reconfigure.8.gz
complete -c dpkg-reconfigure -o ftype -l frontend -d 'Select the frontend to use'
complete -c dpkg-reconfigure -o pvalue -l priority -d 'Specify the minimum priority of question that will be displayed'
complete -c dpkg-reconfigure -l default-priority -d 'Use whatever the default priority of question is, instead of forcing the prio…'
complete -c dpkg-reconfigure -s u -l unseen-only -d 'By default, all questions are shown, even if they have already been answered'
complete -c dpkg-reconfigure -l force -d 'Force dpkg-reconfigure to reconfigure a package even if the package is in an …'
complete -c dpkg-reconfigure -l no-reload -d 'Prevent dpkg-reconfigure from reloading templates'

