# dvihp
# Autogenerated from man page /usr/share/man/man1/dvihp.1.gz
complete -c dvihp -s A -d 'print odd pages'
complete -c dvihp -s B -d 'print even pages'
complete -c dvihp -s d -d 'set debug bits to n (see documentation)'
complete -c dvihp -s D -d 'set resolution to n'
complete -c dvihp -s f -d 'run as filter'
complete -c dvihp -s l -d 'don\'t print pages after n'
complete -c dvihp -s m -d 'manual feed'
complete -c dvihp -s n -d 'print n pages'
complete -c dvihp -s O -d 'set/change paper offset to a,b mm'
complete -c dvihp -s o -d 'output to s instead of spooling'
complete -c dvihp -s p -d 'don\'t print pages before n'
complete -c dvihp -o Ps -d 'pass directly to lpr'
complete -c dvihp -s v -d 'verbose operation'
complete -c dvihp -s x -d 'set magnification to n'
complete -c dvihp -l help -d 'write usage summary'

