# dvipos
# Autogenerated from man page /usr/share/man/man1/dvipos.1.gz
complete -c dvipos -s h -l help -d 'print usage'
complete -c dvipos -s W -l warning -d 'print warnings'
complete -c dvipos -s v -l verbose -d 'print verbose output'
complete -c dvipos -s d -l debug -d 'print   dvitype (1) debugging data'
complete -c dvipos -s s -l smashchars -d 'regard height and depth as zero'
complete -c dvipos -s o -l output -d 'send all output to FILE.   Without this option, output goes to stdout'
complete -c dvipos -s b -l bbox -d 'send bounding box to FILE (default FILE is infile. pos)'
complete -c dvipos -s f -l framed -d 'request copy of DVI file, BASE'
complete -c dvipos -s m -l mag -d 'override   tex (1) magnification by INT'
complete -c dvipos -s w -l framesize -d 'set frame rule size by INT (default 6554 = . 1pt)'
complete -c dvipos -s p -l pages -d 'set page ranges from X to Y'

