# dvitomp
# Autogenerated from man page /usr/share/man/man1/dvitomp.1.gz
complete -c dvitomp -o help -d 'write usage summary and exit'
complete -c dvitomp -o version -d 'output version information and exit'

