# dvitype
# Autogenerated from man page /usr/share/man/man1/dvitype.1.gz
complete -c dvitype -o dpi -d 'Set resolution to  REAL pixels per inch; default 300. 0. PP'
complete -c dvitype -o magnification -d 'Override existing magnification with R NUMBER . PP'
complete -c dvitype -o max-pages -d 'Process  NUMBER pages; default one million. PP'
complete -c dvitype -o output-level -d 'Verbosity level, from 0 to 4; default 4. PP'
complete -c dvitype -o page-start -d 'Start at R PAGE-SPEC , for example `2\' or `5. *. -2\'. PP'
complete -c dvitype -o show-opcodes -d 'Show numeric opcodes (in decimal)'

