# e2scrub_all
# Autogenerated from man page /usr/share/man/man8/e2scrub_all.8.gz
complete -c e2scrub_all -s n -d 'Print what commands  e2scrub_all would execute to initiate the e2scrub operat…'
complete -c e2scrub_all -s r -d 'Remove e2scrub snapshots but do not check anything'
complete -c e2scrub_all -s A -d 'Scrub all ext[234] file systems even if they are not mounted'
complete -c e2scrub_all -s V -d 'Print version information and exit.  SEE ALSO e2scrub (8) AUTHOR Darrick J'

