# e2scrub
# Autogenerated from man page /usr/share/man/man8/e2scrub.8.gz
complete -c e2scrub -s n -d 'Print what commands  e2scrub would execute to check the file system'
complete -c e2scrub -s r -d 'Remove the e2scrub snapshot and exit without checking anything'
complete -c e2scrub -s t -d 'Run  fstrim(1) on the mounted file system if no errors are found'
complete -c e2scrub -s V -d 'Print version information and exit'

