# e4defrag
# Autogenerated from man page /usr/share/man/man8/e4defrag.8.gz
complete -c e4defrag -s c -d 'Get a current fragmentation count and an ideal fragmentation count, and calcu…'
complete -c e4defrag -s v -d 'option, the current fragmentation count and the ideal fragmentation count are…'

