# ebb
# Autogenerated from man page /usr/share/man/man1/ebb.1.gz
complete -c ebb -s v -d 'Be verbose'
complete -c ebb -s q -d 'Be quiet'
complete -c ebb -s O -d 'Write output to standard output'
complete -c ebb -s m -d 'Write output in dvipdfm\'s ``bb\'\' format'

