# echo
# Autogenerated from man page /usr/share/man/man1/echo.1.gz
complete -c echo -s n -d 'do not output the trailing newline'
complete -c echo -s e -d 'enable interpretation of backslash escapes'
complete -c echo -s E -d 'disable interpretation of backslash escapes (default)'
complete -c echo -l help -d 'display this help and exit'
complete -c echo -l version -d 'output version information and exit '

