# eqn
# Autogenerated from man page /usr/share/man/man1/eqn.1.gz
complete -c eqn -s d -d 'Specify delimiters  x and\\~\\c  y for the left and right end, respectively, of…'
complete -c eqn -s C -d 'Recognize  . EQ and  '
complete -c eqn -s N -d 'Don\'t allow newlines within delimiters'
complete -c eqn -s v -d 'Print the version number'
complete -c eqn -s r -d 'Only one size reduction'
complete -c eqn -s m -d 'The minimum point-size is\\~\\c R n '
complete -c eqn -s T -d 'The output is for device R name '
complete -c eqn -s M -d 'Search  dir for  eqnrc before the default directories'
complete -c eqn -s R -d 'Don\'t load R eqnrc '
complete -c eqn -s f -d 'This is equivalent to a  gfont F command'
complete -c eqn -s s -d 'This is equivalent to a  gsize n command.  This option is deprecated'
complete -c eqn -s e -d 'option of groff '
complete -c eqn -s p -d 'This says that subscripts and superscripts should be n  points smaller than t…'

