# es2_info
# Autogenerated from man page /usr/share/man/man1/es2_info.1.gz
complete -c es2_info -o display -d 'Specify the X display to run on'
complete -c es2_info -s h -d 'Print usage information.  AUTHOR es2_info was written by Tungsten Graphics'

