# expand
# Autogenerated from man page /usr/share/man/man1/expand.1.gz
complete -c expand -s i -l initial -d 'do not convert tabs after non blanks'
complete -c expand -s t -l tabs -d 'have tabs N characters apart, not 8'
complete -c expand -l help -d 'display this help and exit'
complete -c expand -l version -d 'output version information and exit AUTHOR Written by David MacKenzie'

