# expiry
# Autogenerated from man page /usr/share/man/man1/expiry.1.gz
complete -c expiry -s c -l check -d 'Check the password expiration of the current user'
complete -c expiry -s f -l force -d 'Force a password change if the current user has an expired password'
complete -c expiry -s h -l help -d 'Display help message and exit'

