# extractbb
# Autogenerated from man page /usr/share/man/man1/extractbb.1.gz
complete -c extractbb -s v -d 'Be verbose'
complete -c extractbb -s q -d 'Be quiet'
complete -c extractbb -s O -d 'Write output to standard output'
complete -c extractbb -s m -d 'Write output in dvipdfm\'s ``bb\'\' format'

