# faillock
# Autogenerated from man page /usr/share/man/man8/faillock.8.gz
complete -c faillock -l dir -d 'The directory where the user files with the failure records are kept'
complete -c faillock -l user -d 'The user whose failure records should be displayed or cleared'
complete -c faillock -l reset -d 'Instead of displaying the user\\*(Aqs failure records, clear them'

