# fallocate
# Autogenerated from man page /usr/share/man/man1/fallocate.1.gz
complete -c fallocate -s c -l collapse-range
complete -c fallocate -s d -l dig-holes
complete -c fallocate -s i -l insert-range
complete -c fallocate -s l -l length
complete -c fallocate -s n -l keep-size
complete -c fallocate -s o -l offset
complete -c fallocate -s p -l punch-hole
complete -c fallocate -s v -l verbose
complete -c fallocate -s x -l posix
complete -c fallocate -s z -l zero-range
complete -c fallocate -s V -l version
complete -c fallocate -s h -l help

