# fc-validate
# Autogenerated from man page /usr/share/man/man1/fc-validate.1.gz
complete -c fc-validate -s i -d 'Only query face indexed index of each file'
complete -c fc-validate -s l -d 'Set lang as a language instead of current locale.  this is used for -m'
complete -c fc-validate -s v -d 'Show more detailed information'
complete -c fc-validate -s V -d 'Show version of the program and exit'
complete -c fc-validate -s h -d 'Show summary of options'

