# fcat
# Autogenerated from man page /usr/share/man/man1/fcat.1.gz
complete -c fcat -s f -d 'Specifies the file system type'
complete -c fcat -s h -d 'Skip over holes in sparse files, so that absolute address information is lost'
complete -c fcat -s R -d 'Suppress errors if a deleted file is being recovered'
complete -c fcat -s s -d 'Include the slack space in the output'
complete -c fcat -s i -d 'Identify the type of image file, such as raw'
complete -c fcat -s o -d 'The sector offset where the file system starts in the image'
complete -c fcat -s b -d 'The size, in bytes, of the underlying device sectors'
complete -c fcat -s v -d 'Enable verbose mode, output to stderr'
complete -c fcat -s V -d 'Display version  image [images] The disk or partition image to read, whose fo…'

