# ffmpegthumbnailer
# Autogenerated from man page /usr/share/man/man1/ffmpegthumbnailer.1.gz
complete -c ffmpegthumbnailer -o 'i<s>' -d ': input file'
complete -c ffmpegthumbnailer -o 'o<s>' -d ': output file'
complete -c ffmpegthumbnailer -o 's<n>' -d ': thumbnail size (use 0 for original size) (default: 128)'
complete -c ffmpegthumbnailer -o 'q<n>' -d ': image quality (0 = bad, 10 = best) (default: 8) (only for jpeg)'
complete -c ffmpegthumbnailer -o 'c<s>' -d ': override image format (jpeg or png) (default: determined by filename)'
complete -c ffmpegthumbnailer -o 't<n' -d ': time to seek to (percentage or absolute time hh:mm:ss) (default: 10%)'
complete -c ffmpegthumbnailer -s a -d ': ignore aspect ratio and generate square thumbnail'
complete -c ffmpegthumbnailer -s f -d ': create a movie strip overlay'
complete -c ffmpegthumbnailer -s m -d ': prefer embedded image metadata over video content'
complete -c ffmpegthumbnailer -s h -d ': display this help AUTHOR Written by Dirk Vanden Boer'

