# file-roller
# Autogenerated from man page /usr/share/man/man1/file-roller.1.gz
complete -c file-roller -s a -l add-to -d 'Add files to the specified archive and quit the program'
complete -c file-roller -s d -l add -d 'Add files asking the name of the archive and quit the program'
complete -c file-roller -s e -l extract-to -d 'Extract archives to the specified folder and quit the program'
complete -c file-roller -s f -l extract -d 'Extract archives asking the destination folder and quit the program'
complete -c file-roller -s h -l extract-here -d 'Extract archives using the archive name as destination folder and quit the pr…'
complete -c file-roller -l default-dir -d 'Default folder to use for the \'--add\' and \'--extract\' commands'
complete -c file-roller -l force -d 'Create destination folder without asking confirmation'

