# fincore
# Autogenerated from man page /usr/share/man/man1/fincore.1.gz
complete -c fincore -s n -l noheadings
complete -c fincore -s b -l bytes
complete -c fincore -s o -l output
complete -c fincore -s r -l raw
complete -c fincore -s J -l json
complete -c fincore -s V -l version
complete -c fincore -s h -l help

