# findmnt
# Autogenerated from man page /usr/share/man/man8/findmnt.8.gz
complete -c findmnt -s A -l all
complete -c findmnt -s a -l ascii
complete -c findmnt -s b -l bytes
complete -c findmnt -s C -l nocanonicalize
complete -c findmnt -s c -l canonicalize
complete -c findmnt -s D -l df
complete -c findmnt -s d -l direction
complete -c findmnt -s e -l evaluate
complete -c findmnt -s F -l tab-file
complete -c findmnt -s f -l first-only
complete -c findmnt -s h -l help
complete -c findmnt -s i -l invert
complete -c findmnt -s J -l json
complete -c findmnt -s k -l kernel
complete -c findmnt -s l -l list
complete -c findmnt -s M -l mountpoint
complete -c findmnt -s m -l mtab
complete -c findmnt -s N -l task
complete -c findmnt -s n -l noheadings
complete -c findmnt -s O -l options
complete -c findmnt -s o -l output
complete -c findmnt -l output-all
complete -c findmnt -s P -l pairs
complete -c findmnt -s p -l poll
complete -c findmnt -l pseudo
complete -c findmnt -l shadow
complete -c findmnt -s R -l submounts
complete -c findmnt -s r -l raw
complete -c findmnt -l real
complete -c findmnt -s S -l source
complete -c findmnt -s s -l fstab
complete -c findmnt -s T -l target
complete -c findmnt -s t -l types
complete -c findmnt -l tree
complete -c findmnt -l shadowed
complete -c findmnt -s U -l uniq
complete -c findmnt -s u -l notruncate
complete -c findmnt -s v -l nofsroot
complete -c findmnt -s w -l timeout
complete -c findmnt -s x -l verify
complete -c findmnt -l verbose
complete -c findmnt -l vfs-all

