# foo2zjs-pstops
# Autogenerated from man page /usr/share/man/man1/foo2zjs-pstops.1.gz
complete -c foo2zjs-pstops -s a -d 'Accurate screens code'
complete -c foo2zjs-pstops -s c -d 'CIE Color'
complete -c foo2zjs-pstops -s n -d 'Neuter CUPS cupsPSLevel2'
complete -c foo2zjs-pstops -s r -d 'Rotate 90 degrees clockwise'
complete -c foo2zjs-pstops -s w -d 'Well Tempered Screens code'
complete -c foo2zjs-pstops -s D -d 'Set Debug level [0]'

