# fusermount3
# Autogenerated from man page /usr/share/man/man1/fusermount3.1.gz
complete -c fusermount3 -s h -d 'print help'
complete -c fusermount3 -s V -d 'print version'
complete -c fusermount3 -s o -d 'mount options'
complete -c fusermount3 -s u -d unmount
complete -c fusermount3 -s q -d quiet
complete -c fusermount3 -s z -d 'lazy unmount'

