# getopt
# Autogenerated from man page /usr/share/man/man1/getopt.1.gz
complete -c getopt -s a -l alternative
complete -c getopt -s h -l help
complete -c getopt -s l -l longoptions
complete -c getopt -s n -l name
complete -c getopt -s o -l options
complete -c getopt -s q -l quiet
complete -c getopt -s Q -l quiet-output
complete -c getopt -s s -l shell
complete -c getopt -s T -l test
complete -c getopt -s u -l unquoted
complete -c getopt -s V -l version

