# getty
# Autogenerated from man page /usr/share/man/man8/getty.8.gz
complete -c getty -s 8 -l 8bits
complete -c getty -s a -l autologin
complete -c getty -s c -l noreset
complete -c getty -s E -l remote
complete -c getty -s f -l issue-file
complete -c getty -l show-issue
complete -c getty -s h -l flow-control
complete -c getty -s H -l host
complete -c getty -s i -l noissue
complete -c getty -s I -l init-string
complete -c getty -s J -l noclear
complete -c getty -s l -l login-program
complete -c getty -s L -l local-line
complete -c getty -s m -l extract-baud
complete -c getty -l list-speeds
complete -c getty -s n -l skip-login
complete -c getty -s N -l nonewline
complete -c getty -s o -l login-options
complete -c getty -s p -l login-pause
complete -c getty -s r -l chroot
complete -c getty -s R -l hangup
complete -c getty -s s -l keep-baud
complete -c getty -s t -l timeout
complete -c getty -s U -l detect-case
complete -c getty -s w -l wait-cr
complete -c getty -l nohints
complete -c getty -l nohostname
complete -c getty -l long-hostname
complete -c getty -l erase-chars
complete -c getty -l kill-chars
complete -c getty -l chdir
complete -c getty -l delay
complete -c getty -l nice
complete -c getty -l reload
complete -c getty -l version
complete -c getty -l help

