# gftodvi
# Autogenerated from man page /usr/share/man/man1/gftodvi.1.gz
complete -c gftodvi -o overflow-label-offset -d 'specifies the distance from the right edge of the character bounding box at w…'
complete -c gftodvi -o verbose -d 'option, gftodvi operates silently'

