# glib-compile-schemas
# Autogenerated from man page /usr/share/man/man1/glib-compile-schemas.1.gz
complete -c glib-compile-schemas -s h -l help -d 'Print help and exit'
complete -c glib-compile-schemas -l version -d 'Print program version and exit'
complete -c glib-compile-schemas -l targetdir -d 'Store gschemas. compiled in the TARGET directory instead of DIRECTORY'
complete -c glib-compile-schemas -l strict -d 'Abort on any errors in schemas'
complete -c glib-compile-schemas -l dry-run -d 'Don\\*(Aqt write gschemas. compiled.  This option can be used to check '
complete -c glib-compile-schemas -l allow-any-name -d 'Do not enforce restrictions on key names'

