# gnome-2048
# Autogenerated from man page /usr/share/man/man6/gnome-2048.6.gz
complete -c gnome-2048 -l cli -d 'Play in the terminal.  See â--cli=helpâ for documentation'
complete -c gnome-2048 -s s -l size -d 'Changes the size of the grid'
complete -c gnome-2048 -s v -l version -d 'Prints the program version and exits'

