# gnome-system-monitor
# Autogenerated from man page /usr/share/man/man1/gnome-system-monitor.1.gz
complete -c gnome-system-monitor -s s -l simple -d 'Show a simple dialog to end processes and log out.   AUTHOR '

