# gpg-connect-agent
# Autogenerated from man page /usr/share/man/man1/gpg-connect-agent.1.gz
complete -c gpg-connect-agent -s v -d 'TQ   --verbose Output additional information while running'
complete -c gpg-connect-agent -l verbose -d 'Output additional information while running'
complete -c gpg-connect-agent -s q
complete -c gpg-connect-agent -l quiet -d 'Try to be as quiet as possible'
complete -c gpg-connect-agent -l homedir -d 'Set the name of the home directory to dir'
complete -c gpg-connect-agent -l agent-program -d 'Specify the agent program to be started if none is running'
complete -c gpg-connect-agent -l dirmngr-program -d 'Specify the directory manager (keyserver client) program to be started if non…'
complete -c gpg-connect-agent -l dirmngr -d 'Connect to a running directory manager (keyserver client) instead of to the g…'
complete -c gpg-connect-agent -s S
complete -c gpg-connect-agent -l raw-socket -d 'Connect to socket name assuming this is an Assuan style server'
complete -c gpg-connect-agent -s E
complete -c gpg-connect-agent -l exec -d 'Take the rest of the command line as a program and it\'s arguments and execute…'
complete -c gpg-connect-agent -l no-ext-connect -d 'When using -S or --exec, gpg-connect-agent connects to the Assuan server in e…'
complete -c gpg-connect-agent -l no-autostart -d 'Do not start the gpg-agent or the dirmngr if it has not yet been started'
complete -c gpg-connect-agent -s r
complete -c gpg-connect-agent -l run -d 'Run the commands from file at startup and then continue with the regular inpu…'
complete -c gpg-connect-agent -s s
complete -c gpg-connect-agent -l subst -d 'Run the command /subst at startup'
complete -c gpg-connect-agent -l hex -d 'Print data lines in a hex format and the ASCII representation of non-control …'
complete -c gpg-connect-agent -l decode -d 'Decode data lines'

