# gpg-preset-passphrase
# Autogenerated from man page /usr/share/man/man1/gpg-preset-passphrase.1.gz
complete -c gpg-preset-passphrase -l preset -d 'Preset a passphrase.  This is what you usually will use'
complete -c gpg-preset-passphrase -l forget -d 'Flush the passphrase for the given cache ID from the cache'
complete -c gpg-preset-passphrase -s v -d 'TQ   --verbose Output additional information while running'
complete -c gpg-preset-passphrase -l max-cache-ttl -d 'this passphrase presetting by starting gpg-agent with the'
complete -c gpg-preset-passphrase -l allow-preset-passphrase -d 'gpg-preset-passphrase is invoked this way: gpg-preset-passphrase [options] [c…'
complete -c gpg-preset-passphrase -l verbose -d 'Output additional information while running'
complete -c gpg-preset-passphrase -s P
complete -c gpg-preset-passphrase -l passphrase -d 'Instead of reading the passphrase from stdin, use the supplied string as pass…'

