# gpgsplit
# Autogenerated from man page /usr/share/man/man1/gpgsplit.1.gz
complete -c gpgsplit -s v -l verbose -d Verbose
complete -c gpgsplit -s p -l prefix -d 'Prepend filenames with STRING'
complete -c gpgsplit -l uncompress -d 'Uncompress a packet'
complete -c gpgsplit -l secret-to-public -d 'Convert secret keys to public keys'
complete -c gpgsplit -l no-split -d 'Write to stdout and don\'t actually split'

