# grotty
# Autogenerated from man page /usr/share/man/man1/grotty.1.gz
complete -c grotty -s b -d 'Suppress the use of overstriking for bold characters'
complete -c grotty -s B -d 'Use only overstriking for bold-italic characters.  Ignored if  -c isn\'t used'
complete -c grotty -s c -d 'Use  grotty \'s old output format (see above)'
complete -c grotty -s d -d 'Ignore all  \\[rs]D commands.  Without this  grotty renders  \\[rs]D\'l\\|. \\|'
complete -c grotty -s f -d 'Use form feeds in the output'
complete -c grotty -s F -d 'Prepend directory '
complete -c grotty -s h -d 'Use horizontal tabs in the output'
complete -c grotty -s i -d 'Use escape sequences to set the italic text attribute instead of the underlin…'
complete -c grotty -s o -d 'Suppress overstriking (other than for bold or underlined characters in case t…'
complete -c grotty -s r -d 'Use escape sequences to set the reverse text attribute instead of the underli…'
complete -c grotty -s u -d 'Suppress the use of underlining for italic characters'
complete -c grotty -s U -d 'Use only underlining for bold-italic characters.  Ignored if  -c isn\'t used'
complete -c grotty -o Tascii
complete -c grotty -o Tlatin1 -d or
complete -c grotty -o Tutf8 -d 'option on ASCII based systems, and with'
complete -c grotty -o Tcp1047 -d and
complete -c grotty -s R -d 'option of less (1) to disable the interpretation of grotty \'s old output form…'
complete -c grotty -s P -d 'option of man to set the pager executable and its options, or modify the conf…'
complete -c grotty -s v -d 'Print the version number'

