# groupadd
# Autogenerated from man page /usr/share/man/man8/groupadd.8.gz
complete -c groupadd -s f -l force -d 'This option causes the command to simply exit with success status if the spec…'
complete -c groupadd -s g -l gidGID -d 'The numerical value of the group\\*(Aqs ID'
complete -c groupadd -s h -l help -d 'Display help message and exit'
complete -c groupadd -s K -l keyKEY -d 'Overrides /etc/login. defs defaults (GID_MIN, GID_MAX and others)'
complete -c groupadd -s o -l non-unique -d 'This option permits to add a group with a non-unique GID'
complete -c groupadd -s p -l passwordPASSWORD -d 'The encrypted password, as returned by crypt(3)'
complete -c groupadd -s r -l system -d 'Create a system group'
complete -c groupadd -s R -l rootCHROOT_DIR -d 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c groupadd -s P -l prefixPREFIX_DIR -d 'Apply changes in the PREFIX_DIR directory and use the configuration files fro…'
complete -c groupadd -l gid
complete -c groupadd -l key
complete -c groupadd -l password
complete -c groupadd -l root
complete -c groupadd -l prefix

