# grpunconv
# Autogenerated from man page /usr/share/man/man8/grpunconv.8.gz
complete -c grpunconv -s h -l help -d 'Display help message and exit'
complete -c grpunconv -s R -l rootCHROOT_DIR -d 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c grpunconv -l root

