# grub-reboot
# Autogenerated from man page /usr/share/man/man8/grub-reboot.8.gz
complete -c grub-reboot -s h -l help -d 'print this message and exit'
complete -c grub-reboot -s V -l version -d 'print the version information and exit'
complete -c grub-reboot -l boot-directory -d 'expect GRUB images under the directory DIR/grub instead of the ,/boot/grub/ d…'

