# grub-mkfont
# Autogenerated from man page /usr/share/man/man1/grub-mkfont.1.gz
complete -c grub-mkfont -s a -l force-autohint -d 'force autohint'
complete -c grub-mkfont -s b -l bold -d 'convert to bold font'
complete -c grub-mkfont -s c -l asce -d 'set font ascent'
complete -c grub-mkfont -s d -l desc -d 'set font descent'
complete -c grub-mkfont -s i -l index -d 'select face index'
complete -c grub-mkfont -s n -l name -d 'set font family name'
complete -c grub-mkfont -l no-bitmap -d 'ignore bitmap strikes when loading'
complete -c grub-mkfont -l no-hinting -d 'disable hinting'
complete -c grub-mkfont -s o -l output -d 'save output in FILE [required]'
complete -c grub-mkfont -s r -l range -d 'set font range'
complete -c grub-mkfont -s s -l size -d 'set font size'
complete -c grub-mkfont -s v -l verbose -d 'print verbose messages'
complete -c grub-mkfont -s '?' -l help -d 'give this help list'
complete -c grub-mkfont -l usage -d 'give a short usage message'
complete -c grub-mkfont -s V -l version -d 'print program version'

