# grub-fstest
# Autogenerated from man page /usr/share/man/man1/grub-fstest.1.gz
complete -c grub-fstest -s c -l diskcount -d 'Specify the number of input files'
complete -c grub-fstest -s C -l crypto -d 'Mount crypto devices'
complete -c grub-fstest -s d -l debug -d 'Set debug environment variable'
complete -c grub-fstest -s K -l zfs-key -d 'Load zfs crypto key'
complete -c grub-fstest -s n -l length -d 'Handle N bytes in output file'
complete -c grub-fstest -s r -l root -d 'Set root device'
complete -c grub-fstest -s s -l skip -d 'Skip N bytes from output file'
complete -c grub-fstest -s u -l uncompress -d 'Uncompress data'
complete -c grub-fstest -s v -l verbose -d 'print verbose messages'
complete -c grub-fstest -s '?' -l help -d 'give this help list'
complete -c grub-fstest -l usage -d 'give a short usage message'
complete -c grub-fstest -s V -l version -d 'print program version'

