# grub-mkdevicemap
# Autogenerated from man page /usr/share/man/man8/grub-mkdevicemap.8.gz
complete -c grub-mkdevicemap -s n -l no-floppy -d 'do not probe any floppy drive '
complete -c grub-mkdevicemap -s m -l device-map -d 'use FILE as the device map [default=/boot/grub/device. map]'
complete -c grub-mkdevicemap -s h -l help -d 'display this message and exit'
complete -c grub-mkdevicemap -s V -l version -d 'print version information and exit'
complete -c grub-mkdevicemap -s s -l probe-second-floppy
complete -c grub-mkdevicemap -s v -l verbose -d 'print verbose messages REPORTING BUGS Report bugs to <bug-grub@gnu. org>'

