# grub-macbless
# Autogenerated from man page /usr/share/man/man8/grub-macbless.8.gz
complete -c grub-macbless -s p -l ppc -d 'bless for ppc-based macs'
complete -c grub-macbless -s v -l verbose -d 'print verbose messages'
complete -c grub-macbless -s x -l x86 -d 'bless for x86-based macs'
complete -c grub-macbless -s '?' -l help -d 'give this help list'
complete -c grub-macbless -l usage -d 'give a short usage message'
complete -c grub-macbless -s V -l version -d 'print program version REPORTING BUGS Report bugs to <bug-grub@gnu. org>'

