# grub-mkconfig
# Autogenerated from man page /usr/share/man/man8/grub-mkconfig.8.gz
complete -c grub-mkconfig -s o -l output -d 'output generated config to FILE [default=stdout]'
complete -c grub-mkconfig -s h -l help -d 'print this message and exit'
complete -c grub-mkconfig -s V -l version -d 'print the version information and exit REPORTING BUGS Report bugs to <bug-gru…'

