# grub-mount
# Autogenerated from man page /usr/share/man/man1/grub-mount.1.gz
complete -c grub-mount -s C -l crypto -d 'Mount crypto devices'
complete -c grub-mount -s d -l debug -d 'Set debug environment variable'
complete -c grub-mount -s K -l zfs-key -d 'Load zfs crypto key'
complete -c grub-mount -s r -l root -d 'Set root device'
complete -c grub-mount -s v -l verbose -d 'print verbose messages'
complete -c grub-mount -s '?' -l help -d 'give this help list'
complete -c grub-mount -l usage -d 'give a short usage message'
complete -c grub-mount -s V -l version -d 'print program version'

