# grub-render-label
# Autogenerated from man page /usr/share/man/man1/grub-render-label.1.gz
complete -c grub-render-label -s b -l bgcolor -d 'use COLOR for background'
complete -c grub-render-label -s c -l color -d 'use COLOR for text'
complete -c grub-render-label -s f -l font -d 'use FILE as font (PF2)'
complete -c grub-render-label -s i -l input -d 'read text from FILE'
complete -c grub-render-label -s o -l output -d 'set output filename.  Default is STDOUT'
complete -c grub-render-label -s t -l text -d 'set the label to render'
complete -c grub-render-label -s v -l verbose -d 'print verbose messages'
complete -c grub-render-label -s '?' -l help -d 'give this help list'
complete -c grub-render-label -l usage -d 'give a short usage message'
complete -c grub-render-label -s V -l version -d 'print program version'

