# gsbj
# Autogenerated from man page /usr/share/man/man1/gsbj.1.gz
complete -c gsbj -l add-to-space -d 'add the given number of 1/72" units to the width of each space (may be negati…'
complete -c gsbj -l add-to-width -d 'add the given number of 1/72" units to the width of each character (may be ne…'
complete -c gsbj -l columns -d 'print in <n> columns'
complete -c gsbj -l detect -d 'treat the file as PostScript if it starts with %!'
complete -c gsbj -l first-page -d 'start printing at page <n>'
complete -c gsbj -l kern -d 'kern using information from the given . AFM file'
complete -c gsbj -l last-page -d 'stop printing after page <n>'
complete -c gsbj -o 12BclqRr -o 'b<header>' -o 'f<font>' -o 'F<hfont>' -o 'L<lines>' -o 'p<outfile>' -d 'Sun switches implemented:'
complete -c gsbj -o 'T<n>	set' -d 'Switches ignored:'
complete -c gsbj -o GghKkmow -s '#' -s C -s d -s J -s n -s P -s S -s s -s t -s v -d 'Switches added:'
complete -c gsbj -l spacing -d 'use double (n=2), triple (n=3), etc.  spacing'

