# gthumb
# Autogenerated from man page /usr/share/man/man1/gthumb.1.gz
complete -c gthumb -s f -l fullscreen -d 'Start in fullscreen mode'
complete -c gthumb -s s -l slideshow -d 'Automatically start a slideshow'
complete -c gthumb -l import-photos -d 'Automatically import digital camera photos'
complete -c gthumb -l help -d 'Output help information and exit'
complete -c gthumb -l version -d 'Output version information and exit'

