# gtk-builder-tool
# Autogenerated from man page /usr/share/man/man1/gtk-builder-tool.1.gz
complete -c gtk-builder-tool -l replace
complete -c gtk-builder-tool -l id
complete -c gtk-builder-tool -l css

