# gtk-launch
# Autogenerated from man page /usr/share/man/man1/gtk-launch.1.gz
complete -c gtk-launch -s '?' -l help -d 'Prints a short help text and exits'
complete -c gtk-launch -l version -d 'Prints the program version and exits'

