# gtk4-launch
# Autogenerated from man page /usr/share/man/man1/gtk4-launch.1.gz
complete -c gtk4-launch -s '?' -s h -l help -d 'Print the command\'s help and exit'
complete -c gtk4-launch -l version -d 'Print the command\'s version and exit.  ENVIRONMENT'

