# gtk4-update-icon-cache
# Autogenerated from man page /usr/share/man/man1/gtk4-update-icon-cache.1.gz
complete -c gtk4-update-icon-cache -s f -l force -d 'Overwrite an existing cache file even if it appears to be up-to-date'
complete -c gtk4-update-icon-cache -s t -l ignore-theme-index -d 'Don\'t check for the existence of index. theme in the icon theme directory'
complete -c gtk4-update-icon-cache -s i -l index-only -d 'Don\'t include image data in the cache'
complete -c gtk4-update-icon-cache -l include-image-data -d 'Include image data in the cache'
complete -c gtk4-update-icon-cache -s c -l source -d 'Output a C header file declaring a constant NAME with the contents of the ico…'
complete -c gtk4-update-icon-cache -s q -l quiet -d 'Turn off verbose output'
complete -c gtk4-update-icon-cache -s v -l validate -d 'Validate existing icon cache'

