# gvfsd
# Autogenerated from man page /usr/share/man/man1/gvfsd.1.gz
complete -c gvfsd -s h -l help -d 'Prints a short help text and exits'
complete -c gvfsd -l version -d 'Shows the version number and exits'
complete -c gvfsd -s r -l replace -d 'Replace the currently running gvfsd instance'
complete -c gvfsd -l no-fuse -d 'Don\\*(Aqt start the fuse filesystem'
complete -c gvfsd -s d -l debug -d 'Enable debug output'

