# gvfsd-metadata
# Autogenerated from man page /usr/share/man/man1/gvfsd-metadata.1.gz
complete -c gvfsd-metadata -s h -l help -d 'Prints a short help text and exits'
complete -c gvfsd-metadata -l version -d 'Shows the version number and exits'
complete -c gvfsd-metadata -s r -l replace -d 'Replace the currently running instance'

