# h2ph
# Autogenerated from man page /usr/share/man/man1/h2ph.1.gz
complete -c h2ph -s d -d 'Put the resulting '
complete -c h2ph -s r -d 'Run recursively; if any of headerfiles are directories, then run h2ph on all …'
complete -c h2ph -s a -d 'Run automagically; convert headerfiles, as well as any '
complete -c h2ph -s l -d 'Symbolic links will be replicated in the destination directory'
complete -c h2ph -s h -d 'Put \'hints\' in the . ph files which will help in locating problems with h2ph'
complete -c h2ph -s e -d 'If an error is encountered during conversion, output file will be removed and…'
complete -c h2ph -s D -d 'Include the code from the . h file as a comment in the . ph file'

