# hbpldecode
# Autogenerated from man page /usr/share/man/man1/hbpldecode.1.gz
complete -c hbpldecode -s d -d 'Basename of . pbm file for saving decompressed planes'
complete -c hbpldecode -s h -d 'Print hex file offsets'
complete -c hbpldecode -s o -d 'Print file offsets'
complete -c hbpldecode -s D -d 'Set Debug level [0]'

