# hciconfig
# Autogenerated from man page /usr/share/man/man1/hciconfig.1.gz
complete -c hciconfig -s a -l all -d 'Print features, packet type, link policy, link mode, class, Version other tha…'
complete -c hciconfig -s h -l help -d 'Show help options'

