# hd
# Autogenerated from man page /usr/share/man/man1/hd.1.gz
complete -c hd -s b -l one-byte-octal
complete -c hd -s c -l one-byte-char
complete -c hd -s C -l canonical
complete -c hd -s d -l two-bytes-decimal
complete -c hd -s e -l format
complete -c hd -s f -l format-file
complete -c hd -s L -l color
complete -c hd -s n -l length
complete -c hd -s o -l two-bytes-octal
complete -c hd -s s -l skip
complete -c hd -s v -l no-squeezing
complete -c hd -s x -l two-bytes-hex
complete -c hd -s V -l version
complete -c hd -s h -l help

