# head
# Autogenerated from man page /usr/share/man/man1/head.1.gz
complete -c head -s c -l bytes -d 'print the first NUM bytes of each file; with the leading \'-\', print all but t…'
complete -c head -s n -l lines -d 'print the first NUM lines instead of the first 10; with the leading \'-\', prin…'
complete -c head -s q -l quiet -l silent -d 'never print headers giving file names'
complete -c head -s v -l verbose -d 'always print headers giving file names'
complete -c head -s z -l zero-terminated -d 'line delimiter is NUL, not newline'
complete -c head -l help -d 'display this help and exit'
complete -c head -l version -d 'output version information and exit'

