# hfind
# Autogenerated from man page /usr/share/man/man1/hfind.1.gz
complete -c hfind -s i -d 'Create an index file for the database'
complete -c hfind -s f -d 'Specify the location of a file that contains one hash value per line'
complete -c hfind -s e -d 'Extended mode.   Additional information besides just the name is printed'
complete -c hfind -s q -d 'Quick mode'
complete -c hfind -s V -d 'Display version db_file The location of the hash database file'

