# hipercdecode
# Autogenerated from man page /usr/share/man/man1/hipercdecode.1.gz
complete -c hipercdecode -s d -d 'Basename of . pbm file for saving decompressed planes'
complete -c hipercdecode -s h -d 'Print hex file offsets'
complete -c hipercdecode -s o -d 'Print file offsets'
complete -c hipercdecode -s D -d 'Set Debug level [0]'

