# hostnamectl
# Autogenerated from man page /usr/share/man/man1/hostnamectl.1.gz
complete -c hostnamectl -l no-ask-password -d 'Do not query the user for authentication for privileged operations'
complete -c hostnamectl -l static -l transient -l pretty -d 'If status is invoked (or no explicit command is given) and one of these switc…'
complete -c hostnamectl -s H -l host -d 'Execute the operation remotely'
complete -c hostnamectl -s M -l machine -d 'Execute operation on a local container'
complete -c hostnamectl -s h -l help -d 'Print a short help text and exit'
complete -c hostnamectl -l version -d 'Print a short version string and exit'
complete -c hostnamectl -l json -d 'Shows output formatted as JSON'

