# hp-colorcal
# Autogenerated from man page /usr/share/man/man1/hp-colorcal.1.gz
complete -c hp-colorcal -o 'd<device-uri>' -l device -d 'To specify a CUPS printer:'
complete -c hp-colorcal -o 'p<printer>' -l printer -d 'MODE Run in interactive mode:'
complete -c hp-colorcal -s i -l interactive -d 'OPTIONS Set the logging level:'
complete -c hp-colorcal -o 'l<level>' -l logging -d '<level>: none, info*, error, warn, debug (*default) Run in debug mode:'
complete -c hp-colorcal -s g -o ldebug -d 'This help information:'
complete -c hp-colorcal -s h -l help -d 'SEE ALSO hp-align hp-clean hp-linefeedcal hp-pqdiag AUTHOR HPLIP (HP Linux Im…'

