# hp-config_usb_printer
# Autogenerated from man page /usr/share/man/man1/hp-config_usb_printer.1.gz
complete -c hp-config_usb_printer -o 'l<level>' -l logging -d '<level>: none, info*, error, warn, debug (*default) Run in debug mode:'
complete -c hp-config_usb_printer -s g -o ldebug -d 'This help information:'
complete -c hp-config_usb_printer -s h -l help -d 'USB BUSDEVICE USB bus:device : "xxx:yyy" where \'xxx\' is the USB bus and \'yyy\'…'

