# hp-firmware
# Autogenerated from man page /usr/share/man/man1/hp-firmware.1.gz
complete -c hp-firmware -o 'd<device-uri>' -l device -d 'To specify a CUPS printer:'
complete -c hp-firmware -o 'p<printer>' -l printer -d 'MODE Run in interactive mode:'
complete -c hp-firmware -s i -l interactive -d 'Run in non-interactive mode:'
complete -c hp-firmware -s n -l non-interactive -d 'OPTIONS Set the logging level:'
complete -c hp-firmware -o 'l<level>' -l logging -d '<level>: none, info*, error, warn, debug (*default) Run in debug mode:'
complete -c hp-firmware -s g -o ldebug -d 'This help information:'
complete -c hp-firmware -s h -l help -d 'Use USB IDs to specify printer:'
complete -c hp-firmware -s s -d 'Seconds to delay before download:'
complete -c hp-firmware -o 'y<secs>' -l delay -d 'SEE ALSO hp-plugin hp-toolbox AUTHOR HPLIP (HP Linux Imaging and Printing) is…'

