# hp-levels
# Autogenerated from man page /usr/share/man/man1/hp-levels.1.gz
complete -c hp-levels -o 'd<device-uri>' -l device -d 'To specify a CUPS printer:'
complete -c hp-levels -o 'p<printer>' -l printer -d 'MODE Run in interactive mode:'
complete -c hp-levels -s i -l interactive -d 'OPTIONS Set the logging level:'
complete -c hp-levels -o 'l<level>' -l logging -d '<level>: none, info*, error, warn, debug (*default) Run in debug mode:'
complete -c hp-levels -s g -o ldebug -d 'This help information:'
complete -c hp-levels -s h -l help -d 'Bar graph size:'
complete -c hp-levels -o 's<size>' -l size -d 'Use colored bar graphs:'
complete -c hp-levels -s c -l color -d 'Bar graph character:'
complete -c hp-levels -o 'a<char>' -l char -d 'AUTHOR HPLIP (HP Linux Imaging and Printing) is an HP developed solution for …'

