# hp-plugin
# Autogenerated from man page /usr/share/man/man1/hp-plugin.1.gz
complete -c hp-plugin -s u -l gui -d 'Run in interactive mode:'
complete -c hp-plugin -s i -l interactive -d 'Installation for required printer mode:'
complete -c hp-plugin -l required -d 'Installation for optional printer mode:'
complete -c hp-plugin -l optional -d 'Set the language:'
complete -c hp-plugin -l loc -l lang -l loc -l lang -d 'OPTIONS Specify the path to the plugin file:'
complete -c hp-plugin -s p -l path -l plugin -d 'Set the logging level:'
complete -c hp-plugin -o 'l<level>' -l logging -d '<level>: none, info*, error, warn, debug (*default) Run in debug mode:'
complete -c hp-plugin -s g -o ldebug -d 'This help information:'
complete -c hp-plugin -s h -l help -d 'SEE ALSO hp-setup hp-firmware AUTHOR HPLIP (HP Linux Imaging and Printing) is…'

