# hp-query
# Autogenerated from man page /usr/share/man/man1/hp-query.1.gz
complete -c hp-query -s n -l non-interactive -d 'OPTIONS Set the logging level:'
complete -c hp-query -o 'l<level>' -l logging -d '<level>: none, info*, error, warn, debug (*default) Run in debug mode:'
complete -c hp-query -s g -o ldebug -d 'This help information:'
complete -c hp-query -s h -l help -d 'Specify model by device URI:'
complete -c hp-query -o 'd<device_uri>' -l device -d 'Specify normalized model name:'
complete -c hp-query -o 'm<model_name>' -l model -d 'Specify raw model name:'
complete -c hp-query -o 'r<model_name>' -l raw -d 'Specify key to query:'
complete -c hp-query -o 'k<key>' -l key -o a/--all -d 'Query all keys:'
complete -c hp-query -s a -l all -d 'Specify the separator when multiple keys are queried:'
complete -c hp-query -o 's<sep>' -l sep -d 'Suppress trailing linefeed:'
complete -c hp-query -s x -d 'SEE ALSO hp-info AUTHOR HPLIP (HP Linux Imaging and Printing) is an HP develo…'

