# hp-setup
# Autogenerated from man page /usr/share/man/man1/hp-setup.1.gz
complete -c hp-setup -s u -l gui -d 'Run in interactive mode:'
complete -c hp-setup -s i -l interactive -d 'OPTIONS Automatic mode:'
complete -c hp-setup -s a -l auto -d 'To specify the port on a multi-port JetDirect:'
complete -c hp-setup -l port -d 'No testpage in automatic mode:'
complete -c hp-setup -s x -d 'To specify a CUPS printer queue name:'
complete -c hp-setup -o 'p<printer>' -l printer -d 'To specify a CUPS fax queue name:'
complete -c hp-setup -o 'f<fax>' -l fax -d 'Type of queue(s) to install:'
complete -c hp-setup -o 't<typelist>' -l type -d 'To specify the device URI to install:'
complete -c hp-setup -o 'd<device>' -l device -l qt4 -d 'Remove printers or faxes instead of setting-up:'
complete -c hp-setup -s r -l rm -l remove -d 'Set the language:'
complete -c hp-setup -l loc -l lang -l loc -l lang -d 'Set the logging level:'
complete -c hp-setup -o 'l<level>' -l logging -d '<level>: none, info*, error, warn, debug (*default) Run in debug mode:'
complete -c hp-setup -s g -o ldebug -d 'This help information:'
complete -c hp-setup -s h -l help -d 'SERIAL NO'

