# hp-timedate
# Autogenerated from man page /usr/share/man/man1/hp-timedate.1.gz
complete -c hp-timedate -o 'd<device-uri>' -l device -d 'To specify a CUPS printer:'
complete -c hp-timedate -o 'p<printer>' -l printer -d 'MODE Run in interactive mode:'
complete -c hp-timedate -s i -l interactive -d 'OPTIONS Set the logging level:'
complete -c hp-timedate -o 'l<level>' -l logging -d '<level>: none, info*, error, warn, debug (*default) Run in debug mode:'
complete -c hp-timedate -s g -o ldebug -d 'This help information:'
complete -c hp-timedate -s h -l help -d 'AUTHOR HPLIP (HP Linux Imaging and Printing) is an HP developed solution for …'

