# ibus
# Autogenerated from man page /usr/share/man/man1/ibus.1.gz
complete -c ibus -l system -d 'is not given.  Show the content of the system registry cache if'
complete -c ibus -l file -d 'is given'
complete -c ibus -l font -d 'option.  Can choose a language of emoji annotations with'
complete -c ibus -l lang -d 'option.  If LANG="en", IBus Emojier loads /usr/share/ibus/dicts/emoji-en'
complete -c ibus -l partial-match -d 'option enables to match annotations with a partial string'

