# icat
# Autogenerated from man page /usr/share/man/man1/icat.1.gz
complete -c icat -s f -d 'Specifies the file system type'
complete -c icat -s h -d 'Skip over holes in sparse files, so that absolute address information is lost'
complete -c icat -s r -d 'Use file recovery techniques if the file is deleted'
complete -c icat -s s -d 'Include the slack space in the output'
complete -c icat -s i -d 'Identify the type of image file, such as raw'
complete -c icat -s o -d 'The sector offset where the file system starts in the image'
complete -c icat -s b -d 'The size, in bytes, of the underlying device sectors'
complete -c icat -s v -d 'Enable verbose mode, output to stderr'
complete -c icat -s V -d 'Display version image [images] The disk or partition image to read, whose for…'

