# iceauth
# Autogenerated from man page /usr/share/man/man1/iceauth.1.gz
complete -c iceauth -s f -d '             the file currently in use by the session'
complete -c iceauth -s v
complete -c iceauth -s q
complete -c iceauth -s i
complete -c iceauth -s b
complete -c iceauth -s u
complete -c iceauth -s V

