# ico
# Autogenerated from man page /usr/share/man/man1/ico.1.gz
complete -c ico -s r -d 'Display on the root window instead of creating a new window'
complete -c ico -s d -d 'Specify a bit pattern for drawing dashed lines for wire frames'
complete -c ico -s i -d 'Use inverted colors for wire frames'
complete -c ico -o dbl -d 'Use double buffering on the display'
complete -c ico -o faces -d 'Draw filled faces instead of wire frames'
complete -c ico -o noedges -d 'Don\'t draw the wire frames.  Typically used only when -faces is used'
complete -c ico -o sleep -d 'Sleep n seconds between each move of the object'
complete -c ico -o obj -d 'Specify what object to draw'
complete -c ico -o objhelp -d 'Print out a list of the available objects, along with information about each …'
complete -c ico -o colors -d 'Specify what colors should be used to draw the filled faces of the object'
complete -c ico -o version -d 'Print program version information and exit.  PROGRAM TERMINATION'

