# iecset
# Autogenerated from man page /usr/share/man/man1/iecset.1.gz
complete -c iecset -s D -d 'Specifies the device name of the control to open'
complete -c iecset -s c -d 'Specifies the card index to open.   Equivalent with -Dhw:x'
complete -c iecset -s n -d 'Specifies the IEC958 control element index, in case you have multiple IEC958 …'
complete -c iecset -s x -d 'Dumps the status in the form of AESx bytes'
complete -c iecset -s i -d 'Reads the command sequences from stdin.  Each line has single command'

