# im-config
# Autogenerated from man page /usr/share/man/man8/im-config.8.gz
complete -c im-config -s a -d 'List all; force to list all possible input method frameworks in menu or STDOU…'
complete -c im-config -s c -d 'Use console dialogue'
complete -c im-config -s x -d 'Use X dialogue with zenity'
complete -c im-config -s s -d 'No action; perform a simulation of events that would occur but do not actuall…'
complete -c im-config -s l -d 'List all available input method frameworks to STDOUT'
complete -c im-config -s m -d 'List configuration values to STDOUT: . RS 12 . ie n \\{\\ \\h\'-04\'\\(bu\\h\'+03\'\\c '
complete -c im-config -s n -d '<input method name>  Set input method framework to <input method name>'
complete -c im-config -s o -d '<input method name>'

