# img_cat
# Autogenerated from man page /usr/share/man/man1/img_cat.1.gz
complete -c img_cat -s i -d 'Identify the type of image file, such as raw or aff'
complete -c img_cat -s b -d 'The size, in bytes, of the underlying device sectors'
complete -c img_cat -s s -d 'The sector number to start at'
complete -c img_cat -s e -d 'The sector number to stop at'
complete -c img_cat -s v -d 'Verbose output of debugging statements to stderr'
complete -c img_cat -s V -d 'Display version image [images] The disk or partition image to read, whose for…'

