# info
# Autogenerated from man page /usr/share/man/man1/info.1.gz
complete -c info -s a -l all -d 'use all matching manuals'
complete -c info -s k -l apropos -d 'look up STRING in all indices of all manuals'
complete -c info -s d -l directory -d 'add DIR to INFOPATH'
complete -c info -s f -l file -d 'specify Info manual to visit'
complete -c info -s h -l help -d 'display this help and exit'
complete -c info -l index-search -d 'go to node pointed by index entry STRING'
complete -c info -s n -l node -d 'specify nodes in first visited Info file'
complete -c info -s o -l output -d 'output selected nodes to FILE'
complete -c info -s O -l show-options -l usage -d 'go to command-line options node'
complete -c info -l subnodes -d 'recursively output menu items'
complete -c info -s v -l variable -d 'assign VALUE to Info variable VAR'
complete -c info -l version -d 'display version information and exit'
complete -c info -s w -l where -l location -d 'print physical location of Info file'

