# infotocap
# Autogenerated from man page /usr/share/man/man1/infotocap.1.gz
complete -c infotocap -s v -d 'print out tracing information on standard error as the program runs'
complete -c infotocap -s V -d 'print out the version of the program in use on standard error and exit'
complete -c infotocap -s 1 -d 'cause the fields to print out one to a line'
complete -c infotocap -s w -d 'change the output to width characters.  FILES'

