# ionice
# Autogenerated from man page /usr/share/man/man1/ionice.1.gz
complete -c ionice -s c -l class
complete -c ionice -s n -l classdata
complete -c ionice -s p -l pid
complete -c ionice -s P -l pgid
complete -c ionice -s t -l ignore
complete -c ionice -s h -l help
complete -c ionice -s u -l uid
complete -c ionice -s V -l version

