# ip6tables-apply
# Autogenerated from man page /usr/share/man/man8/ip6tables-apply.8.gz
complete -c ip6tables-apply -s t -l timeout -d 'Sets the timeout in seconds after which the script will roll back to the prev…'
complete -c ip6tables-apply -s w -l write -d 'Specify the savefile where successfully applied rules will be written to (def…'
complete -c ip6tables-apply -s c -l command -d 'Run command runcmd to configure iptables instead of applying a rulesfile (def…'
complete -c ip6tables-apply -s h -l help -d 'Display usage information'
complete -c ip6tables-apply -s V -l version -d 'Display version information.  SEE ALSO'

