# ip6tables-restore-translate
# Autogenerated from man page /usr/share/man/man8/ip6tables-restore-translate.8.gz
complete -c ip6tables-restore-translate -s A -s p -s m -l dport -s m -l ctstate -s j -d 'COMMIT # Completed on Sat Dec 24 14:26:40 2016'

