# ipcmk
# Autogenerated from man page /usr/share/man/man1/ipcmk.1.gz
complete -c ipcmk -s M -l shmem
complete -c ipcmk -s Q -l queue
complete -c ipcmk -s S -l semaphore
complete -c ipcmk -s p -l mode
complete -c ipcmk -s V -l version
complete -c ipcmk -s h -l help

