# ipcrm
# Autogenerated from man page /usr/share/man/man1/ipcrm.1.gz
complete -c ipcrm -s a -l all
complete -c ipcrm -s M -l shmem-key
complete -c ipcrm -s m -l shmem-id
complete -c ipcrm -s Q -l queue-key
complete -c ipcrm -s q -l queue-id
complete -c ipcrm -s S -l semaphore-key
complete -c ipcrm -s s -l semaphore-id
complete -c ipcrm -s V -l version
complete -c ipcrm -s h -l help

