# ipcs
# Autogenerated from man page /usr/share/man/man1/ipcs.1.gz
complete -c ipcs -s i -l id
complete -c ipcs -s h -l help
complete -c ipcs -s V -l version
complete -c ipcs -s m -l shmems
complete -c ipcs -s q -l queues
complete -c ipcs -s s -l semaphores
complete -c ipcs -s a -l all
complete -c ipcs -s c -l creator
complete -c ipcs -s l -l limits
complete -c ipcs -s p -l pid
complete -c ipcs -s t -l time
complete -c ipcs -s u -l summary
complete -c ipcs -s b -l bytes
complete -c ipcs -l human

