# iptables-restore
# Autogenerated from man page /usr/share/man/man8/iptables-restore.8.gz
complete -c iptables-restore -s c -l counters -d 'restore the values of all packet and byte counters'
complete -c iptables-restore -s h -l help -d 'Print a short option summary'
complete -c iptables-restore -s n -l noflush -d 'don\'t flush the previous contents of the table'
complete -c iptables-restore -s t -l test -d 'Only parse and construct the ruleset, but do not commit it'
complete -c iptables-restore -s v -l verbose -d 'Print additional debug info during ruleset processing'
complete -c iptables-restore -s V -l version -d 'Print the program version number'
complete -c iptables-restore -s w -l wait -d 'Wait for the xtables lock'
complete -c iptables-restore -s W -l wait-interval -d 'Interval to wait per each iteration'
complete -c iptables-restore -s M -l modprobe -d 'Specify the path to the modprobe program'
complete -c iptables-restore -s T -l table -d 'Restore only the named table even if the input stream contains other ones'

