# isadump
# Autogenerated from man page /usr/share/man/man8/isadump.8.gz
complete -c isadump -s f -d 'Enable flat address space mode'
complete -c isadump -s y -d 'Disable interactive mode'
complete -c isadump -s k -d 'Specify a comma-separated list of bytes to send as the key sequence to enter …'
complete -c isadump -s W -d 'Perform 16-bit reads'
complete -c isadump -s L -d 'Perform 32-bit reads'

