# ischroot
# Autogenerated from man page /usr/share/man/man1/ischroot.1.gz
complete -c ischroot -s f -l default-false -d 'Exit with status 1 if the detection is not possible'
complete -c ischroot -s t -l default-true -d 'Exit with status 0 if the detection is not possible'
complete -c ischroot -l help -d 'Print a usage message on standard output and exit successfully'
complete -c ischroot -l version -d 'Print version information on standard output and exit successfully'

