# isoinfo
# Autogenerated from man page /usr/share/man/man1/isoinfo.1.gz
complete -c isoinfo -s h -d 'print a summary of all options'
complete -c isoinfo -s d -d 'Print information from the primary volume descriptor (PVD) of the iso9660 ima…'
complete -c isoinfo -s f -d 'generate output as if a \'find '
complete -c isoinfo -s i -d 'Specifies the path of the iso9660 image that we wish to examine'
complete -c isoinfo -s l -d 'generate output as if a \'ls -lR\' command had been run on the iso9660 image'
complete -c isoinfo -s N -d 'Quick hack to help examine single session disc files that are to be written t…'
complete -c isoinfo -s p -d 'Print path table information'
complete -c isoinfo -s R -d 'Extract information from Rock Ridge extensions (if present) for permissions, …'
complete -c isoinfo -s J -d 'Extract information from Joliet extensions (if present) for file names'
complete -c isoinfo -s j -d 'Convert Joliet file names (if present) to the supplied charset'
complete -c isoinfo -s T -d 'Quick hack to help examine multi-session images that have already been burned…'
complete -c isoinfo -o help -o version -d 'i =name, dev =name.  The isoinfo program has additional command line options'
complete -c isoinfo -s x -d 'Extract specified file to stdout'

