# istat
# Autogenerated from man page /usr/share/man/man1/istat.1.gz
complete -c istat -s B -d 'Display the addresses of num disk units'
complete -c istat -s f -d 'Specify the file system type'
complete -c istat -s s -d 'The time skew of the original system in seconds'
complete -c istat -s i -d 'Identify the type of image file, such as raw'
complete -c istat -s o -d 'The sector offset where the file system starts in the image'
complete -c istat -s b -d 'The size, in bytes, of the underlying device sectors'
complete -c istat -s v -d 'Verbose output of debugging statements to stderr'
complete -c istat -s V -d 'Display version'
complete -c istat -s z -d 'An ASCII string of the original system\'s time zone'

