# jcat
# Autogenerated from man page /usr/share/man/man1/jcat.1.gz
complete -c jcat -s f -d 'Specify the file system type'
complete -c jcat -s i -d 'Identify the type of image file, such as raw'
complete -c jcat -s o -d 'The sector offset where the file system starts in the image'
complete -c jcat -s b -d 'The size, in bytes, of the underlying device sectors'
complete -c jcat -s V -d 'Display version'
complete -c jcat -s v -d 'verbose output image [images] The disk or partition image to read, whose form…'

