# jpgicc
# Autogenerated from man page /usr/share/man/man1/jpgicc.1.gz
complete -c jpgicc -s b -d 'Black point compensation'
complete -c jpgicc -s c -d 'Precalculates transform (0=Off, 1=Normal, 2=Hi-res, 3=LoRes) [defaults to 1]'
complete -c jpgicc -s d -d 'Observer adaptation state (abs. col.  only), (0. 1'
complete -c jpgicc -s e -d 'Embed destination profile'
complete -c jpgicc -s g -d 'Marks out-of-gamut colors on softproof'
complete -c jpgicc -s h -d 'Show summary of options and examples (0=help, 1=Examples, 2=Built-in profiles…'
complete -c jpgicc -s i -d 'Input profile (defaults to sRGB)'
complete -c jpgicc -s l -d 'TODO: explain this option'
complete -c jpgicc -s m -d 'SoftProof intent (0,1,2,3) [defaults to 0]'
complete -c jpgicc -s n -d 'Ignore embedded profile'
complete -c jpgicc -s o -d 'Output profile (defaults to sRGB)'
complete -c jpgicc -s p -d 'Soft proof profile'
complete -c jpgicc -s q -d 'Output JPEG quality, (0. 100) [defaults to 75]'
complete -c jpgicc -s s -d 'Save embedded profile as newprofile'
complete -c jpgicc -o tNUM -d 'Rendering intent . nf '
complete -c jpgicc -s v -d Verbose
complete -c jpgicc -s t -d 'Rendering intent 0=Perceptual [default] 1=Relative colorimetric 2=Saturation …'

