# kbdrate
# Autogenerated from man page /usr/share/man/man8/kbdrate.8.gz
complete -c kbdrate -s r -l rate -d 'Change the keyboard repeat rate to  NUMBER cps'
complete -c kbdrate -s d -l delay -d 'Change the delay to  NUMBER milliseconds'
complete -c kbdrate -s s -l silent -d 'Silent.  No messages are printed'
complete -c kbdrate -s h -l help -d 'Display a help text'
complete -c kbdrate -s V -l version -d 'Display a version number and exit'

