# kbxutil
# Autogenerated from man page /usr/share/man/man1/kbxutil.1.gz
complete -c kbxutil -l from -d 'first record to export'
complete -c kbxutil -l to -d 'last record to export'
complete -c kbxutil -s v -l verbose -d verbose
complete -c kbxutil -s q -l quiet -d 'be somewhat more quiet'
complete -c kbxutil -s n -l dry-run -d 'do not make any changes'
complete -c kbxutil -l debug -d 'set debugging flags'
complete -c kbxutil -l stats -d 'show key statistics'
complete -c kbxutil -l import-openpgp -d 'import OpenPGP keyblocks'
complete -c kbxutil -l find-dups -d 'find duplicates'
complete -c kbxutil -l cut -d 'export records'
complete -c kbxutil -l debug-all -d 'enable full debugging'

