# kerneloops
# Autogenerated from man page /usr/share/man/man8/kerneloops.8.gz
complete -c kerneloops -l file -d 'Parse the file denoted with filename as if it were /var/log/messages'
complete -c kerneloops -l debug -d 'Enable debug mode'
complete -c kerneloops -l nodaemon -d 'Do not daemonize FILES /etc/kerneloops'

