# keyring
# Autogenerated from man page /usr/share/man/man1/keyring.1.gz
complete -c keyring -s h -l help -d 'Show the help message and exit'
complete -c keyring -s p -l keyring-path -d 'Specify path to the keyring backend to use'
complete -c keyring -s b -l keyring-backend -d 'Specify name of the keyring backend to use'
complete -c keyring -l list-backends -d 'List the available keyring backends and exit'
complete -c keyring -l disable -d 'Create a configuration file disabling keyring and exit'

