# kill
# Autogenerated from man page /usr/share/man/man1/kill.1.gz
complete -c kill -o '<signal>' -d 'TQ  -s <signal> . TQ  --signal <signal> Specify the  signal to be sent'
complete -c kill -s q -l queue -d 'Use  sigqueue(3) rather than  kill(2) and the value argument is used to speci…'
complete -c kill -s l -l list -d 'List signal names'
complete -c kill -s L -l table -d 'List signal names in a nice table'
complete -c kill -s 9 -o SIGKILL -d or
complete -c kill -o KILL -d 'Negative PID values may be used to choose whole process groups; see the PGID …'
complete -c kill -s 1 -d 'is special; it indicates all processes except the kill process itself and init'
complete -c kill -s s
complete -c kill -l signal -d 'Specify the signal to be sent'

