# killall
# Autogenerated from man page /usr/share/man/man1/killall.1.gz
complete -c killall -s e -l exact -d 'Require an exact match for very long names'
complete -c killall -s I -l ignore-case -d 'Do case insensitive process name match'
complete -c killall -s g -l process-group -d 'Kill the process group to which the process belongs'
complete -c killall -s i -l interactive -d 'Interactively ask for confirmation before killing'
complete -c killall -s l -l list -d 'List all known signal names'
complete -c killall -s n -l ns -d 'Match against the PID namespace of the given PID'
complete -c killall -s o -l older-than -d 'Match only processes that are older (started before) the time specified'
complete -c killall -s q -l quiet -d 'Do not complain if no processes were killed'
complete -c killall -s r -l regexp -d 'Interpret process name pattern as a POSIX extended regular expression, per  r…'
complete -c killall -s s -l signal -o SIGNAL -d 'Send this signal instead of SIGTERM'
complete -c killall -s u -l user -d 'Kill only processes the specified user owns.   Command names are optional'
complete -c killall -s v -l verbose -d 'Report if the signal was successfully sent'
complete -c killall -s V -l version -d 'Display version information'
complete -c killall -s w -l wait -d 'Wait for all killed processes to die'
complete -c killall -s y -l younger-than -d 'Match only processes that are younger (started after) the time specified'
complete -c killall -o HUP -d or
complete -c killall -o SIGHUP -d 'or by number (e. g'
complete -c killall -s 1 -d 'or by option'
complete -c killall -s Z -l context -d 'Specify security context: kill only processes having security context that ma…'

