# l2ping
# Autogenerated from man page /usr/share/man/man1/l2ping.1.gz
complete -c l2ping -s i -d 'The command is applied to device hciX, which must be the name of an installed…'
complete -c l2ping -s s -d 'The size of the data packets to be sent'
complete -c l2ping -s c -d 'Send count number of packets then exit'
complete -c l2ping -s t -d 'Wait timeout seconds for the response'
complete -c l2ping -s d -d 'Wait delay seconds between pings'
complete -c l2ping -s f -d 'Kind of flood ping'
complete -c l2ping -s r -d 'Reverse ping (gnip?).  Send echo response instead of echo request'
complete -c l2ping -s v -d 'Verify response payload is identical to request payload'

