# lastb
# Autogenerated from man page /usr/share/man/man1/lastb.1.gz
complete -c lastb -s a -l hostlast
complete -c lastb -s d -l dns
complete -c lastb -s f -l file
complete -c lastb -s F -l fulltimes
complete -c lastb -s i -l ip
complete -c lastb -o 'number;' -s n -l limit
complete -c lastb -s p -l present
complete -c lastb -s R -l nohostname
complete -c lastb -s s -l since
complete -c lastb -s t -l until
complete -c lastb -l time-format
complete -c lastb -s w -l fullnames
complete -c lastb -s x -l system
complete -c lastb -o 5days -d 'T}:T{ T} FILES'

