# lavadecode
# Autogenerated from man page /usr/share/man/man1/lavadecode.1.gz
complete -c lavadecode -s d -d 'Basename of . pbm file for saving decompressed planes'
complete -c lavadecode -s h -d 'Print hex file offsets'
complete -c lavadecode -s o -d 'Print file offsets'
complete -c lavadecode -s D -d 'Set Debug level [0]'

