# ld-linux
# Autogenerated from man page /usr/share/man/man8/ld-linux.8.gz
complete -c ld-linux -l audit -d 'Use objects named in  list as auditors'
complete -c ld-linux -l inhibit-cache -d 'Do not use R /etc/ld. so. cache '
complete -c ld-linux -l library-path -d 'Use  path instead of  LD_LIBRARY_PATH environment variable setting (see below)'
complete -c ld-linux -l inhibit-rpath -d 'Ignore RPATH and RUNPATH information in object names in R list '
complete -c ld-linux -l list -d 'List all dependencies and how they are resolved'
complete -c ld-linux -l preload -d 'Preload the objects specified in R list '
complete -c ld-linux -o static -d 'option was given to ld (1) during compilation'
complete -c ld-linux -s z -d 'linker option, shared objects in the default paths are skipped'
complete -c ld-linux -l verify -d 'Verify that program is dynamically linked and this dynamic linker can handle …'

