# ldconfig
# Autogenerated from man page /usr/share/man/man8/ldconfig.8.gz
complete -c ldconfig -s c -l format -d '(Since glibc 2. 2) Cache format to use: R old , R new , or R compat '
complete -c ldconfig -s C -d 'Use  cache instead of R /etc/ld. so. cache '
complete -c ldconfig -s f -d 'Use  conf instead of R /etc/ld. so. conf . \\" FIXME glibc 2. 7 added -i'
complete -c ldconfig -s i -l ignore-aux-cache -d '(Since glibc 2. 7) '
complete -c ldconfig -s l -d '(Since glibc 2. 2) Library mode.  Manually link individual libraries'
complete -c ldconfig -s n -d 'Process only the directories specified on the command line'
complete -c ldconfig -s N -d 'Don\'t rebuild the cache'
complete -c ldconfig -s p -l print-cache -d 'Print the lists of directories and candidate libraries stored in the current …'
complete -c ldconfig -s r -d 'Change to and use  root as the root directory'
complete -c ldconfig -s v -l verbose -d 'Verbose mode'
complete -c ldconfig -s V -l version -d 'Print program version'
complete -c ldconfig -s X -d 'is also specified, links are still updated'

