# ldd
# Autogenerated from man page /usr/share/man/man1/ldd.1.gz
complete -c ldd -l version -d 'Print the version number of  ldd '
complete -c ldd -s v -l verbose -d 'Print all information, including, for example, symbol versioning information'
complete -c ldd -s u -l unused -d 'Print unused direct dependencies.  (Since glibc 2. 3. 4. )'
complete -c ldd -s d -l data-relocs -d 'Perform relocations and report any missing objects (ELF only)'
complete -c ldd -s r -l function-relocs -d 'Perform relocations for both data objects and functions, and report any missi…'
complete -c ldd -l help -d 'Usage information'

