# lexgrog
# Autogenerated from man page /usr/share/man/man1/lexgrog.1.gz
complete -c lexgrog -s d -l debug -d 'Print debugging information'
complete -c lexgrog -s m -l man -d 'Parse input as man page source files'
complete -c lexgrog -s c -l cat -d 'Parse input as preformatted man pages (\\(lqcat pages\\(rq)'
complete -c lexgrog -s w -l whatis -d 'Display the name and description from the man page\'s header, as used by  apro…'
complete -c lexgrog -s f -l filters -d 'Display the list of filters needed to preprocess the man page before formatti…'
complete -c lexgrog -s E -l encoding -d 'Override the guessed character set for the page to R encoding '
complete -c lexgrog -s '?' -l help -d 'Print a help message and exit'
complete -c lexgrog -l usage -d 'Print a short usage message and exit'
complete -c lexgrog -s V -l version -d 'Display version information.  EXIT STATUS'

