# libnss_systemd
# Autogenerated from man page /usr/share/man/man8/libnss_systemd.so.2.8.gz
complete -c libnss_systemd -o rw-r--r--
complete -c libnss_systemd -o rw------- -d 'lrwxrwxrwx.  1 root root   19 May 10 4711. user -> foobar. user lrwxrwxrwx'

