# lightdm
# Autogenerated from man page /usr/share/man/man1/lightdm.1.gz
complete -c lightdm -s h -l help -d 'Show help options'
complete -c lightdm -s c -l config -d 'Use configuration file'
complete -c lightdm -s d -l debug -d 'Print debugging messages'
complete -c lightdm -l test-mode -d 'Run as unprivileged user, skipping things that require root access'
complete -c lightdm -l pid-file -d 'File to write PID into'
complete -c lightdm -l xsessions-dir -d 'Directory to load X sessions from'
complete -c lightdm -l xgreeters-dir -d 'Directory to load X greeters from'
complete -c lightdm -l log-dir -d 'Directory to write logs to'
complete -c lightdm -l run-dir -d 'Directory to store running state'
complete -c lightdm -l cache-dir -d 'Directory to cached information'
complete -c lightdm -s v -l version -d 'Show release version FILES'

