# linkicc
# Autogenerated from man page /usr/share/man/man1/linkicc.1.gz
complete -c linkicc -s 8 -d 'Creates 8-bit devicelink'
complete -c linkicc -s b -d 'Black point compensation'
complete -c linkicc -s c -d 'Precission (0=LowRes, 1=Normal, 2=Hi-res).  [defaults to 1]'
complete -c linkicc -s d -d 'Description text (quotes can be used)'
complete -c linkicc -s h -d 'Show summary of options and examples'
complete -c linkicc -s i -d 'Input profile (defaults to sRGB)'
complete -c linkicc -s k -d 'Ink-limiting in % (CMYK only)'
complete -c linkicc -s o -d 'Output devicelink profile.  [defaults to \'devicelink. icm\']'
complete -c linkicc -s t -d 'Intent (0=Perceptual, 1=Colorimetric, 2=Saturation, 3=Absolute)'
complete -c linkicc -s x -d 'Creatively, guess deviceclass of resulting profile'

