# linux-version
# Autogenerated from man page /usr/share/man/man1/linux-version.1.gz
complete -c linux-version -l paths -d 'AUTHOR linux-version and this manual page were written by Ben Hutchings as pa…'

