# linux64
# Autogenerated from man page /usr/share/man/man8/linux64.8.gz
complete -c linux64 -l list
complete -c linux64 -l 'uname-2.6'
complete -c linux64 -s v -l verbose
complete -c linux64 -s 3 -l 3gb
complete -c linux64 -l 4gb
complete -c linux64 -s B -l 32bit
complete -c linux64 -s F -l fdpic-funcptrs
complete -c linux64 -s I -l short-inode
complete -c linux64 -s L -l addr-compat-layout
complete -c linux64 -s R -l addr-no-randomize
complete -c linux64 -s S -l whole-seconds
complete -c linux64 -s T -l sticky-timeouts
complete -c linux64 -s X -l read-implies-exec
complete -c linux64 -s Z -l mmap-page-zero
complete -c linux64 -s V -l version
complete -c linux64 -s h -l help

