# listres
# Autogenerated from man page /usr/share/man/man1/listres.1.gz
complete -c listres -o all -d 'This option indicates that listres should print information for all known wid…'
complete -c listres -o nosuper -d 'This option indicates that resources that are inherited from a superclass sho…'
complete -c listres -o variable -d 'This option indicates that widgets should be identified by the names of the c…'
complete -c listres -o top -d 'This option specifies the name of the widget to be treated as the top of the …'
complete -c listres -o format -d 'This option specifies the printf-style format string to be used to print out …'

