# login
# Autogenerated from man page /usr/share/man/man1/login.1.gz
complete -c login -s f -d 'Do not perform authentication, user is preauthenticated'
complete -c login -s h -d 'Name of the remote host for this login'
complete -c login -s p -d 'Preserve environment'
complete -c login -s r -d 'Perform autologin protocol for rlogin'

