# logrotate
# Autogenerated from man page /usr/share/man/man8/logrotate.8.gz
complete -c logrotate -s f -l force -d 'Tells logrotate to force the rotation, even if it doesn\'t think this is neces…'
complete -c logrotate -s d -l debug -d 'Turn on debug mode, which means that no changes are made to the logs and the …'
complete -c logrotate -s s -l state -d 'Tells logrotate to use an alternate state file'
complete -c logrotate -l skip-state-lock -d 'Do not lock the state file, for example if locking is unsupported or prohibit…'
complete -c logrotate -s v -l verbose -d 'Turns on verbose mode, for example to display messages during rotation'
complete -c logrotate -s l -l log -d 'Tells logrotate to log verbose output into the log_file'
complete -c logrotate -s m -l mail -d 'Tells logrotate which command to use when mailing logs'
complete -c logrotate -l usage -d 'Prints a short usage message'
complete -c logrotate -s '?' -l help -d 'Prints help message'
complete -c logrotate -l version -d 'Display version information.  CONFIGURATION FILE'

