# look
# Autogenerated from man page /usr/share/man/man1/look.1.gz
complete -c look -s a -l alternative
complete -c look -s d -l alphanum
complete -c look -s f -l ignore-case
complete -c look -s t -l terminate
complete -c look -s V -l version
complete -c look -s h -l help

