# losetup
# Autogenerated from man page /usr/share/man/man8/losetup.8.gz
complete -c losetup -s a -l all
complete -c losetup -s d -l detach
complete -c losetup -s D -l detach-all
complete -c losetup -s f -l find
complete -c losetup -l show
complete -c losetup -s L -l nooverlap
complete -c losetup -s j -l associated -s o
complete -c losetup -l offset
complete -c losetup -l sizelimit
complete -c losetup -s b -l sector-size
complete -c losetup -s c -l set-capacity
complete -c losetup -s P -l partscan
complete -c losetup -s r -l read-only
complete -c losetup -l direct-io
complete -c losetup -s v -l verbose
complete -c losetup -s l -l list
complete -c losetup -s O -l output
complete -c losetup -l output-all
complete -c losetup -s n -l noheadings
complete -c losetup -l raw
complete -c losetup -s J -l json
complete -c losetup -s V -l version
complete -c losetup -s h -l help

