# lpadmin
# Autogenerated from man page /usr/share/man/man8/lpadmin.8.gz
complete -c lpadmin -s c -d 'Adds the named printer to class'
complete -c lpadmin -s m -d 'Sets a standard PPD file for the printer from the model directory or using on…'
complete -c lpadmin -s o -d 'Specifies whether IPP supply level values should be reported'
complete -c lpadmin -s R -d 'Deletes the named option from printer'
complete -c lpadmin -s r -d 'Removes the named printer from class'
complete -c lpadmin -s u -d 'Sets user-level access control on a destination'
complete -c lpadmin -s v -d 'Sets the device-uri attribute of the printer queue'
complete -c lpadmin -s D -d 'Provides a textual description of the destination'
complete -c lpadmin -s E -d 'When specified before the -d, -p, or -x options, forces the use of TLS encryp…'
complete -c lpadmin -s L -d 'Provides a textual location of the destination'
complete -c lpadmin -s i -d 'This option historically has been used to provide either a System V interface…'
complete -c lpadmin -s P -d 'Specifies a PostScript Printer Description (PPD) file to use with the printer'

