# lpoptions
# Autogenerated from man page /usr/share/man/man1/lpoptions.1.gz
complete -c lpoptions -s E -d 'Enables encryption when communicating with the CUPS server'
complete -c lpoptions -s d -d 'Sets the user default printer to destination'
complete -c lpoptions -s h -d 'Uses an alternate server'
complete -c lpoptions -s l -d 'Lists the printer specific options and their current settings'
complete -c lpoptions -s o -d 'Specifies a new option for the named destination'
complete -c lpoptions -s p -d 'Sets the destination and instance, if specified, for any options that follow'
complete -c lpoptions -s r -d 'Removes the specified option from the named destination'
complete -c lpoptions -s x -d 'Removes the options for the named destination and instance, if specified'

