# lsattr
# Autogenerated from man page /usr/share/man/man1/lsattr.1.gz
complete -c lsattr -s R -d 'Recursively list attributes of directories and their contents'
complete -c lsattr -s V -d 'Display the program version'
complete -c lsattr -s a -d 'List all files in directories, including files that start with `. \''
complete -c lsattr -s d -d 'List directories like other files, rather than listing their contents'
complete -c lsattr -s l -d 'Print the options using long names instead of single character abbreviations'
complete -c lsattr -s p -d 'List the file\'s project number'
complete -c lsattr -s v -d 'List the file\'s version/generation number'

