# lsblk
# Autogenerated from man page /usr/share/man/man8/lsblk.8.gz
complete -c lsblk -s a -l all
complete -c lsblk -s b -l bytes
complete -c lsblk -s D -l discard
complete -c lsblk -s d -l nodeps
complete -c lsblk -s E -l dedup
complete -c lsblk -s e -l exclude
complete -c lsblk -s f -l fs
complete -c lsblk -s h -l help
complete -c lsblk -s I -l include
complete -c lsblk -s i -l ascii
complete -c lsblk -s J -l json
complete -c lsblk -s l -l list
complete -c lsblk -s M -l merge
complete -c lsblk -s m -l perms
complete -c lsblk -s n -l noheadings
complete -c lsblk -s o -l output
complete -c lsblk -s O -l output-all
complete -c lsblk -s P -l pairs
complete -c lsblk -s p -l paths
complete -c lsblk -s r -l raw
complete -c lsblk -s S -l scsi
complete -c lsblk -s s -l inverse
complete -c lsblk -s T -l tree
complete -c lsblk -s t -l topology
complete -c lsblk -s V -l version
complete -c lsblk -s w -l width
complete -c lsblk -s x -l sort
complete -c lsblk -s z -l zoned
complete -c lsblk -l sysroot

