# lscpu
# Autogenerated from man page /usr/share/man/man1/lscpu.1.gz
complete -c lscpu -s a -l all
complete -c lscpu -s B -l bytes
complete -c lscpu -s b -l online
complete -c lscpu -s C -l caches
complete -c lscpu -s c -l offline
complete -c lscpu -s e -l extended
complete -c lscpu -s h -l help
complete -c lscpu -s J -l json
complete -c lscpu -s p -l parse
complete -c lscpu -s s -l sysroot
complete -c lscpu -s x -l hex
complete -c lscpu -s y -l physical
complete -c lscpu -s V -l version
complete -c lscpu -l output-all

