# lshw
# Autogenerated from man page /usr/share/man/man1/lshw.1.gz
complete -c lshw -o version -d 'Displays the version of lshw and exits'
complete -c lshw -o help -d 'Displays the available command line options and quits'
complete -c lshw -s X -d 'Launch the X11 GUI (if available)'
complete -c lshw -o html -d 'Outputs the device tree as an HTML page'
complete -c lshw -o xml -d 'Outputs the device tree as an XML tree'
complete -c lshw -o json -d 'Outputs the device tree as a JSON object (JavaScript Object Notation)'
complete -c lshw -o short -d 'Outputs the device tree showing hardware paths, very much like the output of …'
complete -c lshw -o businfo -d 'Outputs the device list showing bus information, detailing SCSI, USB, IDE and…'
complete -c lshw -o dump -d 'Display output and dump collected information into a file (SQLite database)'
complete -c lshw -o class -d 'Only show the given class of hardware'
complete -c lshw -s C -d 'Alias for -class class'
complete -c lshw -o enable
complete -c lshw -o disable -d 'Enables or disables a test'
complete -c lshw -o quiet -d 'Don\'t display status'
complete -c lshw -o sanitize -d 'Remove potentially sensitive information from output (IP addresses, serial nu…'
complete -c lshw -o numeric -d 'Also display numeric IDs (for PCI and USB devices)'
complete -c lshw -o notime -d 'Exclude volatile attributes (timestamps) from output'

