# lslogins
# Autogenerated from man page /usr/share/man/man1/lslogins.1.gz
complete -c lslogins -s a -l acc-expiration
complete -c lslogins -l btmp-file
complete -c lslogins -s c -l colon-separate
complete -c lslogins -s e -l export
complete -c lslogins -s f -l failed
complete -c lslogins -s G -l supp-groups
complete -c lslogins -s g -l groups
complete -c lslogins -s h -l help
complete -c lslogins -s L -l last
complete -c lslogins -s l -l logins
complete -c lslogins -s n -l newline
complete -c lslogins -l noheadings
complete -c lslogins -l notruncate
complete -c lslogins -s o -l output
complete -c lslogins -l output-all
complete -c lslogins -s p -l pwd
complete -c lslogins -s r -l raw
complete -c lslogins -s s -l system-accs
complete -c lslogins -l time-format
complete -c lslogins -s u -l user-accs
complete -c lslogins -s V -l version
complete -c lslogins -l wtmp-file
complete -c lslogins -l lastlog
complete -c lslogins -s Z -l context
complete -c lslogins -s z -l print0

