# lslocks
# Autogenerated from man page /usr/share/man/man8/lslocks.8.gz
complete -c lslocks -s b -l bytes
complete -c lslocks -s i -l noinaccessible
complete -c lslocks -s J -l json
complete -c lslocks -s n -l noheadings
complete -c lslocks -s o -l output
complete -c lslocks -l output-all
complete -c lslocks -s p -l pid
complete -c lslocks -s r -l raw
complete -c lslocks -s u -l notruncate
complete -c lslocks -s V -l version
complete -c lslocks -s h -l help

