# lsmem
# Autogenerated from man page /usr/share/man/man1/lsmem.1.gz
complete -c lsmem -s a -l all
complete -c lsmem -s b -l bytes
complete -c lsmem -s h -l help
complete -c lsmem -s J -l json
complete -c lsmem -s n -l noheadings
complete -c lsmem -s o -l output
complete -c lsmem -l output-all
complete -c lsmem -s P -l pairs
complete -c lsmem -s r -l raw
complete -c lsmem -s S -l split
complete -c lsmem -s s -l sysroot
complete -c lsmem -s V -l version
complete -c lsmem -l summary

