# lsmtd
# Autogenerated from man page /usr/share/man/man8/lsmtd.8.gz
complete -c lsmtd -s b -l bytes -d 'Print columns with size quantities (e. g'
complete -c lsmtd -s h -l help -d 'Display a help text and exit'
complete -c lsmtd -s i -l ascii -d 'Only use ascii characters for pretty printing'
complete -c lsmtd -s J -l json -d 'Use JSON output format'
complete -c lsmtd -s l -l list -d 'Use a pretty-printed list output format (default)'
complete -c lsmtd -s m -l no-ubi -d 'Do not display information about UBI devices or volumes'
complete -c lsmtd -s n -l noheadings -d 'Do not print column headings when using raw or list output format'
complete -c lsmtd -s o -l output -d 'Specify which output columns to print'
complete -c lsmtd -s O -l output-all -d 'Output all available columns'
complete -c lsmtd -s P -l pairs -d 'Produce output in the form of key="value" pairs'
complete -c lsmtd -s r -l raw -d 'Produce output in raw format'
complete -c lsmtd -s u -l si-units -d 'Display human readable sizes as powers of ten rather than powers of two'
complete -c lsmtd -s V -l version -d 'Print version information and exit'
complete -c lsmtd -s x -l sort -d 'Sort output lines by column.  NOTES If the'

