# mactime
# Autogenerated from man page /usr/share/man/man1/mactime.1.gz
complete -c mactime -s b -d 'Specify the location of a body file'
complete -c mactime -s g -d 'Specify the location of the group file'
complete -c mactime -s p -d 'Specify the location of the passwd file'
complete -c mactime -s i -d 'Specify the location of an index file to write to'
complete -c mactime -s d -d 'Display timeline and index files in comma delimited format'
complete -c mactime -s h -d 'Display header info about the session including time range, input source, and…'
complete -c mactime -s V -d 'Display version to STDOUT'
complete -c mactime -s m -d 'The month is given as a number instead of name (does not work with -y)'
complete -c mactime -s y -d 'The date is displayed in ISO8601 format'
complete -c mactime -s z -d 'The timezone from where the data was collected'

