# make-ssl-cert
# Autogenerated from man page /usr/share/man/man8/make-ssl-cert.8.gz
complete -c make-ssl-cert -l force-overwrite -d 'Always create a new certificate, even if the file already exists'
complete -c make-ssl-cert -l no-overwrite -d 'Never overwrite an existing file, even if the old certificate\'s key length is…'
complete -c make-ssl-cert -l expiration-days -d 'Make the new certificate expire in N days.  Default is 3650'

