# mapscrn
# Autogenerated from man page /usr/share/man/man8/mapscrn.8.gz
complete -c mapscrn -s o -d 'option is given, the old map is saved in map. orig'
complete -c mapscrn -s V -d 'Prints version number and exits'
complete -c mapscrn -s v -d 'Be verbose.  FILES'

