# mcookie
# Autogenerated from man page /usr/share/man/man1/mcookie.1.gz
complete -c mcookie -s f -l file
complete -c mcookie -s m -l max-size
complete -c mcookie -s v -l verbose
complete -c mcookie -s V -l version
complete -c mcookie -s h -l help

