# mdig
# Autogenerated from man page /usr/share/man/man1/mdig.1.gz
complete -c mdig -s f -d 'This option makes mdig operate in batch mode by reading a list of lookup requ…'
complete -c mdig -s h -d 'This option causes mdig to print detailed help information, with the full lis…'
complete -c mdig -s v -d 'This option causes mdig to print the version number and exit'
complete -c mdig -s 4 -d 'This option forces mdig to only use IPv4 query transport'
complete -c mdig -s 6 -d 'This option forces mdig to only use IPv6 query transport'
complete -c mdig -s b -d 'This option sets the source IP address of the query to address'
complete -c mdig -s m -d 'This option enables memory usage debugging'
complete -c mdig -s p -d 'This option is used when a non-standard port number is to be queried'
complete -c mdig -s c -d 'This option sets the query class to class'
complete -c mdig -s t -d 'This option sets the query type to type'
complete -c mdig -s x -d 'Reverse lookups - mapping addresses to names - are simplified by this option'

