# memusage
# Autogenerated from man page /usr/share/man/man1/memusage.1.gz
complete -c memusage -s n -l progname -d 'Name of the program file to profile'
complete -c memusage -s p -l png -d 'Generate PNG graphic and store it in R file '
complete -c memusage -s d -l data -d 'Generate binary data file and store it in R file '
complete -c memusage -s u -l unbuffered -d 'Do not buffer output'
complete -c memusage -s b -l buffer -d 'Collect  size entries before writing them out'
complete -c memusage -l no-timer -d 'Disable timer-based . RB ( SIGPROF ) sampling of stack pointer value'
complete -c memusage -s m -l mmap -d 'Also trace  mmap (2),  mremap (2), and  munmap (2)'
complete -c memusage -s '?' -l help -d 'Print help and exit'
complete -c memusage -l usage -d 'Print a short usage message and exit'
complete -c memusage -s V -l version -d 'Print version information and exit'
complete -c memusage -s t -l time-based -d 'Use time (rather than number of function calls) as the scale for the X axis'
complete -c memusage -s T -l total -d 'Also draw a graph of total memory use'
complete -c memusage -l title -d 'Use  name as the title of the graph'
complete -c memusage -s x -l x-size -d 'Make the graph  size pixels wide'
complete -c memusage -s y -l y-size -d 'Make the graph size pixels high'

