# mflua
# Autogenerated from man page /usr/share/man/man1/mflua.1.gz
complete -c mflua -o base
complete -c mflua -o halt-on-error
complete -c mflua -o ini
complete -c mflua -o interaction
complete -c mflua -o jobname
complete -c mflua -o kpathsea-debug
complete -c mflua -o output-directory
complete -c mflua -o progname
complete -c mflua -o recorder
complete -c mflua -o translate-file
complete -c mflua -o 8bit
complete -c mflua -o help
complete -c mflua -o version -d 'REPORTING BUGS Email bug reports to luigi. scarso@gmail. com'

