# mft
# Autogenerated from man page /usr/share/man/man1/mft.1.gz
complete -c mft -o change -d 'Apply the change file  change_file_name to R mf_file_name . PP'
complete -c mft -o metapost -d 'Assume  mf_file_name is a \\*(MP source file (this is the default if  mf_file_…'
complete -c mft -o style -d 'Use the style file style_file_name instead of plain. mft (or mplain'

