# min12xxw
# Autogenerated from man page /usr/share/man/man1/min12xxw.1.gz
complete -c min12xxw -s h -l help -d 'Gives usage information (help)'
complete -c min12xxw -s v -l version -d 'Displays the version number and exit'
complete -c min12xxw -s e -l ecomode -d 'Enables economic mode which saves toner by leaving every other scanline blank'
complete -c min12xxw -s s -l status -d 'Query the printer status, page counter and whatever information can be retrie…'
complete -c min12xxw -s d -d 'option below which sets the device file to use'
complete -c min12xxw -l device -d 'Sets the device file to use for queries.  The default is /dev/lp0'
complete -c min12xxw -s n -l nomargins -d 'Disables the enforcement of the 0. 17 inch margins on all sides of the paper'
complete -c min12xxw -s m -l model -d 'Sets which printer model to produce output for'
complete -c min12xxw -s r -l res -d 'Sets the resolution to either 300, 600 or 1200 dpi (600 dpi is the default)'
complete -c min12xxw -s t -l tray -d 'Sets the paper tray to be used'
complete -c min12xxw -s p -l papertype -d 'Sets the type of paper used'
complete -c min12xxw -s f -l paperformat -d 'This sets the paper format to be used for the print job'
complete -c min12xxw -o sPAPERSIZE -o r1200 -o sDEVICE
complete -c min12xxw -o sOutputFile -d 'This would convert a postscript file test. ps to a file test'

