# mkfontscale
# Autogenerated from man page /usr/share/man/man1/mkfontscale.1.gz
complete -c mkfontscale -s b -d 'read bitmap fonts.   By default, bitmap fonts are ignored'
complete -c mkfontscale -s s -d 'ignore scalable fonts.   By default, scalable fonts are read'
complete -c mkfontscale -s o -d 'send program output to R filename ; default is  fonts'
complete -c mkfontscale -s x -d 'exclude all files with the specified R suffix '
complete -c mkfontscale -s a -d 'add  encoding to the list of encodings searched for'
complete -c mkfontscale -s f -d 'set the fraction of characters that may be missing in large encodings to  fuz…'
complete -c mkfontscale -s l -d 'Write  fonts'
complete -c mkfontscale -s e -d 'specifies a directory with encoding files'
complete -c mkfontscale -s p -d 'Specifies a prefix that is prepended to the encoding file path names when the…'
complete -c mkfontscale -s r -d 'Keep non-absolute encoding directories in their relative form when writing th…'
complete -c mkfontscale -s n -d 'do not scan for fonts, do not write font directory files'
complete -c mkfontscale -s u -s U -d 'disable (-u) or enable (-U) indexing of ISO 10646:1 font encodings (default: …'
complete -c mkfontscale -s v -d 'print program version and exit'

