# mktexmf
# Autogenerated from man page /usr/share/man/man1/mktexmf.1.gz
complete -c mktexmf -l help -d 'Print help message and exit'
complete -c mktexmf -l version -d 'Print version information and exit'

