# mmstat
# Autogenerated from man page /usr/share/man/man1/mmstat.1.gz
complete -c mmstat -s t -d 'Specify the media management type.  Use \'-t list\' to list the supported types'
complete -c mmstat -s o -d 'Specify the offset into the image where the volume containing the partition s…'
complete -c mmstat -s b -d 'The size, in bytes, of the underlying device sectors'
complete -c mmstat -s i -d 'Identify the type of image file, such as raw'
complete -c mmstat -s v -d 'Verbose output of debugging statements to stderr'
complete -c mmstat -s V -d 'Display version image [images] The disk or partition image to read, whose for…'

