# ModemManager
# Autogenerated from man page /usr/share/man/man8/ModemManager.8.gz
complete -c ModemManager -l filter-policy -d 'Specify which ports are probed and how: \'WHITELIST-ONLY\' Only devices or port…'
complete -c ModemManager -l no-auto-scan -d 'Fully disable udev-based auto-scan looking for devices'
complete -c ModemManager -l initial-kernel-events -d 'Specify location of the file where the list of initial kernel events is avail…'
complete -c ModemManager -l debug -d 'Runs ModemManager with "DEBUG" log level and without daemonizing'
complete -c ModemManager -s V -l version -d 'Print the ModemManager software version and exit'
complete -c ModemManager -s h -l help -d 'Show application options'
complete -c ModemManager -l log-level -d 'Sets how much information ModemManager sends to the log destination (usually …'
complete -c ModemManager -l log-file -d 'Specify location of the file where ModemManager will dump its log messages, i…'
complete -c ModemManager -l log-journal -d 'Output log message to the systemd journal'
complete -c ModemManager -l log-timestamps -d 'Include absolute timestamps in the log output'
complete -c ModemManager -l log-relative-timestamps -d 'Include timestamps, relative to the start time of the daemon, in the log outp…'
complete -c ModemManager -l test-session -d 'Run the ModemManager daemon in the Session bus instead of the System bus'
complete -c ModemManager -l test-enable -d 'Enable the Test DBus interface in the daemon'
complete -c ModemManager -l test-plugin-dir -d 'Specify an alternate directory where the daemon should look for vendor plugins'

