# more
# Autogenerated from man page /usr/share/man/man1/more.1.gz
complete -c more -s d -l silent
complete -c more -s l -l logical
complete -c more -s f -l no-pause
complete -c more -s p -l print-over
complete -c more -s c -l clean-print
complete -c more -s s -l squeeze
complete -c more -s u -l plain
complete -c more -s n -l lines
complete -c more -o number
complete -c more -l help
complete -c more -s V -l version

