# mpost
# Autogenerated from man page /usr/share/man/man1/mpost.1.gz
complete -c mpost -l ini -d 'option is given, preloading does not happen'
complete -c mpost -l dvitomp -d 'option is given,  acts as DVI-to-MPX converter only'
complete -c mpost -l restricted -d 'option to make MetaPost safe to run on unknown input; the tex, makempx, and e…'
complete -c mpost -l help

