# mpris-proxy
# Autogenerated from man page /usr/share/man/man1/mpris-proxy.1.gz
complete -c mpris-proxy -s h -l help -d 'Show help options . SS "Application Options:"'
complete -c mpris-proxy -s v -l version -d 'Show version information and exit'
complete -c mpris-proxy -s e -l export -d 'Export remote players'

