# nawk
# Autogenerated from man page /usr/share/man/man1/nawk.1.gz
complete -c nawk -s f -d 'Program text is read from file instead of from the command line'
complete -c nawk -s v -d 'assigns  value to program variable R var '
complete -c nawk -s '\\' -d 'indicates the unambiguous end of options'
complete -c nawk -s W -d 'Program text is read from  file and this is the last option'
complete -c nawk -s F -d 'sets the field separator, FS, to value '

