# nemo-desktop
# Autogenerated from man page /usr/share/man/man1/nemo-desktop.1.gz
complete -c nemo-desktop -l debug -d 'Enable debugging code'
complete -c nemo-desktop -l quit -d 'Quit Nemo'
complete -c nemo-desktop -l help -d 'Show a summary of options'
complete -c nemo-desktop -l version -d 'Show Nemo\'s version'

