# NetworkManager
# Autogenerated from man page /usr/share/man/man8/NetworkManager.8.gz
complete -c NetworkManager -l version -s V -d 'Print the NetworkManager software version and exit'
complete -c NetworkManager -l help -s h -d 'Print NetworkManager\\*(Aqs available options and exit'
complete -c NetworkManager -l no-daemon -s n -d 'Do not daemonize'
complete -c NetworkManager -l debug -s d -d 'Do not daemonize, and direct log output to the controlling terminal in additi…'
complete -c NetworkManager -l pid-file -s p -d 'Specify location of a PID file'
complete -c NetworkManager -l state-file -d 'Specify file for storing state of the NetworkManager persistently'
complete -c NetworkManager -l config -d 'Specify configuration file to set up various settings for NetworkManager'
complete -c NetworkManager -l configure-and-quit -d 'Quit after all devices reach a stable state'
complete -c NetworkManager -l plugins -d 'List plugins used to manage system-wide connection settings'
complete -c NetworkManager -l log-level -d 'Sets how much information NetworkManager sends to the log destination (usuall…'
complete -c NetworkManager -l log-domains -d 'A comma-separated list specifying which operations are logged to the log dest…'
complete -c NetworkManager -l print-config -d 'Print the NetworkManager configuration to stdout and exit'

