# newusers
# Autogenerated from man page /usr/share/man/man8/newusers.8.gz
complete -c newusers -l badname -d 'Allow names that do not conform to standards'
complete -c newusers -s h -l help -d 'Display help message and exit'
complete -c newusers -s r -l system -d 'Create a system account'
complete -c newusers -s R -l rootCHROOT_DIR -d 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c newusers -l root

