# nfnl_osf
# Autogenerated from man page /usr/share/man/man8/nfnl_osf.8.gz
complete -c nfnl_osf -s f -d 'Read signatures from file R fingerprints '
complete -c nfnl_osf -s d -d 'Instead of adding the signatures from fingerprints into the kernel, remove th…'
complete -c nfnl_osf -s 1 -d 'Illegal arguments passed, fingerprints file not readable or failure in netlin…'
complete -c nfnl_osf -o ENOENT -d 'Fingerprints file not specified'
complete -c nfnl_osf -o EINVAL -d 'Netlink handle initialization failed or fingerprints file format invalid'

