# ngettext
# Autogenerated from man page /usr/share/man/man1/ngettext.1.gz
complete -c ngettext -s d -l domain -d 'retrieve translated message from TEXTDOMAIN'
complete -c ngettext -s c -l context -d 'specify context for MSGID'
complete -c ngettext -s e -d 'enable expansion of some escape sequences'
complete -c ngettext -s E -d '(ignored for compatibility)'
complete -c ngettext -s h -l help -d 'display this help and exit'
complete -c ngettext -s V -l version -d 'display version information and exit'

