# nice
# Autogenerated from man page /usr/share/man/man1/nice.1.gz
complete -c nice -s n -l adjustment -d 'add integer N to the niceness (default 10)'
complete -c nice -l help -d 'display this help and exit'
complete -c nice -o 20
complete -c nice -l version -d 'output version information and exit'

