# nl
# Autogenerated from man page /usr/share/man/man1/nl.1.gz
complete -c nl -s b -l body-numbering -d 'use STYLE for numbering body lines'
complete -c nl -s d -l section-delimiter -d 'use CC for logical page delimiters'
complete -c nl -s f -l footer-numbering -d 'use STYLE for numbering footer lines'
complete -c nl -s h -l header-numbering -d 'use STYLE for numbering header lines'
complete -c nl -s i -l line-increment -d 'line number increment at each line'
complete -c nl -s l -l join-blank-lines -d 'group of NUMBER empty lines counted as one'
complete -c nl -s n -l number-format -d 'insert line numbers according to FORMAT'
complete -c nl -s p -l no-renumber -d 'do not reset line numbers for each section'
complete -c nl -s s -l number-separator -d 'add STRING after (possible) line number'
complete -c nl -s v -l starting-line-number -d 'first line number for each section'
complete -c nl -s w -l number-width -d 'use NUMBER columns for line numbers'
complete -c nl -l help -d 'display this help and exit'
complete -c nl -l version -d 'output version information and exit '

