# nm-connection-editor
# Autogenerated from man page /usr/share/man/man1/nm-connection-editor.1.gz
complete -c nm-connection-editor -s t -l type -d 'Type of connection to create or show'
complete -c nm-connection-editor -s s -l show -d 'Expand or collapse the network list to highlight the network connection type …'
complete -c nm-connection-editor -s c -l create -d 'Create a new connection of the type given by --type and allow the user to mod…'
complete -c nm-connection-editor -s e -l edit -d 'Show the network connection edit window for the connection of the given UUID'

