# nmcli
# Autogenerated from man page /usr/share/man/man1/nmcli.1.gz
complete -c nmcli -s a -l ask -d 'When using this option nmcli will stop and ask for any missing required argum…'
complete -c nmcli -s c -l colors -d 'This option controls color output (using terminal escape sequences)'
complete -c nmcli -l complete-args -d 'Instead of conducting the desired action, nmcli will list possible completion…'
complete -c nmcli -s e -l escape -d 'Whether to escape : and  characters in terse tabular mode'
complete -c nmcli -s f -l fields -d 'This option is used to specify what fields (column names) should be printed'
complete -c nmcli -s g -l get-values -d 'This option is used to print values from specific fields'
complete -c nmcli -s h -l help -d 'Print help information'
complete -c nmcli -s p -l pretty -d 'Output is pretty'
complete -c nmcli -s s -l show-secrets -d 'When using this option nmcli will display passwords and secrets that might be…'
complete -c nmcli -s t -l terse -d 'Output is terse'
complete -c nmcli -s v -l version -d 'Show nmcli version'
complete -c nmcli -s w -l wait -d 'This option sets a timeout period for which nmcli will wait for NetworkManage…'
complete -c nmcli -l mode -d 'and is a convenient way to retrieve values for particular fields'
complete -c nmcli -s m
complete -c nmcli -l active -d 'option is specified, only the active profiles are shown'
complete -c nmcli -l order -d 'option can be used to get custom ordering of connections'
complete -c nmcli -o a:na -d 'show [--active] [id | uuid | path | apath] ID'
complete -c nmcli -l temporary -d 'option is specified, in which case the new profile wont exist after NetworkMa…'
complete -c nmcli -l rescan -d 'can be used to either force or disable the scan regardless of how fresh the a…'

