# notify-send
# Autogenerated from man page /usr/share/man/man1/notify-send.1.gz
complete -c notify-send -s '?' -l help -d 'Show help and exit'
complete -c notify-send -s u -l urgency -d 'Specifies the urgency level (low, normal, critical)'
complete -c notify-send -s t -l expire-time -d 'The duration, in milliseconds, for the notification to appear on screen'
complete -c notify-send -s i -l icon -d 'Specifies an icon filename or stock icon to display'
complete -c notify-send -s c -l category -d 'Specifies the notification category'
complete -c notify-send -s h -l hint -d 'Specifies basic extra data to pass'

