# nsenter
# Autogenerated from man page /usr/share/man/man1/nsenter.1.gz
complete -c nsenter -s a -l all
complete -c nsenter -s t -l target
complete -c nsenter -s m -l mount
complete -c nsenter -s u -l uts
complete -c nsenter -s i -l ipc
complete -c nsenter -s n -l net
complete -c nsenter -s p -l pid
complete -c nsenter -s U -l user
complete -c nsenter -s C -l cgroup
complete -c nsenter -s T -l time
complete -c nsenter -s G -l setgid
complete -c nsenter -s S -l setuid
complete -c nsenter -l preserve-credentials
complete -c nsenter -s r -l root
complete -c nsenter -s w -l wd
complete -c nsenter -s F -l no-fork
complete -c nsenter -s Z -l follow-context
complete -c nsenter -s V -l version
complete -c nsenter -s h -l help

