# nss-systemd
# Autogenerated from man page /usr/share/man/man8/nss-systemd.8.gz
complete -c nss-systemd -o rw-r--r--
complete -c nss-systemd -o rw------- -d 'lrwxrwxrwx.  1 root root   19 May 10 4711. user -> foobar. user lrwxrwxrwx'

