# ntfsls
# Autogenerated from man page /usr/share/man/man8/ntfsls.8.gz
complete -c ntfsls -s a -l all -d 'Display all files'
complete -c ntfsls -s F -l classify -d 'Append indicator (one of */=@|) to entries'
complete -c ntfsls -s f -l force -d 'Force execution'
complete -c ntfsls -s h -l help -d 'Print the usage information of  ntfsls and exit'
complete -c ntfsls -s i -l inode -d 'Print inode number of each file'
complete -c ntfsls -s l -l long -d 'Use a long listing format'
complete -c ntfsls -s p -l path -d 'The directory whose contents to list or the file (including the path) about w…'
complete -c ntfsls -s q -l quiet -d 'Suppress some debug/warning/error messages'
complete -c ntfsls -s R -l recursive -d 'Show the contents of all directories beneath the specified directory'
complete -c ntfsls -s s -l system -d 'Unless this options is specified, all files beginning with a dollar sign char…'
complete -c ntfsls -s v -l verbose -d 'Display more debug/warning/error messages'
complete -c ntfsls -s V -l version -d 'Print the version number of  ntfsls and exit'
complete -c ntfsls -o fv -d 'is equivalent to'
complete -c ntfsls -s x -l dos -d 'Display short file names, i. e'

