# ntfscmp
# Autogenerated from man page /usr/share/man/man8/ntfscmp.8.gz
complete -c ntfscmp -s P -l no-progress-bar -d 'Don\'t show progress bars'
complete -c ntfscmp -s v -l verbose -d 'More informational output'
complete -c ntfscmp -s h -l help -d 'Display help and exit'

