# ntfstruncate
# Autogenerated from man page /usr/share/man/man8/ntfstruncate.8.gz
complete -c ntfstruncate -s f -l force -d 'This will override some sensible defaults, such as not using a mounted volume'
complete -c ntfstruncate -s h -l help -d 'Show a list of options with a brief description of each one'
complete -c ntfstruncate -s l -d 'Display licensing information'
complete -c ntfstruncate -s n -l no-action -d 'Simulate the truncation without actually write to device'
complete -c ntfstruncate -s q -l quiet -d 'Suppress some debug/warning/error messages'
complete -c ntfstruncate -s v -l verbose -d 'Display more debug/warning/error messages'
complete -c ntfstruncate -s V -l version -d 'Show the version number, copyright and license of  ntfstruncate '
complete -c ntfstruncate -o fv -d 'is equivalent to'

