# ofm2opl
# Autogenerated from man page /usr/share/man/man1/ofm2opl.1.gz
complete -c ofm2opl -o charcode-format -d 'output character codes according to type, either `hex\', `octal\' or `ascii\''
complete -c ofm2opl -o char-format -d 'output character codes according to stype, either `num\' or `ascii\''
complete -c ofm2opl -o num-format -d 'output numbers according to ntype, either `hex\' or `octal\'; default is hex'
complete -c ofm2opl -o text-format -d 'output coding scheme and family according to ttype, either `mixed\' or `upper\'…'
complete -c ofm2opl -o help -d 'display a brief summary of syntax and options '
complete -c ofm2opl -o verbose -d 'display progress reports'
complete -c ofm2opl -o version -d 'output version information and exit'

