# openssl-sess_id
# Autogenerated from man page /usr/share/man/man1/openssl-sess_id.1ssl.gz
complete -c openssl-sess_id -o help -d 'Print out a usage message'
complete -c openssl-sess_id -o inform -o outform -d 'The input and output formats; the default is \\s-1PEM'
complete -c openssl-sess_id -o in -d 'This specifies the input filename to read session information from or standar…'
complete -c openssl-sess_id -o out -d 'This specifies the output filename to write session information to or standar…'
complete -c openssl-sess_id -o text -d 'Prints out the various public or private key components in plain text in addi…'
complete -c openssl-sess_id -o cert -d 'If a certificate is present in the session it will be output using this optio…'
complete -c openssl-sess_id -o noout -d 'This option prevents output of the encoded version of the session'

