# open
# Autogenerated from man page /usr/share/man/man1/open.1.gz
complete -c open -l help -d 'Show command synopsis'
complete -c open -l manual -d 'Show this manual page'
complete -c open -l version -d 'Show the xdg-utils version information'

