# openvt
# Autogenerated from man page /usr/share/man/man1/openvt.1.gz
complete -c openvt -s c -l console -d 'Use the given VT number and not the first available'
complete -c openvt -s f -l force -d 'Force opening a VT without checking whether it is already in use'
complete -c openvt -s e -l exec -d 'Directly execute the given command, without forking'
complete -c openvt -s s -l switch -d 'Switch to the new VT when starting the command'
complete -c openvt -s u -l user -d 'Figure out the owner of the current VT, and run login as that user'
complete -c openvt -s l -l login -d 'Make the command a login shell'
complete -c openvt -s v -l verbose -d 'Be a bit more verbose'
complete -c openvt -s w -l wait -d 'wait for command to complete'
complete -c openvt -s V -l version -d 'print program version and exit'
complete -c openvt -s h -l help -d 'show this text and exit'

