# opl2ofm
# Autogenerated from man page /usr/share/man/man1/opl2ofm.1.gz
complete -c opl2ofm -o help -d 'display a brief summary of syntax and options '
complete -c opl2ofm -o verbose -d 'display progress reports'
complete -c opl2ofm -o version -d 'output version information and exit'

