# opldecode
# Autogenerated from man page /usr/share/man/man1/opldecode.1.gz
complete -c opldecode -s d -d 'Basename of . pbm file for saving decompressed planes'
complete -c opldecode -s h -d 'Print hex file offsets'
complete -c opldecode -s o -d 'Print file offsets'
complete -c opldecode -s D -d 'Set Debug level [0]'

