# orca
# Autogenerated from man page /usr/share/man/man1/orca.1.gz
complete -c orca -s s -l setup -d 'When starting  orca , initiate the GUI-based configuration'
complete -c orca -s u -l user-prefs-dir -d 'When starting  orca , use  dirname as an alternate directory for the user pre…'
complete -c orca -s e -l enable -d 'When starting  orca , force the enabling of the supplied options'
complete -c orca -s d -l disable -d 'When starting  orca , force the disabling of the supplied options'
complete -c orca -s l -l list-apps -d 'Prints the names of all the currently running applications'
complete -c orca -l debug -d 'Enables debug output for  orca and sends all debug output to a file with a na…'
complete -c orca -l debug-file -d 'Enables debug output for  orca and sends all debug output to the given filena…'
complete -c orca -s v -l version -d 'outputs  orca version number and exits'
complete -c orca -s h -l help -d 'displays  orca help and exits'
complete -c orca -l replace -d 'Replace a currently running  orca process'

