# ovf2ovp
# Autogenerated from man page /usr/share/man/man1/ovf2ovp.1.gz
complete -c ovf2ovp -o charcode-format -d 'output character codes according to type, either `hex\', `octal\' or `ascii\''
complete -c ovf2ovp -o char-format -d 'output character codes according to stype, either `num\' or `ascii\''
complete -c ovf2ovp -o num-format -d 'output numbers according to ntype, either `hex\' or `octal\'; default is hex'
complete -c ovf2ovp -o text-format -d 'output coding scheme and family according to ttype, either `mixed\' or `upper\'…'
complete -c ovf2ovp -o help -d 'display a brief summary of syntax and options'
complete -c ovf2ovp -o verbose -d 'display progress reports'
complete -c ovf2ovp -o version -d 'output version information and exit'

