# ownership
# Autogenerated from man page /usr/share/man/man8/ownership.8.gz
complete -c ownership -s d -l dev-mem -d 'Read memory from device FILE (default: /dev/mem)'
complete -c ownership -s h -l help -d 'Display usage information and exit'
complete -c ownership -s V -l version -d 'Display the version and exit'

