# p7zip
# Autogenerated from man page /usr/share/man/man1/p7zip.1.gz
complete -c p7zip -s d -d 'switch each passed file needs to end with the '
complete -c p7zip -s c -l stdout -l to-stdout -d 'Write output on standard output'
complete -c p7zip -l decompress -l uncompress -d 'Decompress file'
complete -c p7zip -s f -l force -d 'Skip some checks and force compression or decompression'
complete -c p7zip -s h -l help -d 'Print usage'
complete -c p7zip -s k -l keep -d 'Do not delete input file'

