# paperconfig
# Autogenerated from man page /usr/share/man/man8/paperconfig.8.gz
complete -c paperconfig -s v -l version -d 'Print the version of  paperconfig and exit'
complete -c paperconfig -s h -l help -d 'Print help about usage and exit'
complete -c paperconfig -s p -l paper -d 'Use  papername if possible'
complete -c paperconfig -l force -d 'Force interactive selection of the system paper even if the actual paper is a…'

