# partprobe
# Autogenerated from man page /usr/share/man/man8/partprobe.8.gz
complete -c partprobe -s d -l dry-run -d 'Don\'t update the kernel'
complete -c partprobe -s s -l summary -d 'Show a summary of devices and their partitions'
complete -c partprobe -s h -l help -d 'Show summary of options'
complete -c partprobe -s v -l version -d 'Show version of program.  REPORTING BUGS Report bugs to <bug-parted@gnu'

