# partx
# Autogenerated from man page /usr/share/man/man8/partx.8.gz
complete -c partx -s a -l add
complete -c partx -s b -l bytes
complete -c partx -s d -l delete
complete -c partx -s g -l noheadings
complete -c partx -s l -l list
complete -c partx -s n -l nr
complete -c partx -s o -l output
complete -c partx -l output-all
complete -c partx -s P -l pairs
complete -c partx -s r -l raw
complete -c partx -s s -l show
complete -c partx -s t -l type
complete -c partx -l list-types
complete -c partx -s u -l update
complete -c partx -s S -l sector-size
complete -c partx -s v -l verbose
complete -c partx -s V -l version
complete -c partx -s h -l help

