# parted
# Autogenerated from man page /usr/share/man/man8/parted.8.gz
complete -c parted -s h -l help -d 'displays a help message'
complete -c parted -s l -l list -d 'lists partition layout on all block devices'
complete -c parted -s m -l machine -d 'displays machine parseable output'
complete -c parted -s s -l script -d 'never prompts for user intervention'
complete -c parted -s v -l version -d 'displays the version'
complete -c parted -s a -l align -d 'Set alignment for newly created partitions, valid alignment types are: . RS'

