# pasuspender
# Autogenerated from man page /usr/share/man/man1/pasuspender.1.gz
complete -c pasuspender -s h -l help -d 'Show help'
complete -c pasuspender -l version -d 'Show version information'
complete -c pasuspender -s s -l server -d 'Specify the sound server to connect to'

