# pathchk
# Autogenerated from man page /usr/share/man/man1/pathchk.1.gz
complete -c pathchk -s p -d 'check for most POSIX systems'
complete -c pathchk -s P -d 'check for empty names and leading "-"'
complete -c pathchk -l portability -d 'check for all POSIX systems (equivalent to -p -P)'
complete -c pathchk -l help -d 'display this help and exit'
complete -c pathchk -l version -d 'output version information and exit AUTHOR Written by Paul Eggert, David MacK…'

