# pccardctl
# Autogenerated from man page /usr/share/man/man8/pccardctl.8.gz
complete -c pccardctl -s V -d 'Show version information and exit'
complete -c pccardctl -l not
complete -c pccardctl -s v -d 'Increase the verbosity of the ls command'

