# pdfdetach
# Autogenerated from man page /usr/share/man/man1/pdfdetach.1.gz
complete -c pdfdetach -o list -d 'List all of the embedded files in the PDF file'
complete -c pdfdetach -o save -d 'Save the specified embedded file'
complete -c pdfdetach -o savefile -d 'Save the specified embedded file'
complete -c pdfdetach -o saveall -d 'Save all of the embedded files'
complete -c pdfdetach -s o -d 'Set the file name used when saving an embedded file with the "-save" switch, …'
complete -c pdfdetach -o enc -d 'Sets the encoding to use for text output (embedded file names)'
complete -c pdfdetach -o opw -d 'Specify the owner password for the PDF file'
complete -c pdfdetach -o upw -d 'Specify the user password for the PDF file'
complete -c pdfdetach -s v -d 'Print copyright and version information'
complete -c pdfdetach -s h -d 'Print usage information.  ( -help and'
complete -c pdfdetach -l help -d 'are equivalent. ) EXIT CODES The Xpdf tools use the following exit codes:'

