# pibootctl-remove
# Autogenerated from man page /usr/share/man/man1/pibootctl-remove.1.gz
complete -c pibootctl-remove -s h -l help -d 'Show a brief help page for the command'
complete -c pibootctl-remove -s f -l force -d 'Ignore errors if the named configuration does not exist'

