# pibootctl-status
# Autogenerated from man page /usr/share/man/man1/pibootctl-status.1.gz
complete -c pibootctl-status -s h -l help -d 'Show a brief help page for the command'
complete -c pibootctl-status -s a -l all -d 'Include all settings, regardless of modification, in the output'
complete -c pibootctl-status -l json -d 'Use JSON as the output format'
complete -c pibootctl-status -l yaml -d 'Use YAML as the output format'
complete -c pibootctl-status -l shell -d 'Use a var=value format suitable for the shell'

