# pibootctl-show
# Autogenerated from man page /usr/share/man/man1/pibootctl-show.1.gz
complete -c pibootctl-show -s h -l help -d 'Show a brief help page for the command'
complete -c pibootctl-show -s a -l all -d 'Include all settings, regardless of modification, in the output; by default, …'
complete -c pibootctl-show -l json -d 'Use JSON as the output format'
complete -c pibootctl-show -l yaml -d 'Use YAML as the output format'
complete -c pibootctl-show -l shell -d 'Use a var=value output format suitable for the shell'

