# pibootctl-load
# Autogenerated from man page /usr/share/man/man1/pibootctl-load.1.gz
complete -c pibootctl-load -s h -l help -d 'Show a brief help page for the command'
complete -c pibootctl-load -l no-backup -d 'Don\\(aqt take an automatic backup of the current boot configuration if one do…'

