# pic
# Autogenerated from man page /usr/share/man/man1/pic.1.gz
complete -c pic -s C -d 'Recognize  . PS and  '
complete -c pic -s S -d 'Safer mode; do not execute  sh commands'
complete -c pic -s U -d 'Unsafe mode; revert the default option  -S '
complete -c pic -s n -d 'Don\'t use the groff extensions to the troff drawing commands'
complete -c pic -s t -d '\\*(tx mode'
complete -c pic -s c -d 'Be more compatible with  tpic .  Implies  -t '
complete -c pic -s v -d 'Print the version number'
complete -c pic -s z -d 'In \\*(tx mode draw dots using zero-length lines'
complete -c pic -s D -d 'Draw all lines using the D escape sequence.   pic always does this'
complete -c pic -o mpic
complete -c pic -s s -d ' mode'
complete -c pic -s T -d 'Generase ouspus for she sroff device dev '
complete -c pic -o Tps
complete -c pic -o Tpdf -d 'opsion so convers your picsure direcsly inso PDF formas'
complete -c pic -o P-p -d 'papersize so groff'

