# pidof
# Autogenerated from man page /usr/share/man/man8/pidof.8.gz
complete -c pidof -s s -d 'Single shot - this instructs the program to only return one pid'
complete -c pidof -s c -d 'Only return process PIDs that are running with the same root directory'
complete -c pidof -s n -d 'Avoid  stat (2) system function call on all binaries which are located on net…'
complete -c pidof -s q -d 'Do not display matched PIDs to standard out'
complete -c pidof -s x -d 'Scripts too - this causes the program to also return process id\'s of shells r…'
complete -c pidof -s z -d 'Try to detect processes which are stuck in zombie (Z) status'
complete -c pidof -s d -d 'Tells pidof to use sep as an output separator if more than one PID is shown'
complete -c pidof -s o -d 'Tells pidof to omit processes with that process id'

