# pinentry-curses
# Autogenerated from man page /usr/share/man/man1/pinentry-curses.1.gz
complete -c pinentry-curses -l version -d 'Print the program version and licensing information'
complete -c pinentry-curses -l help -d 'Print a usage message summarizing the most useful command-line options'
complete -c pinentry-curses -l debug -s d -d 'Turn on some debugging.   Mostly useful for the maintainers'
complete -c pinentry-curses -l enhanced -s e -d 'Ask for timeouts and insurance, too'
complete -c pinentry-curses -l no-global-grab -s g -d 'Grab the keyboard only when the window is focused'
complete -c pinentry-curses -l parent-wid -d 'Use window ID N as the parent window for positioning the window'
complete -c pinentry-curses -l display -l ttyname -l ttytype -l lc-type -l lc-messages -d 'These options are used to pass localization information to pinentry-curses'

