# pipewire
# Autogenerated from man page /usr/share/man/man1/pipewire.1.gz
complete -c pipewire -s h -l help -d 'Show help'
complete -c pipewire -s v -l verbose -d 'Increase the verbosity by one level'
complete -c pipewire -l version -d 'Show version information'
complete -c pipewire -s c -l config -d 'Load the given config file (Default: pipewire. conf)'

