# pkaction
# Autogenerated from man page /usr/share/man/man1/pkaction.1.gz
complete -c pkaction -l action-id -d 'then all actions are displayed.  Otherwise the action action'
complete -c pkaction -l verbose -d 'option only the name of the action is shown'

