# pkcheck
# Autogenerated from man page /usr/share/man/man1/pkcheck.1.gz
complete -c pkcheck -l process -d '(see below) or'
complete -c pkcheck -l system-bus-name -d 'action.  The'
complete -c pkcheck -l detail -d 'option can be used zero or more times to pass details about action.  If'
complete -c pkcheck -l allow-user-interaction -d 'is passed, pkcheck blocks while waiting for authentication'
complete -c pkcheck -l enable-internal-agent -d 'is passed.  AUTHOR'

