# pkcon
# Autogenerated from man page /usr/share/man/man1/pkcon.1.gz
complete -c pkcon -l version -d 'Print the program version and exit'
complete -c pkcon -s h -l help -d 'Show help options'
complete -c pkcon -l help-all -d 'Show all help options'
complete -c pkcon -l filter -d 'Set the filter to use'
complete -c pkcon -s y -l noninteractive -d 'Install packages without asking for confirmation'
complete -c pkcon -l only-download -d 'Prepare the transaction by downloading packages only'
complete -c pkcon -s n -l background -d 'Run the command using idle network bandwidth and also using less power'
complete -c pkcon -s p -l plain -d 'Print to screen a machine-readable output, rather than using animated widgets'
complete -c pkcon -s v -l verbose -d 'Show debugging information'
complete -c pkcon -s c -l cache-age -d 'Set the maximum acceptable age for cached metadata, in seconds'
complete -c pkcon -l allow-untrusted -d 'Allow untrusted packages to be installed'
complete -c pkcon -l allow-downgrade -d 'Allow packages to be downgraded during transaction'
complete -c pkcon -l allow-reinstall -d 'Allow packages to be reinstalled during transaction'

