# plank
# Autogenerated from man page /usr/share/man/man1/plank.1.gz
complete -c plank -s h -l help -d 'Show help options'
complete -c plank -l help-all -d 'Show all help options'
complete -c plank -l help-gapplication -d 'Show GApplication options'
complete -c plank -l help-gtk -d 'Show GTK+ Options . SS "Application Options:"'
complete -c plank -s d -l debug -d 'Enable debug logging'
complete -c plank -s v -l verbose -d 'Enable verbose logging'
complete -c plank -s n -l name -d 'The name of this dock.  Defaults to "dock1"'
complete -c plank -l preferences -d 'Show preferences dialog of the just started or already running instance'
complete -c plank -s V -l version -d 'Show the application\'s version'
complete -c plank -l display -d 'X display to use'

