# plog
# Autogenerated from man page /usr/share/man/man1/plog.1.gz
complete -c plog -s q -l quick -d 'disconnect when ip-up finishes running'
complete -c plog -s r -d 'causes the connection to be redialed after it is dropped'
complete -c plog -s d -d 'toggles the state of pppd\'s debug option'
complete -c plog -s c -d 'causes  pppd (8) to renegotiate compression'
complete -c plog -s a -d 'stops all running ppp connections'
complete -c plog -s h -d 'displays help information'
complete -c plog -s v -d 'prints the version and exits'

