# pod2text
# Autogenerated from man page /usr/share/man/man1/pod2text.1.gz
complete -c pod2text -s a -l alt -d 'Use an alternate output format that, among other things, uses a different hea…'
complete -c pod2text -l code -d 'Include any non-POD text from the input file in the output as well'
complete -c pod2text -s c -l color -d 'Format the output with \\s-1ANSI\\s0 color escape sequences'
complete -c pod2text -l errors -d 'Set the error handling style'
complete -c pod2text -s i -l indent -d 'Set the number of spaces to indent regular text, and the default indentation …'
complete -c pod2text -s h -l help -d 'Print out usage information and exit'
complete -c pod2text -s l -l loose -d 'Print a blank line after a \\f(CW\\*(C`=head1\\*(C\' heading'
complete -c pod2text -s m -l left-margin -l margin -d 'The width of the left margin in spaces.   Defaults to 0'
complete -c pod2text -l nourls -d 'Normally, L<> formatting codes with a \\s-1URL\\s0 but anchor text are formatte…'
complete -c pod2text -s o -l overstrike -d 'Format the output with overstrike printing'
complete -c pod2text -s q -l quotes -d 'Sets the quote marks used to surround C<> text to quotes'
complete -c pod2text -s s -l sentence -d 'Assume each sentence ends with two spaces and try to preserve that spacing'
complete -c pod2text -l stderr -d 'By default, pod2text dies if any errors are detected in the \\s-1POD\\s0 input'
complete -c pod2text -s t -l termcap -d 'Try to determine the width of the screen and the bold and underline sequences…'
complete -c pod2text -s u -l utf8 -d 'By default, pod2text tries to use the same output encoding as its input encod…'

