# ppa-purge
# Autogenerated from man page /usr/share/man/man1/ppa-purge.1.gz
complete -c ppa-purge -s h -d 'Display usage help'
complete -c ppa-purge -s p -d 'Name of the PPA to be reset, the default value is ppa'
complete -c ppa-purge -s s -d 'Address of the repository server, the default value is ppa. launchpad. net'

