# ppdhtml
# Autogenerated from man page /usr/share/man/man1/ppdhtml.1.gz
complete -c ppdhtml -s D -d 'Sets the named variable for use in the source file'
complete -c ppdhtml -s I -d 'Specifies an alternate include directory'

