# pppoe-discovery
# Autogenerated from man page /usr/share/man/man8/pppoe-discovery.8.gz
complete -c pppoe-discovery -s I -d 'RS The -I option specifies the Ethernet interface to use'
complete -c pppoe-discovery -s D -d 'RS The -D option causes every packet to be dumped to the specified file_name'
complete -c pppoe-discovery -s U -d 'RS Causes pppoe-discovery to use the Host-Uniq tag in its discovery packets'
complete -c pppoe-discovery -s W -d 'RS Causes pppoe-discovery to use the Host-Uniq tag in its discovery packets'
complete -c pppoe-discovery -s S -d 'RS Specifies the desired service name'
complete -c pppoe-discovery -s C -d 'RS Specifies the desired access concentrator name'
complete -c pppoe-discovery -s Q -d 'RS Causes pppoe-discovery to avoid printing discovered access concentrator na…'
complete -c pppoe-discovery -s t -d 'RS Changes the discovery timeout for PADI requests, in seconds'
complete -c pppoe-discovery -s a -d 'RS Changes the number of PADI discovery attempts made'
complete -c pppoe-discovery -s V -s h

