# pppstats
# Autogenerated from man page /usr/share/man/man8/pppstats.8.gz
complete -c pppstats -s a -d 'Display absolute values rather than deltas'
complete -c pppstats -s d -d 'Show data rate (kB/s) instead of bytes'
complete -c pppstats -s c -d 'Repeat the display  count times'
complete -c pppstats -s r -d 'Display additional statistics summarizing the compression ratio achieved by t…'
complete -c pppstats -s v -d 'Display additional statistics relating to the performance of the Van Jacobson…'
complete -c pppstats -s w -d 'Pause  wait seconds between each display'
complete -c pppstats -s z -d 'Instead of the standard display, show statistics indicating the performance o…'

