# preconv
# Autogenerated from man page /usr/share/man/man1/preconv.1.gz
complete -c preconv -s d -d 'Emit debugging messages to standard error (mainly the used encoding)'
complete -c preconv -s D -d 'Specify default encoding if everything fails (see below)'
complete -c preconv -s e -d 'Specify input encoding explicitly, overriding all other methods'
complete -c preconv -l help -d 'TQ  -h Print a help message and exit'
complete -c preconv -s r -d 'Do not add . lf requests'
complete -c preconv -s k -d and
complete -c preconv -s K -d 'options of groff '
complete -c preconv -s h -d 'Print a help message and exit'
complete -c preconv -l version
complete -c preconv -s v -d 'Print the version number and exit'
complete -c preconv -o '*-' -d 'tag1 : value1 ; tag2 : value2 ; '

