# preunzip
# Autogenerated from man page /usr/share/man/man1/preunzip.1.gz
complete -c preunzip -s h -l help -d 'display help'
complete -c preunzip -s d -l decompress -d 'force decompression'
complete -c preunzip -s z -l compress -d 'dorce compression'
complete -c preunzip -s L -l license -d 'display software license'
complete -c preunzip -s V -l version -d 'display version'
complete -c preunzip -s c -l stdout -d 'decompress to standard output'
complete -c preunzip -s f -l force -d force
complete -c preunzip -s k -l keep -d 'keep input files'
complete -c preunzip -s s -l sort -d 'sort and remove duplicates before compressing'
complete -c preunzip -s S -l nocwl -d 'do not rename . wl suffix to . cwl (use . wl. pz instead)'
complete -c preunzip -s q -l quiet -d 'suppress all warnings AUTHOR This manual page was written by Brian Nelson <py…'

