# prezip-bin
# Autogenerated from man page /usr/share/man/man1/prezip-bin.1.gz
complete -c prezip-bin -s V -d 'Display prezip-bin version number to standard output'
complete -c prezip-bin -s d -d 'Read a compressed word list from standard input and decompress it to standard…'
complete -c prezip-bin -s z -d 'Read a binary word list from standard input and compress it to standard output'

