# print
# Autogenerated from man page /usr/share/man/man1/print.1.gz
complete -c print -l action -d 'Performs the specified action on the files'
complete -c print -l debug -d 'Turns on extra information to find out what is happening'
complete -c print -l nopager -d 'Ignores any "copiousoutput" directive and sends output to STDOUT'
complete -c print -l norun -d 'Displays the found command without actually executing it'

