# ps
# Autogenerated from man page /usr/share/man/man1/ps.1.gz
complete -c ps -s a -d option
complete -c ps -s M -d 'will be considered identical to Z and so on'
complete -c ps -s A -d 'Select all processes.   Identical to'
complete -c ps -s e
complete -c ps -s d -d 'Select all processes except session leaders'
complete -c ps -l deselect -d 'Select all processes except those that fulfill the specified conditions (nega…'
complete -c ps -s N
complete -c ps -l pid
complete -c ps -s C -d 'Select by command name'
complete -c ps -s G -d 'Select by real group ID (RGID) or name'
complete -c ps -s g -d 'Select by session OR by effective group name'
complete -c ps -s s -d and
complete -c ps -l group -d options
complete -c ps -l Group -d 'Select by real group ID (RGID) or name.   Identical to'
complete -c ps -s p -d and
complete -c ps -l ppid -d 'Select by parent process ID'
complete -c ps -s q -d and
complete -c ps -l quick-pid
complete -c ps -l sid -d 'Select by session ID.   Identical to'
complete -c ps -s t -d and
complete -c ps -l tty -d 'but can also be used with an empty ttylist to indicate the terminal associate…'
complete -c ps -s u -d and
complete -c ps -l user
complete -c ps -s U -d 'Select by real user ID (RUID) or name'
complete -c ps -l User -d 'Select by real user ID (RUID) or name.   Identical to'
complete -c ps -s c -d 'Show different scheduler information for the'
complete -c ps -s l -d option
complete -c ps -l context -d 'Display security context format (for SELinux)'
complete -c ps -s f -d 'Do full-format listing'
complete -c ps -s L -d 'the NLWP (number of threads) and LWP (thread ID) columns will be added'
complete -c ps -s F -d 'Extra full format.   See the'
complete -c ps -l format -d 'user-defined format.   Identical to'
complete -c ps -s o -d 'and o '
complete -c ps -s j -d 'Jobs format'
complete -c ps -s y -d 'option is often useful with this'
complete -c ps -s O -d '(user-defined output format with some common fields predefined) or can be use…'
complete -c ps -l sort -d 'When used as a formatting option, it is identical to'
complete -c ps -l cols -d 'Set screen width'
complete -c ps -l columns -d 'Set screen width'
complete -c ps -l cumulative -d 'Include some dead child process data (as a sum with the parent)'
complete -c ps -l forest -d 'ASCII art process tree'
complete -c ps -l headers -d and
complete -c ps -l no-headers -d 'to enable printing headers each page or disable headers entirely, respectively'
complete -c ps -s H -d 'Show process hierarchy (forest)'
complete -c ps -l lines -d 'Set screen height'
complete -c ps -l no-heading -d 'is an alias for this option'
complete -c ps -l rows -d 'Set screen height'
complete -c ps -s w -d 'Wide output.   Use this option twice for unlimited width'
complete -c ps -l width -d 'Set screen width.  THREAD DISPLAY'
complete -c ps -s m -d 'Show threads after processes'
complete -c ps -s T -d 'Show threads, possibly with SPID column'
complete -c ps -l help -d 'Print a help message'
complete -c ps -l info -d 'Print debugging info'
complete -c ps -s V -d 'Print the procps-ng version'
complete -c ps -l version -d 'Print the procps-ng version'
complete -c ps -o '	not'

