# ps2pk
# Autogenerated from man page /usr/share/man/man1/ps2pk.1.gz
complete -c ps2pk -o aAFMfile -d 'Overrules the name that is used to locate the AFM file'
complete -c ps2pk -o eenc -d 'Name of a file containing an encoding scheme  (default - the encoding named i…'
complete -c ps2pk -o Eextension -d 'The extension factor (real value, default 1. 0)'
complete -c ps2pk -o mmodename -d 'A modename such as would be used by METAFONT (default "Unknown mode")'
complete -c ps2pk -o Ppointsize -d 'The desired pointsize (real value, default 10. 0 points)'
complete -c ps2pk -o Rbaseres -d 'The desired base resolution (integer value, default 300 dpi)'
complete -c ps2pk -o raspectratio -d 'The desired aspect ratio (expression, integerY/integerX, default 300/300)'
complete -c ps2pk -o Sslant -d 'The slant (real value, default 0. 0)'
complete -c ps2pk -o Xxres -d 'The resolution in the X direction (integer value, default 300 dpi)'
complete -c ps2pk -o Yyres -d 'The resolution in the Y direction (integer value, default the value of xres)'
complete -c ps2pk -s v -d 'Verbose flag.  (Tells what the program is doing. )'

