# ps2pdf14
# Autogenerated from man page /usr/share/man/man1/ps2pdf14.1.gz
complete -c ps2pdf14 -o dCompatibilityLevel -d 'switch in the command line'
complete -c ps2pdf14 -o dPDFSETTINGS -d 'figure. ps proof. pdf'
complete -c ps2pdf14 -s t -d ps2pdf

