# ps2pdfwr
# Autogenerated from man page /usr/share/man/man1/ps2pdfwr.1.gz
complete -c ps2pdfwr -s q -o dNOPAUSE -o dBATCH -o sDEVICE
complete -c ps2pdfwr -o dOutputFile -d 'argument, all preceded and followed by any command-line arguments'
complete -c ps2pdfwr -o dSAFER -d 'is prepended before all the other options (This is now redundant as "SAFER" i…'

