# ps2pdf12
# Autogenerated from man page /usr/share/man/man1/ps2pdf12.1.gz
complete -c ps2pdf12 -o dCompatibilityLevel -d 'switch in the command line'
complete -c ps2pdf12 -o dPDFSETTINGS -d 'figure. ps proof. pdf'
complete -c ps2pdf12 -s t -d ps2pdf

