# ptx
# Autogenerated from man page /usr/share/man/man1/ptx.1.gz
complete -c ptx -s A -l auto-reference -d 'output automatically generated references'
complete -c ptx -s G -l traditional -d 'behave more like System V \'ptx\''
complete -c ptx -s F -l flag-truncation -d 'use STRING for flagging line truncations.  The default is \'/\''
complete -c ptx -s M -l macro-name -d 'macro name to use instead of \'xx\''
complete -c ptx -s O -l format -d 'generate output as roff directives'
complete -c ptx -s R -l right-side-refs -d 'put references at right, not counted in -w'
complete -c ptx -s S -l sentence-regexp -d 'for end of lines or end of sentences'
complete -c ptx -s T -d 'generate output as TeX directives'
complete -c ptx -s W -l word-regexp -d 'use REGEXP to match each keyword'
complete -c ptx -s b -l break-file -d 'word break characters in this FILE'
complete -c ptx -s f -l ignore-case -d 'fold lower case to upper case for sorting'
complete -c ptx -s g -l gap-size -d 'gap size in columns between output fields'
complete -c ptx -s i -l ignore-file -d 'read ignore word list from FILE'
complete -c ptx -s o -l only-file -d 'read only word list from this FILE'
complete -c ptx -s r -l references -d 'first field of each line is a reference '
complete -c ptx -s w -l width -d 'output width in columns, reference excluded'
complete -c ptx -l help -d 'display this help and exit'
complete -c ptx -s t -l typeset-mode
complete -c ptx -l version -d 'output version information and exit AUTHOR Written by F.  Pinard'

