# pw-dot
# Autogenerated from man page /usr/share/man/man1/pw-dot.1.gz
complete -c pw-dot -s r -l remote -d 'The name the remote instance to connect to'
complete -c pw-dot -s h -l help -d 'Show help'
complete -c pw-dot -l version -d 'Show version information'
complete -c pw-dot -s a -l all -d 'Show all object types'
complete -c pw-dot -s s -l smart -d 'Show linked objects only'
complete -c pw-dot -s d -l detail -d 'Show all object properties'
complete -c pw-dot -s o -l output -d 'Output file name (Default pw. dot).  Use - for stdout'
complete -c pw-dot -s L -l lr -d 'Lay the graph from left to right, instead of dot\\(aqs default top to bottom'
complete -c pw-dot -s 9 -l 90 -d 'Lay the graph using 90-degree angles in edges'

