# pw-metadata
# Autogenerated from man page /usr/share/man/man1/pw-metadata.1.gz
complete -c pw-metadata -s r -l remote -d 'The name the remote instance to use'
complete -c pw-metadata -s h -l help -d 'Show help'
complete -c pw-metadata -l version -d 'Show version information'
complete -c pw-metadata -s m -l monitor -d 'Keeps running and log the changes to the metadata'
complete -c pw-metadata -s d -l delete -d 'Delete all metadata for id or for the specified key of object id'

