# pw-profiler
# Autogenerated from man page /usr/share/man/man1/pw-profiler.1.gz
complete -c pw-profiler -s r -l remote -d 'The name the remote instance to monitor'
complete -c pw-profiler -s h -l help -d 'Show help'
complete -c pw-profiler -l version -d 'Show version information'
complete -c pw-profiler -s o -l output -d 'Profiler output name (default "profiler. log")'

