# pwck
# Autogenerated from man page /usr/share/man/man8/pwck.8.gz
complete -c pwck -l badname -d 'Allow names that do not conform to standards'
complete -c pwck -s h -l help -d 'Display help message and exit'
complete -c pwck -s q -l quiet -d 'Report errors only'
complete -c pwck -s r -l read-only -d 'Execute the pwck command in read-only mode'
complete -c pwck -s R -l rootCHROOT_DIR -d 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c pwck -s s -l sort -d 'Sort entries in /etc/passwd and /etc/shadow by UID'
complete -c pwck -l root

