# pwd
# Autogenerated from man page /usr/share/man/man1/pwd.1.gz
complete -c pwd -s L -l logical -d 'use PWD from environment, even if it contains symlinks'
complete -c pwd -s P -l physical -d 'avoid all symlinks'
complete -c pwd -l help -d 'display this help and exit'
complete -c pwd -l version -d 'output version information and exit'

