# pwunconv
# Autogenerated from man page /usr/share/man/man8/pwunconv.8.gz
complete -c pwunconv -s h -l help -d 'Display help message and exit'
complete -c pwunconv -s R -l rootCHROOT_DIR -d 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c pwunconv -l root

