# py3clean
# Autogenerated from man page /usr/share/man/man1/py3clean.1.gz
complete -c py3clean -l version -d 'show program\\(aqs version number and exit'
complete -c py3clean -s h -l help -d 'show this help message and exit'
complete -c py3clean -s v -l verbose -d 'turn verbose more one'
complete -c py3clean -s q -l quiet -d 'be quiet'
complete -c py3clean -s p -l package -d 'specify Debian package name to clean'
complete -c py3clean -s V -d 'specify Python 3 version to clean'

