# py3rsa-priv2pub
# Autogenerated from man page /usr/share/man/man1/py3rsa-priv2pub.1.gz
complete -c py3rsa-priv2pub -s h -l help -d 'show help message and exit'
complete -c py3rsa-priv2pub -s i -l input -d 'input filename.  Read from stdin if not specified'
complete -c py3rsa-priv2pub -l output -d 'output filename.  write to stdout of not specified'
complete -c py3rsa-priv2pub -l inform -d 'key format of input - default PEM'
complete -c py3rsa-priv2pub -l outform -d 'key format of output - default PEM AUTHOR ,py3rsa-priv2pub was written by Syb…'

