# py3rsa-keygen
# Autogenerated from man page /usr/share/man/man1/py3rsa-keygen.1.gz
complete -c py3rsa-keygen -s h -l help -d 'show help message and exit'
complete -c py3rsa-keygen -l pubout -d 'output filename for the public key'
complete -c py3rsa-keygen -s o -l out -d 'output filename for the private key'
complete -c py3rsa-keygen -l form -d 'key format of the private and public keys - default PEM AUTHOR ,py3rsa-keygen…'

