# py3rsa-encrypt
# Autogenerated from man page /usr/share/man/man1/py3rsa-encrypt.1.gz
complete -c py3rsa-encrypt -s h -l help -d 'show help message and exit'
complete -c py3rsa-encrypt -s i -l input -d 'name of the file to encrypt.  read from stdin if not specified'
complete -c py3rsa-encrypt -l output -d 'name of the file to write the encrypted file to'
complete -c py3rsa-encrypt -l keyform -d 'key format of the public key - default PEM AUTHOR ,py3rsa-encrypt was written…'

