# py3rsa-verify
# Autogenerated from man page /usr/share/man/man1/py3rsa-verify.1.gz
complete -c py3rsa-verify -s h -l help -d 'show help message and exit'
complete -c py3rsa-verify -s i -l input -d 'name of the signed file to verify.  Read from stdin if not specified'
complete -c py3rsa-verify -l keyform -d 'key format of the public key - default PEM EXIT STATUS 0 if signature can be …'

