# pygettext3
# Autogenerated from man page /usr/share/man/man1/pygettext3.1.gz
complete -c pygettext3 -s a -l extract-all -d 'Extract all strings'
complete -c pygettext3 -s d -l default-domain -d 'Rename the default output file from messages. pot to name. pot'
complete -c pygettext3 -s E -l escape -d 'Replace non-ASCII characters with octal escape sequences'
complete -c pygettext3 -s D -l docstrings -d 'Extract module, class, method, and function docstrings'
complete -c pygettext3 -s h -l help -d 'Print this help message and exit'
complete -c pygettext3 -s k -l keyword -d 'Keywords to look for in addition to the default set, which are: _'
complete -c pygettext3 -s K -l no-default-keywords -d 'Disable the default set of keywords (see above)'
complete -c pygettext3 -l no-location -d 'Do not write filename/lineno location comments'
complete -c pygettext3 -s n -l add-location -d 'Write filename/lineno location comments indicating where each extracted strin…'
complete -c pygettext3 -s o -l output -d 'Rename the default output file from messages. pot to FILENAME'
complete -c pygettext3 -s p -l output-dir -d 'Output files will be placed in directory DIR'
complete -c pygettext3 -s S -l style -d 'Specify which style to use for location comments.  Two styles are supported: '
complete -c pygettext3 -s v -l verbose -d 'Print the names of the files being processed'
complete -c pygettext3 -s V -l version -d 'Print the version of pygettext and exit'
complete -c pygettext3 -s w -l width -d 'Set width of output to columns'
complete -c pygettext3 -s x -l exclude-file -d 'Specify a file that contains a list of strings that are not be extracted from…'
complete -c pygettext3 -o S/--style
complete -c pygettext3 -s X -l no-docstrings -d 'Specify a file that contains a list of files (one per line) that should not h…'

