# pyrcc5
# Autogenerated from man page /usr/share/man/man1/pyrcc5.1.gz
complete -c pyrcc5 -o help -d 'Show a summary of the options'
complete -c pyrcc5 -o version -d 'Display the version number and exit'
complete -c pyrcc5 -s o -d 'Write the generated output to FILE instead of stdout'
complete -c pyrcc5 -o threshold -d 'Set the threshold above which files should be compressed'
complete -c pyrcc5 -o compress -d 'Set the compression level for all input files'
complete -c pyrcc5 -o root -d 'Search all resource referenced in a . qrc file under PATH'
complete -c pyrcc5 -o no-compress -d 'Do not compress the resource files at all'

