# pythran-config
# Autogenerated from man page /usr/share/man/man1/pythran-config.1.gz
complete -c pythran-config -s h -l help -d 'show this help message and exit'
complete -c pythran-config -l compiler -d 'print default compiler'
complete -c pythran-config -l cflags -d 'print compilation flags'
complete -c pythran-config -l libs -d 'print linker flags'
complete -c pythran-config -l no-python -d 'do not include Python-related flags'
complete -c pythran-config -l verbose -s v -d 'verbose mode: [-v] prints warnings if pythranrc has an invalid configuration;…'

