# qemu-storage-daemon
# Autogenerated from man page /usr/share/man/man1/qemu-storage-daemon.1.gz
complete -c qemu-storage-daemon -s h -l help -d 'Display help and exit'
complete -c qemu-storage-daemon -s V -l version -d 'Display version information and exit'
complete -c qemu-storage-daemon -s T -l trace -d 'Specify tracing options. sp [enable=]PATTERN NDENT 7. 0 NDENT 3'
complete -c qemu-storage-daemon -l blockdev -d 'is a block node definition'
complete -c qemu-storage-daemon -l chardev -d 'is a character device definition'
complete -c qemu-storage-daemon -l export -d 'is a block export definition'
complete -c qemu-storage-daemon -l monitor -d 'is a QMP monitor definition'
complete -c qemu-storage-daemon -l nbd-server -d 'is a server for NBD exports.  Both TCP and UNIX domain sockets are supported'
complete -c qemu-storage-daemon -l object -d 'is a QEMU user creatable object definition.  List object types with help'
complete -c qemu-storage-daemon -l pidfile -d 'is the path to a file where the daemon writes its pid'

