# qemu-make-debian-root
# Autogenerated from man page /usr/share/man/man8/qemu-make-debian-root.8.gz
complete -c qemu-make-debian-root -s k -d 'Keep file system'
complete -c qemu-make-debian-root -s s -d 'Create a sparse image.  SEE ALSO qemu (1), qemu-img (1)'

