# qemu-pr-helper
# Autogenerated from man page /usr/share/man/man8/qemu-pr-helper.8.gz
complete -c qemu-pr-helper -s d -l daemon -d 'run in the background (and create a PID file)'
complete -c qemu-pr-helper -s q -l quiet -d 'decrease verbosity'
complete -c qemu-pr-helper -s v -l verbose -d 'increase verbosity'
complete -c qemu-pr-helper -s f -l pidfile -d 'PID file when running as a daemon'
complete -c qemu-pr-helper -s k -l socket -d 'path to the socket'
complete -c qemu-pr-helper -s T -l trace -d 'Specify tracing options. sp [enable=]PATTERN NDENT 7. 0 NDENT 3'
complete -c qemu-pr-helper -s u -l user -d 'user to drop privileges to'
complete -c qemu-pr-helper -s g -l group -d 'group to drop privileges to'
complete -c qemu-pr-helper -s h -l help -d 'Display a help message and exit'
complete -c qemu-pr-helper -s V -l version -d 'Display version information and exit'

