# rdiffdir
# Autogenerated from man page /usr/share/man/man1/rdiffdir.1.gz
complete -c rdiffdir -l write-sig-to -d 'This option is only used in  delta and  tar modes'
complete -c rdiffdir -s z -l gzip-compress -d 'Enable gzip compression and decompression of signature and delta files'

