# rdma-link
# Autogenerated from man page /usr/share/man/man8/rdma-link.8.gz
complete -c rdma-link -s V
complete -c rdma-link -s d -d 'rdma link show [  DEV/PORT_INDEX  ] rdma link add NAME type TYPE netdev NETDE…'

