# rdma-system
# Autogenerated from man page /usr/share/man/man8/rdma-system.8.gz
complete -c rdma-system -s V
complete -c rdma-system -s d -d 'rdma system show rdma system set netns NEWMODE rdma system help'

