# rdma-dev
# Autogenerated from man page /usr/share/man/man8/rdma-dev.8.gz
complete -c rdma-dev -s V
complete -c rdma-dev -s d -d 'rdma dev show [  DEV  ] rdma dev set [  DEV  ] name NEWNAME rdma dev set [  D…'

