# rdmsr
# Autogenerated from man page /usr/share/man/man1/rdmsr.1.gz
complete -c rdmsr -l help -s h -d 'Print a list of available options'
complete -c rdmsr -l version -s V -d 'Print current version'
complete -c rdmsr -l hexadecimal -s x -d 'Display output in hexadecimal (lower case)'
complete -c rdmsr -l capital-hex -s X -d 'Display output in hexadecimal (upper case)'
complete -c rdmsr -l decimal -s d -d 'Display output in signed decimal'
complete -c rdmsr -l unsigned -s u -d 'Display output in unsigned decimal'
complete -c rdmsr -l octal -s o -d 'Display output in octal'
complete -c rdmsr -l c-language -s c -d 'Format output as a C language constant'
complete -c rdmsr -l zero-pad -s 0 -d 'Output leading zeroes'
complete -c rdmsr -l raw -s r -d 'Output raw binary'
complete -c rdmsr -l all -s a -d 'All processors'
complete -c rdmsr -l processor -s p -d 'Select processor number (default: 0)'
complete -c rdmsr -l bitfield -s f -d 'Output bits [h:l] only'

