# readprofile
# Autogenerated from man page /usr/share/man/man8/readprofile.8.gz
complete -c readprofile -s a -l all
complete -c readprofile -s b -l histbin
complete -c readprofile -s i -l info
complete -c readprofile -s m -l mapfile
complete -c readprofile -s M -l multiplier
complete -c readprofile -s p -l profile
complete -c readprofile -s r -l reset
complete -c readprofile -s s -l counters
complete -c readprofile -s v -l verbose
complete -c readprofile -s V -l version
complete -c readprofile -s h -l help

