# resize2fs
# Autogenerated from man page /usr/share/man/man8/resize2fs.8.gz
complete -c resize2fs -s b -d 'Turns on the 64bit feature, resizes the group descriptors as necessary, and m…'
complete -c resize2fs -s d -d 'Turns on various resize2fs debugging features, if they have been compiled int…'
complete -c resize2fs -s f -d 'Forces resize2fs to proceed with the file system resize operation, overriding…'
complete -c resize2fs -s F -d 'Flush the file system device\'s buffer caches before beginning'
complete -c resize2fs -s M -d 'Shrink the file system to minimize its size as much as possible, given the fi…'
complete -c resize2fs -s p -d 'Print out percentage completion bars for each  resize2fs phase during an offl…'
complete -c resize2fs -s P -d 'Print an estimate of the number of file system blocks in the file system if i…'
complete -c resize2fs -s s -d 'Turns off the 64bit feature and frees blocks that are no longer in use'
complete -c resize2fs -s S -d 'The  resize2fs program will heuristically determine the RAID stride that was …'
complete -c resize2fs -s z -d 'Before overwriting a file system block, write the old contents of the block t…'

