# rmmod
# Autogenerated from man page /usr/share/man/man8/rmmod.8.gz
complete -c rmmod -s v -l verbose -d 'Print messages about what the program is doing'
complete -c rmmod -s f -l force -d 'This option can be extremely dangerous: it has no effect unless CONFIG_MODULE…'
complete -c rmmod -s s -l syslog -d 'Send errors to syslog instead of standard error'
complete -c rmmod -s V -l version -d 'Show version of program and exit'
complete -c rmmod -s r -d 'option instead.  OPTIONS'

