# rsyslogd
# Autogenerated from man page /usr/share/man/man8/rsyslogd.8.gz
complete -c rsyslogd -s D -d 'Runs the Bison config parser in debug mode'
complete -c rsyslogd -s d -d 'Turns on debug mode.  See the DEBUGGING section for more information'
complete -c rsyslogd -s f -d 'Specify an alternative configuration file instead of R /etc/rsyslog'
complete -c rsyslogd -s i -d 'Specify an alternative pid file instead of the default one'
complete -c rsyslogd -s n -d 'Avoid auto-backgrounding'
complete -c rsyslogd -s N -d 'Do a config check'
complete -c rsyslogd -s o -d 'Generates a consolidated config file  fullconf that contains all of rsyslog\'s…'
complete -c rsyslogd -s C -d 'This prevents rsyslogd from changing to the root directory'
complete -c rsyslogd -s v -d 'Print version and exit'

