# rtcwake
# Autogenerated from man page /usr/share/man/man8/rtcwake.8.gz
complete -c rtcwake -s A -l adjfile
complete -c rtcwake -s a -l auto
complete -c rtcwake -l date
complete -c rtcwake -s d -l device
complete -c rtcwake -s l -l local
complete -c rtcwake -l list-modes
complete -c rtcwake -s m -l mode
complete -c rtcwake -s n -l dry-run
complete -c rtcwake -s s -l seconds
complete -c rtcwake -s t -l time
complete -c rtcwake -s u -l utc
complete -c rtcwake -s v -l verbose
complete -c rtcwake -s V -l version
complete -c rtcwake -s h -l help

