# runcon
# Autogenerated from man page /usr/share/man/man1/runcon.1.gz
complete -c runcon -s c -l compute -d 'compute process transition context before modifying'
complete -c runcon -s t -l type -d 'type (for same role as parent)'
complete -c runcon -s u -l user -d 'user identity'
complete -c runcon -s r -l role -d role
complete -c runcon -s l -l range -d levelrange
complete -c runcon -l help -d 'display this help and exit'
complete -c runcon -l version -d 'output version information and exit AUTHOR Written by Russell Coker'

