# runuser
# Autogenerated from man page /usr/share/man/man1/runuser.1.gz
complete -c runuser -s c -l command
complete -c runuser -s f -l fast
complete -c runuser -s g -l group
complete -c runuser -s G -l supp-group
complete -c runuser -s l -l login
complete -c runuser -s P -l pty
complete -c runuser -s m -s p -l preserve-environment
complete -c runuser -s s -l shell
complete -c runuser -l session-command
complete -c runuser -s w -l whitelist-environment
complete -c runuser -s V -l version
complete -c runuser -s h -l help

