# runxlrd
# Autogenerated from man page /usr/share/man/man1/runxlrd.1.gz
complete -c runxlrd -s h -l help -d 'Show summary of options and exit. \\"'
complete -c runxlrd -s v -l version -d '\\" Show version of program'
complete -c runxlrd -s l -d 'Contains error messages'
complete -c runxlrd -l verbosity -d 'Level of information and diagnostics provided'
complete -c runxlrd -s m -l mmap -d '1: use mmap; 0: don\'t use mmap; -1: accept heuristic'
complete -c runxlrd -s e -l encoding -d 'Encoding override'
complete -c runxlrd -s f -l formatting -d '0 (default): no fmt info 1: fmt info (all cells) 2: fmt info (margins trimmed)'
complete -c runxlrd -s g -l gc -d '0: auto gc enabled; 1: auto gc disabled, manual collect after each file; 2: n…'
complete -c runxlrd -s s -l onesheet -d 'Restrict output to this sheet (name or index)'

