# sbkeysync
# Autogenerated from man page /usr/share/man/man1/sbkeysync.1.gz
complete -c sbkeysync -l efivars-path -d 'Path to efivars mountpoint (or regular directory for testing)'
complete -c sbkeysync -l verbose -d 'Print verbose progress information'
complete -c sbkeysync -l dry-run -d 'Don\'t update firmware key databases'
complete -c sbkeysync -l pk -d 'Set PK'
complete -c sbkeysync -l keystore -d 'Read keys from <dir>/{db,dbx,KEK}/* (can be specified multiple times, first d…'
complete -c sbkeysync -l no-default-keystores -d 'Don\'t read keys from the default'

