# sbsign
# Autogenerated from man page /usr/share/man/man1/sbsign.1.gz
complete -c sbsign -l engine -d 'use the specified engine to load the key'
complete -c sbsign -l key -d 'signing key (PEM-encoded RSA private key)'
complete -c sbsign -l cert -d 'certificate (x509 certificate) '
complete -c sbsign -l detached -d 'write a detached signature, instead of a signed binary'
complete -c sbsign -l addcert
complete -c sbsign -l output -d 'write signed data to <file> (default <efi-boot-image>'

