# sbvarsign
# Autogenerated from man page /usr/share/man/man1/sbvarsign.1.gz
complete -c sbvarsign -l engine -d 'use the specified engine to load the key'
complete -c sbvarsign -l key -d 'signing key (PEM-encoded RSA private key)'
complete -c sbvarsign -l cert -d 'certificate (x509 certificate)'
complete -c sbvarsign -l include-attrs -d 'include attrs at beginning of output file'
complete -c sbvarsign -l guid -d 'EFI GUID for the variable'
complete -c sbvarsign -l attr -d 'variable attributes'
complete -c sbvarsign -l output -d 'write signed data to <file> (default <var-data-file>. signed)'

