# sbverify
# Autogenerated from man page /usr/share/man/man1/sbverify.1.gz
complete -c sbverify -l cert -d 'certificate (x509 certificate)'
complete -c sbverify -l list -d 'list all signatures (but don\'t verify)'
complete -c sbverify -l detached -d 'read signature from <file>, instead of looking for an embedded signature'

