# script
# Autogenerated from man page /usr/share/man/man1/script.1.gz
complete -c script -s a -l append
complete -c script -s c -l command
complete -c script -s E -l echo
complete -c script -s e -l return
complete -c script -s f -l flush
complete -c script -l force
complete -c script -s B -l log-io
complete -c script -s I -l log-in
complete -c script -s O -l log-out
complete -c script -s T -l log-timing
complete -c script -s m -l logging-format
complete -c script -s o -l output-limit
complete -c script -s q -l quiet
complete -c script -s t -l timing
complete -c script -s V -l version
complete -c script -s h -l help

