# scriptlive
# Autogenerated from man page /usr/share/man/man1/scriptlive.1.gz
complete -c scriptlive -s I -l log-in
complete -c scriptlive -s B -l log-io
complete -c scriptlive -s t -l timing
complete -c scriptlive -s T -l log-timing
complete -c scriptlive -s d -l divisor
complete -c scriptlive -s m -l maxdelay
complete -c scriptlive -s V -l version
complete -c scriptlive -s h -l help

