# see
# Autogenerated from man page /usr/share/man/man1/see.1.gz
complete -c see -l action -d 'Performs the specified action on the files'
complete -c see -l debug -d 'Turns on extra information to find out what is happening'
complete -c see -l nopager -d 'Ignores any "copiousoutput" directive and sends output to STDOUT'
complete -c see -l norun -d 'Displays the found command without actually executing it'

