# sensors
# Autogenerated from man page /usr/share/man/man1/sensors.1.gz
complete -c sensors -s c -l config-file -d 'Specify a configuration file'
complete -c sensors -s h -l help -d 'Print a help text and exit'
complete -c sensors -s s -l set -d 'Evaluate all `set\' statements in the configuration file and exit'
complete -c sensors -s A -l no-adapter -d 'Do not show the adapter for each chip'
complete -c sensors -s u -d 'Raw output'
complete -c sensors -s j -d 'Json output'
complete -c sensors -s v -l version -d 'Print the program version and exit'
complete -c sensors -s f -l fahrenheit -d 'Print the temperatures in degrees Fahrenheit instead of Celsius'
complete -c sensors -l bus-list -d 'Generate bus statements suitable for using in sensors. conf'

