# sessreg
# Autogenerated from man page /usr/share/man/man1/sessreg.1.gz
complete -c sessreg -s w -d 'This specifies an alternate wtmpx file, instead of  "/var/log/wtmp" '
complete -c sessreg -s u -d 'This specifies an alternate utmpx file, instead of  "/var/run/utmp" '
complete -c sessreg -s L -d 'This specifies an alternate lastlog file, instead of  "/var/log/lastlog" , if…'
complete -c sessreg -s l -d 'This describes the "line" name of the entry'
complete -c sessreg -s h -d 'This is set to indicate that the session was initiated from a remote host'
complete -c sessreg -s s -d '\\" __BEGIN_UTMPX_ONLY__ This option is accepted for compatibility, but does n…'
complete -c sessreg -s x -d '\\" __BEGIN_UTMPX_ONLY__ This option is accepted for compatibility, but does n…'
complete -c sessreg -s t -d '\\" __BEGIN_UTMPX_ONLY__ This option is accepted for compatibility, but does n…'
complete -c sessreg -s V -d 'This option causes the command to print its version and exit'
complete -c sessreg -s a -d 'This session should be added to utmpx/wtmpx'
complete -c sessreg -s d -d 'This session should be deleted from utmpx/wtmpx'

