# setcap
# Autogenerated from man page /usr/share/man/man8/setcap.8.gz
complete -c setcap -s v -d '(verify) option setcap sets the capabilities of each specified filename to th…'
complete -c setcap -s n -d 'argument can be used to set the file capability for use only in a user namesp…'
complete -c setcap -s q -d 'flag is used to make the program less verbose in its output'

