# setfacl
# Autogenerated from man page /usr/share/man/man1/setfacl.1.gz
complete -c setfacl -s b -l remove-all -d 'Remove all extended ACL entries'
complete -c setfacl -s k -l remove-default -d 'Remove the Default ACL.  If no Default ACL exists, no warnings are issued'
complete -c setfacl -s n -l no-mask -d 'Do not recalculate the effective rights mask'
complete -c setfacl -l mask -d 'Do recalculate the effective rights mask, even if an ACL mask entry was expli…'
complete -c setfacl -s d -l default -d 'All operations apply to the Default ACL'
complete -c setfacl -l restore -d 'Restore a permission backup created by `getfacl -R\' or similar'
complete -c setfacl -l test -d 'Test mode'
complete -c setfacl -s R -l recursive -d 'Apply operations to all files and directories recursively'
complete -c setfacl -s L -l logical -d 'Logical walk, follow symbolic links to directories'
complete -c setfacl -s P -l physical -d 'Physical walk, do not follow symbolic links to directories'
complete -c setfacl -s v -l version -d 'Print the version of setfacl and exit'
complete -c setfacl -s h -l help -d 'Print help explaining the command line options'
complete -c setfacl -s m -d and
complete -c setfacl -s x -d 'options expect an ACL on the command line'
complete -c setfacl -s M -d and
complete -c setfacl -s X -d 'options read an ACL from a file or from standard input'
complete -c setfacl -l set -l set-file -d 'options set the ACL of a file or a directory.  The previous ACL is replaced'
complete -c setfacl -l modify -l modify-file -d 'options modify the ACL of a file or directory'
complete -c setfacl -l remove -l remove-file -d 'options remove ACL entries'

