# setmetamode
# Autogenerated from man page /usr/share/man/man1/setmetamode.1.gz
complete -c setmetamode -s C -l console -d 'the console device to be used;'
complete -c setmetamode -s V -l version -d 'print version number;'
complete -c setmetamode -s h -l help -d 'print this usage message.  SEE ALSO loadkeys (1), kbdinfo (1)'

