# setpriv
# Autogenerated from man page /usr/share/man/man1/setpriv.1.gz
complete -c setpriv -l clear-groups
complete -c setpriv -s d -l dump
complete -c setpriv -l groups
complete -c setpriv -l inh-caps -l ambient-caps -l bounding-set
complete -c setpriv -l keep-groups
complete -c setpriv -l init-groups
complete -c setpriv -l list-caps
complete -c setpriv -l no-new-privs
complete -c setpriv -l rgid -l egid -l regid
complete -c setpriv -l ruid -l euid -l reuid
complete -c setpriv -l securebits
complete -c setpriv -l pdeathsig
complete -c setpriv -l selinux-label
complete -c setpriv -l apparmor-profile
complete -c setpriv -l reset-env
complete -c setpriv -s V -l version
complete -c setpriv -s h -l help

