# setpci
# Autogenerated from man page /usr/share/man/man8/setpci.8.gz
complete -c setpci -s v -d 'Tells  setpci to be verbose and display detailed information about configurat…'
complete -c setpci -s f -d 'Tells  setpci not to complain when there\'s nothing to do (when no devices are…'
complete -c setpci -s D -d '`Demo mode\' -- don\'t write anything to the configuration registers'
complete -c setpci -s r -d 'Avoids bus scan if each operation selects a specific device (uses the  -s sel…'
complete -c setpci -l version -d 'Show  setpci version.  This option should be used stand-alone'
complete -c setpci -l help -d 'Show detailed help on available options'
complete -c setpci -l dumpregs -d 'Show a list of all known PCI registers and capabilities'
complete -c setpci -s A -d 'The library supports a variety of methods to access the PCI hardware'
complete -c setpci -s O -d 'The behavior of the library is controlled by several named parameters'
complete -c setpci -o H1 -d 'Use direct hardware access via Intel configuration mechanism 1'
complete -c setpci -o H2 -d 'Use direct hardware access via Intel configuration mechanism 2'
complete -c setpci -s s -d 'selector with specific domain, bus, slot, and function)'
complete -c setpci -s G -d 'Increase debug level of the library'
complete -c setpci -s d -d 'Select devices with specified vendor and device ID'

