# setvtrgb
# Autogenerated from man page /usr/share/man/man8/setvtrgb.8.gz
complete -c setvtrgb -s C -l console -d 'the console device to be used;'
complete -c setvtrgb -s h -l help -d 'Prints usage message and exits'
complete -c setvtrgb -s V -l version -d 'Prints version number and exists'

