# sha224sum
# Autogenerated from man page /usr/share/man/man1/sha224sum.1.gz
complete -c sha224sum -s b -l binary -d 'read in binary mode'
complete -c sha224sum -s c -l check -d 'read SHA224 sums from the FILEs and check them'
complete -c sha224sum -l tag -d 'create a BSD-style checksum'
complete -c sha224sum -s t -l text -d 'read in text mode (default)'
complete -c sha224sum -s z -l zero -d 'end each output line with NUL, not newline, and disable file name escaping '
complete -c sha224sum -l ignore-missing -d 'don\'t fail or report status for missing files'
complete -c sha224sum -l quiet -d 'don\'t print OK for each successfully verified file'
complete -c sha224sum -l status -d 'don\'t output anything, status code shows success'
complete -c sha224sum -l strict -d 'exit non-zero for improperly formatted checksum lines'
complete -c sha224sum -s w -l warn -d 'warn about improperly formatted checksum lines'
complete -c sha224sum -l help -d 'display this help and exit'
complete -c sha224sum -l version -d 'output version information and exit'

