# simple-scan
# Autogenerated from man page /usr/share/man/man1/simple-scan.1.gz
complete -c simple-scan -s d -l debug -d 'Print debugging messages'
complete -c simple-scan -s v -l version -d 'Show release version'
complete -c simple-scan -s '?' -l help -d 'Show help options'
complete -c simple-scan -l help-all -d 'Show all help options'
complete -c simple-scan -l help-gtk -d 'Show GTK+ options.  AUTHOR simple-scan was written by Robert Ancell <robert'

