# sleep
# Autogenerated from man page /usr/share/man/man1/sleep.1.gz
complete -c sleep -l help -d 'display this help and exit'
complete -c sleep -l version -d 'output version information and exit AUTHOR Written by Jim Meyering and Paul E…'

