# slick-greeter
# Autogenerated from man page /usr/share/man/man8/slick-greeter.8.gz
complete -c slick-greeter -s v -l version -d 'Show release version'
complete -c slick-greeter -l test-mode -d 'Run the greeter in a test mode inside the current X session'
complete -c slick-greeter -s '?' -l help -d 'Show help options.  Configuration File-Format /etc/lightdm/slick-greeter'

