# slxdecode
# Autogenerated from man page /usr/share/man/man1/slxdecode.1.gz
complete -c slxdecode -s d -d 'Basename of . pbm file for saving decompressed planes'
complete -c slxdecode -s r -d 'Basename of . jbg file for saving raw planes'
complete -c slxdecode -s h -d 'Print hex file offsets'
complete -c slxdecode -s o -d 'Print file offsets'
complete -c slxdecode -s D -d 'Set Debug level [0]'

