# snap-confine
# Autogenerated from man page /usr/share/man/man8/snap-confine.8.gz
complete -c snap-confine -l classic -d 'applications are not confined at all (like in classic systems, hence the name)'
complete -c snap-confine -l base -d 'filesystem.  If omitted it defaults to the core snap'

