# snice
# Autogenerated from man page /usr/share/man/man1/snice.1.gz
complete -c snice -s f -l fast -d 'Fast mode.   This option has not been implemented'
complete -c snice -s i -l interactive -d 'Interactive use.   You will be asked to approve each action'
complete -c snice -s l -l list -d 'List all signal names'
complete -c snice -s L -l table -d 'List all signal names in a nice table'
complete -c snice -s n -l no-action -d 'No action; perform a simulation of events that would occur but do not actuall…'
complete -c snice -s v -l verbose -d 'Verbose; explain what is being done'
complete -c snice -s w -l warnings -d 'Enable warnings.   This option has not been implemented'
complete -c snice -s h -l help -d 'Display help text and exit'
complete -c snice -s V -l version -d 'Display version information'
complete -c snice -s t -l tty -d 'The next expression is a terminal (tty or pty)'
complete -c snice -s u -l user -d 'The next expression is a username'
complete -c snice -s p -l pid -d 'The next expression is a process ID number'
complete -c snice -s c -l command -d 'The next expression is a command name'
complete -c snice -l ns -d 'Match the processes that belong to the same namespace as pid'
complete -c snice -l nslist -d 'list which namespaces will be considered for the --ns option'

