# software-properties-gtk
# Autogenerated from man page /usr/share/man/man1/software-properties-gtk.1.gz
complete -c software-properties-gtk -l debug -d 'Print some debug information to the command line'
complete -c software-properties-gtk -l massive-debug -d 'Print a lot of debug information to the command line'
complete -c software-properties-gtk -l no-update -d 'No update on repository change (useful if called from an external program)'
complete -c software-properties-gtk -l enable-component -d 'Enable the specified component of the distro\'s repositories [component_arg]'
complete -c software-properties-gtk -l open-tab -d 'Open specific tab number on startup'
complete -c software-properties-gtk -l enable-ppa -d 'Enable PPA with the given name [ppa_arg] . SS Generic options:'
complete -c software-properties-gtk -l help -d 'Show help about options'

