# sotruss
# Autogenerated from man page /usr/share/man/man1/sotruss.1.gz
complete -c sotruss -s F -l from -d 'Trace calls from objects on FROMLIST'
complete -c sotruss -s T -l to -d 'Trace calls to objects on TOLIST'
complete -c sotruss -s e -l exit -d 'Also show exits from the function calls'
complete -c sotruss -s f -l follow -d 'Trace child processes as they are created by currently traced processes as a …'
complete -c sotruss -s o -l output -d 'Write output to FILENAME (or FILENAME'
complete -c sotruss -s '?' -l help -d 'Give this help list'
complete -c sotruss -l usage -d 'Give a short usage message'
complete -c sotruss -l version -d 'Print program version AUTHOR Written by Ulrich Drepper'

