# speaker-test
# Autogenerated from man page /usr/share/man/man1/speaker-test.1.gz
complete -c speaker-test -s c -l channels -d 'NUM channels in stream'
complete -c speaker-test -s D -l device -d 'PCM device name NAME'
complete -c speaker-test -s f -l frequency -d 'sine wave of FREQ Hz'
complete -c speaker-test -l help -d 'Print usage help'
complete -c speaker-test -s b -l buffer -d 'Use buffer size of TIME microseconds'
complete -c speaker-test -s p -l period -d 'Use period size of TIME microseconds'
complete -c speaker-test -s P -l nperiods -d 'Use number of periods.   The default value is 4'
complete -c speaker-test -s r -l rate -d 'stream of RATE Hz'
complete -c speaker-test -s t -l test -d '-t pink means use pink noise (default)'
complete -c speaker-test -s l -l nloops -d 'Specifies the number of loops.   Zero means to run infinitely'
complete -c speaker-test -s s -l speaker -d 'Do a single-shot speaker test for the given channel'
complete -c speaker-test -s w -l wavfile -d 'Use the given WAV file for the playback instead of pre-defined WAV files'
complete -c speaker-test -s W -l wavdir -d 'Specify the directory containing WAV files for playback'
complete -c speaker-test -s m -l chmap -d 'Pass the channel map to override'
complete -c speaker-test -s X -l force-frequency -d 'Allow supplied FREQ to be outside the default range of 30-8000Hz'

