# speech-dispatcher
# Autogenerated from man page /usr/share/man/man1/speech-dispatcher.1.gz
complete -c speech-dispatcher -s d -l run-daemon -d 'Run as a daemon'
complete -c speech-dispatcher -s s -l run-single -d 'Run as single application'
complete -c speech-dispatcher -s a -l spawn -d 'Start only if autospawn is not disabled'
complete -c speech-dispatcher -s l -l log-level -d 'Set log level (between 1 and 5)'
complete -c speech-dispatcher -s L -l log-dir -d 'Set path to logging'
complete -c speech-dispatcher -s c -l communication-method -d 'Communication method to use (\'unix_socket\' or \'inet_socket\')'
complete -c speech-dispatcher -s S -l socket-path -d 'Socket path to use for \'unix_socket\' method (filesystem path or \'default\')'
complete -c speech-dispatcher -s p -l port -d 'Specify a port number for \'inet_socket\' method'
complete -c speech-dispatcher -s t -l timeout -d 'Set time in seconds for the server to wait before it shuts down, if it has no…'
complete -c speech-dispatcher -s P -l pid-file -d 'Set path to pid file'
complete -c speech-dispatcher -s C -l config-dir -d 'Set path to configuration'
complete -c speech-dispatcher -s m -l module-dir -d 'Set path to modules'
complete -c speech-dispatcher -s v -l version -d 'Report version of this program'
complete -c speech-dispatcher -s D -l debug -d 'Output debugging information into \\,$TMPDIR/speechd-debug\\/ if TMPDIR is expo…'
complete -c speech-dispatcher -s h -l help -d 'Print this info'

