# ssh-keyscan
# Autogenerated from man page /usr/share/man/man1/ssh-keyscan.1.gz
complete -c ssh-keyscan -s 4 -d 'Force ssh-keyscan to use IPv4 addresses only'
complete -c ssh-keyscan -s 6 -d 'Force ssh-keyscan to use IPv6 addresses only'
complete -c ssh-keyscan -s c -d 'Request certificates from target hosts instead of plain keys'
complete -c ssh-keyscan -s D -d 'Print keys found as SSHFP DNS records'
complete -c ssh-keyscan -s f -d 'Read hosts or addrlist namelist pairs from file, one per line'
complete -c ssh-keyscan -s H -d 'Hash all hostnames and addresses in the output'
complete -c ssh-keyscan -s p -d 'Connect to port on the remote host'
complete -c ssh-keyscan -s T -d 'Set the timeout for connection attempts'
complete -c ssh-keyscan -s t -d 'Specify the type of the key to fetch from the scanned hosts'
complete -c ssh-keyscan -s v -d 'Verbose mode: print debugging messages about progress'

