# stdbuf
# Autogenerated from man page /usr/share/man/man1/stdbuf.1.gz
complete -c stdbuf -s i -l input -d 'adjust standard input stream buffering'
complete -c stdbuf -s o -l output -d 'adjust standard output stream buffering'
complete -c stdbuf -s e -l error -d 'adjust standard error stream buffering'
complete -c stdbuf -l help -d 'display this help and exit'
complete -c stdbuf -l version -d 'output version information and exit'

