# strace-log-merge
# Autogenerated from man page /usr/share/man/man1/strace-log-merge.1.gz
complete -c strace-log-merge -l help -d 'Show program usage and exit'
complete -c strace-log-merge -o ttt -d 'option in the respective strace invocation should solve the problem'

