# su
# Autogenerated from man page /usr/share/man/man1/su.1.gz
complete -c su -s c -l command
complete -c su -s f -l fast
complete -c su -s g -l group
complete -c su -s G -l supp-group
complete -c su -s l -l login
complete -c su -s m -s p -l preserve-environment
complete -c su -s P -l pty
complete -c su -s s -l shell
complete -c su -l session-command
complete -c su -s w -l whitelist-environment
complete -c su -s V -l version
complete -c su -s h -l help

