# sulogin
# Autogenerated from man page /usr/share/man/man8/sulogin.8.gz
complete -c sulogin -s e -l force
complete -c sulogin -s p -l login-shell
complete -c sulogin -s t -l timeout
complete -c sulogin -s h -l help
complete -c sulogin -s V -l version

