# swapon
# Autogenerated from man page /usr/share/man/man8/swapon.8.gz
complete -c swapon -s a -l all
complete -c swapon -s d -l discard
complete -c swapon -s e -l ifexists
complete -c swapon -s f -l fixpgsz
complete -c swapon -s h -l help
complete -c swapon -s L
complete -c swapon -s o -l options
complete -c swapon -s p -l priority
complete -c swapon -s s -l summary
complete -c swapon -l show
complete -c swapon -l output-all
complete -c swapon -l noheadings
complete -c swapon -l raw
complete -c swapon -l bytes
complete -c swapon -s U
complete -c swapon -s v -l verbose
complete -c swapon -s V -l version

