# sxw2txt
# Autogenerated from man page /usr/share/man/man1/sxw2txt.1.gz
complete -c sxw2txt -l width -d 'Wrap text lines after WIDTH characters'
complete -c sxw2txt -l output -d 'Write output to FILE and not to standard output'
complete -c sxw2txt -l subst -d 'Select which non-ascii characters shall be replaced by ascii look-a-likes'
complete -c sxw2txt -l encoding -d 'Do not try to autodetect the terminal encoding, but convert the document to e…'
complete -c sxw2txt -l raw -d 'Print raw XML'
complete -c sxw2txt -l version -d 'Show version and copyright information COPYRIGHT Copyright © 2006,2007 Dennis…'

