# systemd-bless-boot
# Autogenerated from man page /usr/share/man/man8/systemd-bless-boot.8.gz
complete -c systemd-bless-boot -s h -l help -d 'Print a short help text and exit'
complete -c systemd-bless-boot -l version -d 'Print a short version string and exit'

