# systemd-ask-password-console
# Autogenerated from man page /usr/share/man/man8/systemd-ask-password-console.path.8.gz
complete -c systemd-ask-password-console -l watch -l console -d or
complete -c systemd-ask-password-console -l wall -d 'command line parameters.  SEE ALSO'

