# systemd-hybrid-sleep
# Autogenerated from man page /usr/share/man/man8/systemd-hybrid-sleep.service.8.gz
complete -c systemd-hybrid-sleep -s h -l help -d 'Print a short help text and exit'
complete -c systemd-hybrid-sleep -l version -d 'Print a short version string and exit'

