# system-config-printer-applet
# Autogenerated from man page /usr/share/man/man1/system-config-printer-applet.1.gz
complete -c system-config-printer-applet -l help -d 'Display a short usage message'
complete -c system-config-printer-applet -l version -d 'Display the version of the applet'
complete -c system-config-printer-applet -l debug -d 'Show debugging information'
complete -c system-config-printer-applet -l no-tray-icon -d 'option: a desktop file is provided for this, so that it should appear in the …'

