# systemd-escape
# Autogenerated from man page /usr/share/man/man1/systemd-escape.1.gz
complete -c systemd-escape -l suffix -d 'Appends the specified unit type suffix to the escaped string'
complete -c systemd-escape -l template -d 'Inserts the escaped strings in a unit name template'
complete -c systemd-escape -l path -s p -d 'When escaping or unescaping a string, assume it refers to a file system path'
complete -c systemd-escape -l unescape -s u -d 'Instead of escaping the specified strings, undo the escaping, reversing the o…'
complete -c systemd-escape -l mangle -s m -d 'Like --escape, but only escape characters that are obviously not escaped yet,…'
complete -c systemd-escape -l instance -d 'With --unescape, unescape and print only the instance part of an instantiated…'
complete -c systemd-escape -s h -l help -d 'Print a short help text and exit'
complete -c systemd-escape -l version -d 'Print a short version string and exit'
complete -c systemd-escape -l escape

