# systemd-suspend
# Autogenerated from man page /usr/share/man/man8/systemd-suspend.service.8.gz
complete -c systemd-suspend -s h -l help -d 'Print a short help text and exit'
complete -c systemd-suspend -l version -d 'Print a short version string and exit'

