# systemd-hibernate
# Autogenerated from man page /usr/share/man/man8/systemd-hibernate.service.8.gz
complete -c systemd-hibernate -s h -l help -d 'Print a short help text and exit'
complete -c systemd-hibernate -l version -d 'Print a short version string and exit'

