# systemd-journald-dev-log
# Autogenerated from man page /usr/share/man/man8/systemd-journald-dev-log.socket.8.gz
complete -c systemd-journald-dev-log -l namespace -d 'switch of journalctl(1) may be used to view the log stream of a specific name…'

