# systemd-tmpfiles
# Autogenerated from man page /usr/share/man/man8/systemd-tmpfiles.8.gz
complete -c systemd-tmpfiles -l create -d 'If this option is passed, all files and directories marked with f, F, w, d, D…'
complete -c systemd-tmpfiles -l clean -d 'If this option is passed, all files and directories with an age parameter con…'
complete -c systemd-tmpfiles -l remove -d 'If this option is passed, the contents of directories marked with D or R, and…'
complete -c systemd-tmpfiles -l user -d 'Execute "user" configuration, i. e.  tmpfiles'
complete -c systemd-tmpfiles -l boot -d 'Also execute lines with an exclamation mark'
complete -c systemd-tmpfiles -l prefix -d 'Only apply rules with paths that start with the specified prefix'
complete -c systemd-tmpfiles -l exclude-prefix -d 'Ignore rules with paths that start with the specified prefix'
complete -c systemd-tmpfiles -s E -d 'A shortcut for "--exclude-prefix=/dev --exclude-prefix=/proc --exclude-prefix…'
complete -c systemd-tmpfiles -l root -d 'Takes a directory path as an argument'
complete -c systemd-tmpfiles -l image -d 'Takes a path to a disk image file or block device node'
complete -c systemd-tmpfiles -l replace -d 'When this option is given, one ore more positional arguments must be specified'
complete -c systemd-tmpfiles -l cat-config -d 'Copy the contents of config files to standard output'
complete -c systemd-tmpfiles -l no-pager -d 'Do not pipe output into a pager'
complete -c systemd-tmpfiles -s h -l help -d 'Print a short help text and exit'
complete -c systemd-tmpfiles -l version -d 'Print a short version string and exit'

