# systemd-id128
# Autogenerated from man page /usr/share/man/man1/systemd-id128.1.gz
complete -c systemd-id128 -s p -l pretty -d 'Generate output as programming language snippets'
complete -c systemd-id128 -s a -l app-specific -d 'With this option, an identifier that is the result of hashing the application…'
complete -c systemd-id128 -s u -l uuid -d 'Generate output as an UUID formatted in the "canonical representation", with …'
complete -c systemd-id128 -s h -l help -d 'Print a short help text and exit'
complete -c systemd-id128 -l version -d 'Print a short version string and exit'

