# systemd-sleep
# Autogenerated from man page /usr/share/man/man8/systemd-sleep.8.gz
complete -c systemd-sleep -s h -l help -d 'Print a short help text and exit'
complete -c systemd-sleep -l version -d 'Print a short version string and exit'

