# t1asm
# Autogenerated from man page /usr/share/man/man1/t1asm.1.gz
complete -c t1asm -l pfa -s a -d 'Output in PFA (ASCII) format'
complete -c t1asm -l pfb -s b -d 'Output in PFB (binary) format.  This is the default'
complete -c t1asm -l block-length -s l -d 'PFB only: Set the maximum output block length to  num'
complete -c t1asm -l line-length -d 'PFA only: Set the maximum length of encrypted lines in the output to num'

