# t1mac
# Autogenerated from man page /usr/share/man/man1/t1mac.1.gz
complete -c t1mac -l raw -s r -d 'Indicates that output should be a raw resource fork'
complete -c t1mac -l macbinary -d 'Indicates that output should be in MacBinary I or II format'
complete -c t1mac -l applesingle -d 'Indicates that output should be in AppleSingle format'
complete -c t1mac -l appledouble -d 'Indicates that output should be in AppleDouble format'
complete -c t1mac -l binhex -d 'Indicates that output should be in BinHex 4. 0 format'
complete -c t1mac -l filename -s n -d 'Sets the Macintosh filename of the output font to name'

