# tabs
# Autogenerated from man page /usr/share/man/man1/tabs.1.gz
complete -c tabs -s T -d 'Tell tabs which terminal type to use'
complete -c tabs -s d -d 'The debugging option shows a ruler line, followed by two data lines'
complete -c tabs -s n -d 'This option tells tabs to check the options and run any debugging option, but…'
complete -c tabs -s V -d 'reports the version of ncurses which was used in this program, and exits'
complete -c tabs -s a -d 'Assembler, IBM S/370, first format . br 1,10,16,36,72'
complete -c tabs -o a2 -d 'Assembler, IBM S/370, second format . br 1,10,16,40,72'
complete -c tabs -s c -d 'COBOL, normal format . br 1,8,12,16,20,55'
complete -c tabs -o c2 -d 'COBOL compact format . br 1,6,10,14,49'
complete -c tabs -o c3 -d 'COBOL compact format extended '
complete -c tabs -s f -d 'FORTRAN . br 1,7,11,15,19,23'
complete -c tabs -s p -d 'PL/I . br 1,5,9,13,17,21,25,29,33,37,41,45,49,53,57,61'
complete -c tabs -s s -d 'SNOBOL . br 1,10,55'
complete -c tabs -s u -d 'UNIVAC 1100 Assembler . br 1,12,20,44 '

