# tac
# Autogenerated from man page /usr/share/man/man1/tac.1.gz
complete -c tac -s b -l before -d 'attach the separator before instead of after'
complete -c tac -s r -l regex -d 'interpret the separator as a regular expression'
complete -c tac -s s -l separator -d 'use STRING as the separator instead of newline'
complete -c tac -l help -d 'display this help and exit'
complete -c tac -l version -d 'output version information and exit AUTHOR Written by Jay Lepreau and David M…'

