# tc
# Autogenerated from man page /usr/share/man/man8/tc.8.gz
complete -c tc -s b -s b -o batch -o batch -d 'read commands from provided file or standard input and invoke them'
complete -c tc -o force -d 'don\'t terminate tc on errors in batch mode'
complete -c tc -s o -o oneline -d 'output each record on a single line, replacing line feeds with the  \'\' charac…'
complete -c tc -s n -o net -o netns -d 'switches  tc to the specified network namespace R NETNS '
complete -c tc -s N -o Numeric -d 'Print the number of protocol, scope, dsfield, etc directly instead of convert…'
complete -c tc -o cf -o conf -d 'specifies path to the config file'
complete -c tc -s t -o timestamp -d 'Whentc monitorruns, print timestamp before the event message in format:    Ti…'
complete -c tc -s s
complete -c tc -s d
complete -c tc -s r
complete -c tc -s i
complete -c tc -s g
complete -c tc -s j
complete -c tc -s p
complete -c tc -o col
complete -c tc -o nm
complete -c tc -o ts -o tshort -d 'When tc monitor runs, prints short timestamp before the event message in form…'
complete -c tc -o stats -o statistics -d 'output more statistics about packet usage'
complete -c tc -o details -d 'output more detailed information about rates and cell sizes'
complete -c tc -o raw -d 'output raw hex values for handles'
complete -c tc -o pretty -d 'for u32 filter, decode offset and mask values to equivalent filter commands b…'
complete -c tc -o iec -d 'print rates in IEC units (ie.  1K = 1024)'
complete -c tc -o graph -d 'shows classes as ASCII graph.  Prints generic stats info under each class if'
complete -c tc -s c -d 'Configure color output'
complete -c tc -o json -d 'is also given'
complete -c tc -o name -d 'resolve class name from /etc/iproute2/tc_cls file or from file specified by'
complete -c tc -o br -o brief -d 'Print only essential data needed to identify the filter and action (handle, c…'

