# texdoc
# Autogenerated from man page /usr/share/man/man1/texdoc.1.gz
complete -c texdoc -s w -l view -d 'Use view mode: start a viewer.  (default) '
complete -c texdoc -s m -l mixed -d 'Use mixed mode (view or list)'
complete -c texdoc -s l -l list -d 'Use list mode: show a list of results'
complete -c texdoc -s s -l showall -d 'Use showall mode: show also "bad" results'
complete -c texdoc -s i -l interact -d 'Use interactive menus.  (default) '
complete -c texdoc -s I -l nointeract -d 'Use plain lists, no interaction required'
complete -c texdoc -s M -l machine -d 'Machine-readable output for lists (implies -I)'
complete -c texdoc -s q -l quiet -d 'Suppress warnings and most error messages'
complete -c texdoc -s v -l verbose -d 'Print additional information (e. g. , viewer command)'
complete -c texdoc -s D -l debug -d 'Activate all debug output (equal to "--debug=all")'
complete -c texdoc -s d -d 'Activate debug output restricted to the categories specified in LIST'

