# texhash
# Autogenerated from man page /usr/share/man/man1/texhash.1.gz
complete -c texhash -l help -d 'Print help message and exit'
complete -c texhash -l version -d 'Print version information and exit'

