# tftopl
# Autogenerated from man page /usr/share/man/man1/tftopl.1.gz
complete -c tftopl -o charcode-format -d 'The argument  format specifies how character codes are output in the PL file'
complete -c tftopl -o verbose -d 'Without this option, tftopl operates silently'

