# thermald
# Autogenerated from man page /usr/share/man/man8/thermald.8.gz
complete -c thermald -s h -l help -d 'Show help options'
complete -c thermald -l version -d 'Print thermald version and exit'
complete -c thermald -l no-daemon -d 'Don\'t become a daemon: Default is daemon mode'
complete -c thermald -l loglevel -d 'log severity: info level and up'
complete -c thermald -l poll-interval -d 'Poll interval in seconds: Poll for zone temperature changes'
complete -c thermald -l dbus-enable -d 'Enable Dbus'
complete -c thermald -l exclusive-control -d 'Act as exclusive thermal controller'
complete -c thermald -l ignore-cpuid-check -d 'Ignore cpuid check for supported CPU models'
complete -c thermald -l config-file -d 'Specify thermal-conf. xml path and ignore default thermal-conf. xml'
complete -c thermald -l ignore-default-control -d 'Ignore default CPU temperature control.  Strictly follow thermal-conf'
complete -c thermald -l workaround-enabled -d 'Enable special workarounds for RAPL MMIO power limit and TCC offset every 30 …'
complete -c thermald -l disable-active-power -d 'Disable active power management'
complete -c thermald -l adaptive -d 'Use DPTF adaptive tables when present'
complete -c thermald -l test-mode -d 'Force use adaptive mode and exit if not supported, instead of restarting in n…'
complete -c thermald -l systemd -d 'Assume that thermald is started by systemd'
complete -c thermald -l ignore-critical-trip -d 'If the configuration defined a critical temperature point, which is too low, …'

