# timeout
# Autogenerated from man page /usr/share/man/man1/timeout.1.gz
complete -c timeout -s v -l verbose -d 'diagnose to stderr any signal sent upon timeout'
complete -c timeout -l help -d 'display this help and exit'
complete -c timeout -l preserve-status -d 'exit with the same status as COMMAND, even when the command times out'
complete -c timeout -l foreground -d 'when not running timeout directly from a shell prompt, allow COMMAND to read …'
complete -c timeout -s k -l kill-after -d 'also send a KILL signal if COMMAND is still running this long after the initi…'
complete -c timeout -s s -l signal -d 'specify the signal to be sent on timeout; SIGNAL may be a name like \'HUP\' or …'
complete -c timeout -l version -d 'output version information and exit'

