# timedatectl
# Autogenerated from man page /usr/share/man/man1/timedatectl.1.gz
complete -c timedatectl -l no-ask-password -d 'Do not query the user for authentication for privileged operations'
complete -c timedatectl -l adjust-system-clock -d 'If set-local-rtc is invoked and this option is passed, the system clock is sy…'
complete -c timedatectl -l monitor -d 'If timesync-status is invoked and this option is passed, then timedatectl mon…'
complete -c timedatectl -s a -l all -d 'When showing properties of systemd-timesyncd'
complete -c timedatectl -s p -l property -d 'When showing properties of systemd-timesyncd'
complete -c timedatectl -l value -d 'When printing properties with show-timesync, only print the value, and skip t…'
complete -c timedatectl -s H -l host -d 'Execute the operation remotely'
complete -c timedatectl -s M -l machine -d 'Execute operation on a local container'
complete -c timedatectl -s h -l help -d 'Print a short help text and exit'
complete -c timedatectl -l version -d 'Print a short version string and exit'
complete -c timedatectl -l no-pager -d 'Do not pipe output into a pager'

