# toe
# Autogenerated from man page /usr/share/man/man1/toe.1.gz
complete -c toe -s a -d 'report on all of the terminal databases which ncurses would search, rather th…'
complete -c toe -s s -d 'sort the output by the entry names'
complete -c toe -s u -d 'says to write a report to the standard output, listing dependencies in the gi…'
complete -c toe -s U -d 'says to write a report to the standard output, listing reverse dependencies i…'
complete -c toe -o vn -d 'specifies that (verbose) output be written to standard error, showing toe\'s p…'
complete -c toe -s V -d 'reports the version of ncurses which was used in this program, and exits'
complete -c toe -l '>'
complete -c toe -l '-->' -d '*-+-:	9term     	Plan9 terminal emulator for X *---:	Eterm     	Eterm with xt…'

