# touch
# Autogenerated from man page /usr/share/man/man1/touch.1.gz
complete -c touch -s a -d 'change only the access time'
complete -c touch -s c -l no-create -d 'do not create any files'
complete -c touch -s d -l date -d 'parse STRING and use it instead of current time'
complete -c touch -s f -d '(ignored)'
complete -c touch -s h -l no-dereference -d 'affect each symbolic link instead of any referenced file (useful only on syst…'
complete -c touch -s m -d 'change only the modification time'
complete -c touch -s r -l reference -d 'use this file\'s times instead of current time'
complete -c touch -s t -d 'use [[CC]YY]MMDDhhmm[. ss] instead of current time'
complete -c touch -l time -d 'change the specified time: WORD is access, atime, or use: equivalent to -a WO…'
complete -c touch -l help -d 'display this help and exit'
complete -c touch -l version -d 'output version information and exit'

