# transicc
# Autogenerated from man page /usr/share/man/man1/transicc.1.gz
complete -c transicc -s '%' -d 'use percent % of ink'
complete -c transicc -s b -d 'Black point compensation'
complete -c transicc -s c -d 'Precalculates transform'
complete -c transicc -s i -d 'Input profile (defaults to sRGB)'
complete -c transicc -s l -d 'Transform by device-link profile'
complete -c transicc -s n -d 'Terse output, intended for pipe usage'
complete -c transicc -s t -d 'Intent (0=Perceptual, 1=Colorimetric, 2=Saturation, 3=Absolute)'
complete -c transicc -s v -d Verbose
complete -c transicc -s w -d 'Use 16 bits'
complete -c transicc -s x -d Hexadecimal
complete -c transicc -s o

