# transset
# Autogenerated from man page /usr/share/man/man1/transset.1.gz
complete -c transset -o display -d 'This option specifies the server to use; see X(7). PP'
complete -c transset -s h -l help -d 'This option displays a help message and exits. PP'
complete -c transset -s t -l toggle -d 'This option forces a toggle of opacity'
complete -c transset -s c -l click -d 'This option selects the target window by waiting for the user to click the mo…'
complete -c transset -s p -l point -d 'This option selects the window currently under the cursor to be the target'
complete -c transset -s a -l actual -d 'This option selects the window that currently has input focus to be the target'
complete -c transset -s n -l name -d 'This option selects the target window by name, where name is matched as a reg…'
complete -c transset -l no-regex -d 'This option disables treating the name argument to --name as a regular expres…'
complete -c transset -s i -l id -d 'This option selects the target window by window id. PP'
complete -c transset -l inc -d 'This option increases the window opacity by the given opacity argument. PP'
complete -c transset -l dec -d 'This option decreases the window opacity by the given opacity argument. PP'
complete -c transset -s m -l min -d 'This option sets the minimum possible opacity value'
complete -c transset -s x -l max -d 'This option sets the maximum possible opacity value'
complete -c transset -s v -l verbose -d 'This option prints some additional debug info as the program operates. PP'
complete -c transset -s V -l version -d 'This option prints the program version number and exits'

