# transmission-gtk
# Autogenerated from man page /usr/share/man/man1/transmission-gtk.1.gz
complete -c transmission-gtk -s '?' -d 'Show help options'
complete -c transmission-gtk -s p -d 'Start with all torrents paused'
complete -c transmission-gtk -s m -d 'Start minimized in notification area'
complete -c transmission-gtk -s g -d 'Where to look for configuration files'

