# tset
# Autogenerated from man page /usr/share/man/man1/tset.1.gz
complete -c tset -s c -d 'Set control characters and modes'
complete -c tset -s e -d 'Set the erase character to ch'
complete -c tset -s I -d 'Do not send the terminal or tab initialization strings to the terminal'
complete -c tset -s i -d 'Set the interrupt character to ch'
complete -c tset -s k -d 'Set the line kill character to ch'
complete -c tset -s m -d 'Specify a mapping from a port type to a terminal'
complete -c tset -s Q -d 'Do not display any values for the erase, interrupt and line kill characters'
complete -c tset -s q -d 'The terminal type is displayed to the standard output, and the terminal is no…'
complete -c tset -s r -d 'Print the terminal type to the standard error output'
complete -c tset -s s -d 'Print the sequence of shell commands to initialize the environment variable T…'
complete -c tset -s V -d 'reports the version of ncurses which was used in this program, and exits'
complete -c tset -s w -d 'Resize the window to match the size deduced via setupterm(3X)'
complete -c tset -s n -d 'This implementation does not provide that choice'

