# tsget
# Autogenerated from man page /usr/share/man/man1/tsget.1ssl.gz
complete -c tsget -s h -d 'The \\s-1URL\\s0 of the \\s-1HTTP/HTTPS\\s0 server listening for timestamp reques…'
complete -c tsget -s e -d 'If the -o option is not given this argument specifies the extension of the ou…'
complete -c tsget -s o -d 'This option can be specified only when just one request is sent to the server'
complete -c tsget -s v -d 'The name of the currently processed request is printed on standard error'
complete -c tsget -s d -d 'Switches on verbose mode for the underlying perl module WWW::Curl::Easy'
complete -c tsget -s k -d '(\\s-1HTTPS\\s0) In case of certificate-based client authentication over \\s-1HT…'
complete -c tsget -s p -d '(\\s-1HTTPS\\s0) Specifies the passphrase for the private key specified by the …'
complete -c tsget -s c -d '(\\s-1HTTPS\\s0) In case of certificate-based client authentication over \\s-1HT…'
complete -c tsget -s C -d '(\\s-1HTTPS\\s0) The trusted \\s-1CA\\s0 certificate store'
complete -c tsget -s P -d '(\\s-1HTTPS\\s0) The path containing the trusted \\s-1CA\\s0 certificates to veri…'
complete -c tsget -s r -d 'See \\*(L"Random State Options\\*(R" in openssl\\|(1) for more information'
complete -c tsget -s g -d 'The name of an \\s-1EGD\\s0 socket to get random data from.  (Optional)'

