# tsk_comparedir
# Autogenerated from man page /usr/share/man/man1/tsk_comparedir.1.gz
complete -c tsk_comparedir -s o -d 'Sector offset for a partition in the image or device to compare with'
complete -c tsk_comparedir -s n -d 'Starting inum for a directory in the image to start the comparison at'
complete -c tsk_comparedir -s v -d 'verbose output to stderr'
complete -c tsk_comparedir -s V -d 'Print version'
complete -c tsk_comparedir -s f -d 'Specify the file system type'
complete -c tsk_comparedir -s i -d 'The format of the image file, such as raw'
complete -c tsk_comparedir -s b -d 'The size (in bytes) of the device sectors'

