# tsk_gettimes
# Autogenerated from man page /usr/share/man/man1/tsk_gettimes.1.gz
complete -c tsk_gettimes -s v -d 'verbose output to stderr'
complete -c tsk_gettimes -s V -d 'Print version'
complete -c tsk_gettimes -s f -d 'Specify the file system type'
complete -c tsk_gettimes -s i -d 'The format of the image file, such as raw'
complete -c tsk_gettimes -s b -d 'The size (in bytes) of the device sectors'
complete -c tsk_gettimes -s o -d 'Sector offset for a volume to recover (recovers only that volume) If not give…'
complete -c tsk_gettimes -s s -d 'The time skew of the original system in seconds'
complete -c tsk_gettimes -s z -d 'The ASCII string of the time zone of the original system'

