# ttfdump
# Autogenerated from man page /usr/share/man/man1/ttfdump.1.gz
complete -c ttfdump -s h -d 'Print a help message on standard output and exit'
complete -c ttfdump -s t -d 'If this option is specified then dump the table "tablename", otherwise  dump …'
complete -c ttfdump -s g -d 'If this option is specified then dump the glyph with index glyphnumber,  othe…'
complete -c ttfdump -s c -d 'Select a TrueType font in a TrueType Collection'
complete -c ttfdump -s o -d 'Output of the dump.  If this option is not specified, dump to stdout'
complete -c ttfdump -s i -d 'TrueType font file to be dumped'

