# uclampset
# Autogenerated from man page /usr/share/man/man1/uclampset.1.gz
complete -c uclampset -s m
complete -c uclampset -s M
complete -c uclampset -s a -l all-tasks
complete -c uclampset -s p -l pid
complete -c uclampset -s s -l system
complete -c uclampset -s R -l reset-on-fork
complete -c uclampset -s v -l verbose
complete -c uclampset -s V -l version
complete -c uclampset -s h -l help

