# udisksd
# Autogenerated from man page /usr/share/man/man8/udisksd.8.gz
complete -c udisksd -l help -d 'Show help options'
complete -c udisksd -l replace -d 'Replace existing daemon'
complete -c udisksd -l debug -d 'Print debug or informational messages on stdout/stderr'
complete -c udisksd -l no-sigint -d 'Do not handle SIGINT for controlled shutdown'
complete -c udisksd -l force-load-modules -d 'Activate modules on startup'

