# ufw
# Autogenerated from man page /usr/share/man/man8/ufw.8.gz
complete -c ufw -l version -d 'show program\'s version number and exit'
complete -c ufw -s h -l help -d 'show help message and exit'
complete -c ufw -l dry-run -d 'don\'t modify anything, just show the changes'
complete -c ufw -l force
complete -c ufw -l add-new -d 'allow or deny so the update --add-new command may automatically update the fi…'

