# umount
# Autogenerated from man page /usr/share/man/man8/umount.8.gz
complete -c umount -s a -l all
complete -c umount -s A -l all-targets
complete -c umount -s c -l no-canonicalize
complete -c umount -s d -l detach-loop
complete -c umount -l fake
complete -c umount -s f -l force
complete -c umount -s i -l internal-only
complete -c umount -s l -l lazy
complete -c umount -s N -l namespace
complete -c umount -s n -l no-mtab
complete -c umount -s O -l test-opts
complete -c umount -s q -l quiet
complete -c umount -s R -l recursive
complete -c umount -s r -l read-only
complete -c umount -s t -l types
complete -c umount -s v -l verbose
complete -c umount -s V -l version
complete -c umount -s h -l help

