# unattended-upgrade
# Autogenerated from man page /usr/share/man/man8/unattended-upgrade.8.gz
complete -c unattended-upgrade -s h -l help -d 'help output'
complete -c unattended-upgrade -s d -l debug -d 'extra debug output into /var/log/unattended-upgrades/unattended-upgrades. log'
complete -c unattended-upgrade -l apt-debug -d 'detailed APT/LibAPT output for debugging'
complete -c unattended-upgrade -s v -l verbose -d 'show verbose output'
complete -c unattended-upgrade -l dry-run -d 'Just simulate installing updates, do not actually do it'
complete -c unattended-upgrade -l minimal-upgrade-steps -d 'perform upgrade in minimal steps (cancel with SIGINT)'
complete -c unattended-upgrade -l no-minimal-upgrade-steps -d 'do not perform upgrade in minimal steps'

