# unmkinitramfs
# Autogenerated from man page /usr/share/man/man8/unmkinitramfs.8.gz
complete -c unmkinitramfs -s h -d 'Display usage information and exit'
complete -c unmkinitramfs -s v -d 'Display verbose messages about extraction.  USAGE EXAMPLES'

