# unshare
# Autogenerated from man page /usr/share/man/man1/unshare.1.gz
complete -c unshare -s i -l ipc
complete -c unshare -s m -l mount
complete -c unshare -s n -l net
complete -c unshare -s p -l pid
complete -c unshare -s u -l uts
complete -c unshare -s U -l user
complete -c unshare -s C -l cgroup
complete -c unshare -s T -l time
complete -c unshare -s f -l fork
complete -c unshare -l keep-caps
complete -c unshare -l kill-child
complete -c unshare -l mount-proc
complete -c unshare -l map-user
complete -c unshare -l map-group
complete -c unshare -s r -l map-root-user
complete -c unshare -s c -l map-current-user
complete -c unshare -l propagation
complete -c unshare -l setgroups
complete -c unshare -s R -l root
complete -c unshare -s w -l wd
complete -c unshare -s S -l setuid
complete -c unshare -s G -l setgid
complete -c unshare -l monotonic
complete -c unshare -l boottime
complete -c unshare -s V -l version
complete -c unshare -s h -l help

