# update-catalog
# Autogenerated from man page /usr/share/man/man8/update-catalog.8.gz
complete -c update-catalog -l add -d 'Adds an entry for the  ordinary_catalog in the R centralized_catalog '
complete -c update-catalog -l remove -d 'Removes the entry for the  ordinary_catalog from the R centralized_catalog '
complete -c update-catalog -l update-super -d 'Regenerates the SGML super catalog from the contents of the R /etc/sgml direc…'
complete -c update-catalog -l quiet -d 'Prevents the usual diagnostic output'
complete -c update-catalog -l test -d 'Prevents the update of the catalog and writes the resulting SGML catalog to s…'
complete -c update-catalog -l version -d 'Displays the version information and exits'
complete -c update-catalog -l help -d 'Display the usage information and exits'

