# update-language-def
# Autogenerated from man page /usr/share/man/man8/update-language-def.8.gz
complete -c update-language-def -s c -l conf-file -d 'file giving additional hyphen specifications '
complete -c update-language-def -s d -l output-dir -d 'directory where files are written'
complete -c update-language-def -l checks -d 'perform sanity checks on the generated config file'
complete -c update-language-def -s q -l quiet -d 'don\'t write anything to the standard output during normal operation'
complete -c update-language-def -s h -s '?' -l help -d 'display this help message and exit'
complete -c update-language-def -s o -l output-file
complete -c update-language-def -l version -d 'output version information and exit FILES The default output directory is ,/v…'

