# update-mime-database
# Autogenerated from man page /usr/share/man/man1/update-mime-database.1.gz
complete -c update-mime-database -s h -d 'Print out a command summary'
complete -c update-mime-database -s v -d 'Print out the version information'
complete -c update-mime-database -s V -d 'Be verbose'
complete -c update-mime-database -s n -d 'Only update if MIME-DIR/packages/ or a file in that directory is newer than M…'

