# update-inetd
# Autogenerated from man page /usr/share/man/man1/update-inetd.1.gz
complete -c update-inetd -l group -d 'Specify that the new entry should be placed in group groupname (e. g'
complete -c update-inetd -l pattern -d 'This option can be used to select a service'
complete -c update-inetd -l comment-chars -d 'update-inetd uses "#<off># " as the default comment characters'
complete -c update-inetd -l multi -d 'If you want to disable/remove more than one entry at a time you should use th…'
complete -c update-inetd -l file -d 'Use filename instead of /etc/inetd. conf'
complete -c update-inetd -l verbose -d 'Explain what is being done'
complete -c update-inetd -l debug -d 'Enables debugging mode'
complete -c update-inetd -l help -d 'Print a usage message on standard output and exit successfully'

