# update-tl-stacked-conffile
# Autogenerated from man page /usr/share/man/man8/update-tl-stacked-conffile.8.gz
complete -c update-tl-stacked-conffile -l check -d 'Executes additional checks that all necessary files are present in the kpaths…'
complete -c update-tl-stacked-conffile -l quiet -d 'don\'t write anything to the standard output during normal operation'
complete -c update-tl-stacked-conffile -l help -d 'print a summary of the command-line usage of update-tl-stacked-conffile and e…'
complete -c update-tl-stacked-conffile -l version -d 'output version information and exit El Pp Note that the v option, which turns…'

