# uptime
# Autogenerated from man page /usr/share/man/man1/uptime.1.gz
complete -c uptime -s p -l pretty -d 'show uptime in pretty format'
complete -c uptime -s h -l help -d 'display this help text'
complete -c uptime -s s -l since -d 'system up since, in yyyy-mm-dd HH:MM:SS format'
complete -c uptime -s V -l version -d 'display version information and exit FILES'

