# useradd
# Autogenerated from man page /usr/share/man/man8/useradd.8.gz
complete -c useradd -l badname -d 'Allow names that do not conform to standards'
complete -c useradd -s b -l base-dirBASE_DIR -d 'The default base directory for the system if -dHOME_DIR is not specified'
complete -c useradd -s c -l commentCOMMENT -d 'Any text string'
complete -c useradd -s d -l home-dirHOME_DIR -d 'The new user will be created using HOME_DIR as the value for the user\\*(Aqs l…'
complete -c useradd -s D -l defaults -d 'See below, the subsection "Changing the default values"'
complete -c useradd -s e -l expiredateEXPIRE_DATE -d 'The date on which the user account will be disabled'
complete -c useradd -s f -l inactiveINACTIVE -d 'The number of days after a password expires until the account is permanently …'
complete -c useradd -s g -l gidGROUP -d 'The group name or number of the user\\*(Aqs initial login group'
complete -c useradd -s G -l groupsGROUP1 -d 'A list of supplementary groups which the user is also a member of'
complete -c useradd -s h -l help -d 'Display help message and exit'
complete -c useradd -s k -l skelSKEL_DIR -d 'The skeleton directory, which contains files and directories to be copied in …'
complete -c useradd -s K -l keyKEY -d 'Overrides /etc/login'
complete -c useradd -s l -l no-log-init -d 'Do not add the user to the lastlog and faillog databases'
complete -c useradd -s m -l create-home -d 'Create the user\\*(Aqs home directory if it does not exist'
complete -c useradd -s M -l no-create-home -d 'Do no create the user\\*(Aqs home directory, even if the system wide setting f…'
complete -c useradd -s N -l no-user-group -d 'Do not create a group with the same name as the user, but add the user to the…'
complete -c useradd -s o -l non-unique -d 'Allow the creation of a user account with a duplicate (non-unique) UID'
complete -c useradd -s p -l passwordPASSWORD -d 'The encrypted password, as returned by crypt(3)'
complete -c useradd -s r -l system -d 'Create a system account'
complete -c useradd -s R -l rootCHROOT_DIR -d 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c useradd -s P -l prefixPREFIX_DIR -d 'Apply changes in the PREFIX_DIR directory and use the configuration files fro…'
complete -c useradd -s s -l shellSHELL -d 'The name of the user\\*(Aqs login shell'
complete -c useradd -s u -l uidUID -d 'The numerical value of the user\\*(Aqs ID'
complete -c useradd -s U -l user-group -d 'Create a group with the same name as the user, and add the user to this group'
complete -c useradd -s Z -l selinux-userSEUSER -d 'The SELinux user for the user\\*(Aqs login'
complete -c useradd -l base-dir
complete -c useradd -l comment
complete -c useradd -l home-dir
complete -c useradd -l expiredate
complete -c useradd -l inactive
complete -c useradd -l gid
complete -c useradd -o U/--user-group -d 'is specified on the command line), a group will be created for the user, with…'
complete -c useradd -o N/--no-user-group -d 'is specified on the command line), useradd will set the primary group of the …'
complete -c useradd -l groups
complete -c useradd -l skel
complete -c useradd -l key
complete -c useradd -s 1 -d 'can be used when creating system account to turn off password aging, even tho…'
complete -c useradd -s O -d 'option is also supported'
complete -c useradd -l password
complete -c useradd -l root
complete -c useradd -l prefix
complete -c useradd -l shell
complete -c useradd -l uid
complete -c useradd -l selinux-user

