# usnjls
# Autogenerated from man page /usr/share/man/man1/usnjls.1.gz
complete -c usnjls -s f -d 'Specify the file system type'
complete -c usnjls -s i -d 'Identify the type of image file, such as raw or split'
complete -c usnjls -s o -d 'The sector offset where the file system starts in the image'
complete -c usnjls -s b -d 'The size, in bytes, of the underlying device sectors'
complete -c usnjls -s l -d 'Print the output in long format describing the field values and unpacking the…'
complete -c usnjls -s m -d 'Print the output in mactime format'
complete -c usnjls -s V -d 'Display version'
complete -c usnjls -s v -d 'verbose output image [images] One (or more if split) disk or partition images…'

