# uuidd
# Autogenerated from man page /usr/share/man/man8/uuidd.8.gz
complete -c uuidd -s d -l debug
complete -c uuidd -s F -l no-fork
complete -c uuidd -s k -l kill
complete -c uuidd -s n -l uuids
complete -c uuidd -s P -l no-pid
complete -c uuidd -s p -l pid
complete -c uuidd -s q -l quiet
complete -c uuidd -s r -l random
complete -c uuidd -s S -l socket-activation
complete -c uuidd -s s -l socket
complete -c uuidd -s T -l timeout
complete -c uuidd -s t -l time
complete -c uuidd -s V -l version
complete -c uuidd -s h -l help

