# uuidparse
# Autogenerated from man page /usr/share/man/man1/uuidparse.1.gz
complete -c uuidparse -s J -l json
complete -c uuidparse -s n -l noheadings
complete -c uuidparse -s o -l output
complete -c uuidparse -s r -l raw
complete -c uuidparse -s V -l version
complete -c uuidparse -s h -l help

