# vftovp
# Autogenerated from man page /usr/share/man/man1/vftovp.1.gz
complete -c vftovp -o charcode-format -d 'The argument  format specifies how character codes are output in the VPL file'
complete -c vftovp -o verbose -d 'Without this option, vftovp operates silently'

