# viewres
# Autogenerated from man page /usr/share/man/man1/viewres.1.gz
complete -c viewres -o top -d 'This option specifies the name of the highest widget in the hierarchy to disp…'
complete -c viewres -o variable -d 'This option indicates that the widget variable names (as declared in header f…'
complete -c viewres -o vertical -d 'This option indicates that the tree should be displayed top to bottom rather …'

