# vipw
# Autogenerated from man page /usr/share/man/man8/vipw.8.gz
complete -c vipw -s g -l group -d 'Edit group database'
complete -c vipw -s h -l help -d 'Display help message and exit'
complete -c vipw -s p -l passwd -d 'Edit passwd database'
complete -c vipw -s q -l quiet -d 'Quiet mode'
complete -c vipw -s R -l rootCHROOT_DIR -d 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c vipw -s s -l shadow -d 'Edit shadow or gshadow database'
complete -c vipw -l root

