# virtiofsd
# Autogenerated from man page /usr/share/man/man1/virtiofsd.1.gz
complete -c virtiofsd -s h -l help -d 'Print help'
complete -c virtiofsd -s V -l version -d 'Print version'
complete -c virtiofsd -s d -d 'Enable debug output'
complete -c virtiofsd -l syslog -d 'Print log messages to syslog instead of stderr'
complete -c virtiofsd -s o -d 'NDENT 7. 0'
complete -c virtiofsd -l socket-path -d 'Listen on vhost-user UNIX domain socket at PATH'
complete -c virtiofsd -l socket-group -d 'Set the vhost-user UNIX domain socket gid to GROUP'
complete -c virtiofsd -l fd -d 'Accept connections from vhost-user UNIX domain socket file descriptor FDNUM'
complete -c virtiofsd -l thread-pool-size -d 'Restrict the number of worker threads per request queue to NUM'
complete -c virtiofsd -l cache -d 'Select the desired trade-off between coherency and performance'

