# vlna
# Autogenerated from man page /usr/share/man/man1/vlna.1.gz
complete -c vlna -s f -d 'Filter.  The [filenames] are treated as follows: . RS'
complete -c vlna -s s -d 'The silent mode.  No messages, warnings, statistics are printed'
complete -c vlna -s r -d 'Do not create the backups'
complete -c vlna -s v -d 'The set of characters treated as non-syllabic prepositions is declared by thi…'
complete -c vlna -s x -d 'The code is a string written in hexadecimal notation (even hexa digits is req…'
complete -c vlna -s m -d 'The math-modes ($. $ and $$. $$) are ignored'
complete -c vlna -s n -d 'The verbatim mode (\\\\verb<char>. <char>, \\\\begtt'
complete -c vlna -s l -d 'The LaTeX mode'
complete -c vlna -s w -d 'The web mode (Knuth\'s web, no www:-)'

