# vstp
# Autogenerated from man page /usr/share/man/man1/vstp.1.gz
complete -c vstp -s i -d 'ask for confirmation of transfer, for each file (on the terminal)'
complete -c vstp -s f -d 'don\'t ask for such a confirmation (default)'
complete -c vstp -s b -d 'if they exists, recursively rename the old files with an added '
complete -c vstp -s n -d 'do not keep such backup file (default)'
complete -c vstp -s s -d 'use socketport as the port number instead of default for connecting to BrlNet'
complete -c vstp -s k -d 'use filename as key path instead of default for reading BrlNet\'s authenticati…'
complete -c vstp -s d -d 'use current directory rather than the download directory (see vbs_dir below)'
complete -c vstp -s o -d 'also read filename as config file'

