# wall
# Autogenerated from man page /usr/share/man/man1/wall.1.gz
complete -c wall -s n -l nobanner
complete -c wall -s t -l timeout
complete -c wall -s g -l group
complete -c wall -s V -l version
complete -c wall -s h -l help

