# watch
# Autogenerated from man page /usr/share/man/man1/watch.1.gz
complete -c watch -s d -l differences -d 'Highlight the differences between successive updates'
complete -c watch -s n -l interval -d 'Specify update interval.   The command will not allow quicker than 0'
complete -c watch -s p -l precise -d 'Make  watch attempt to run  command every  --interval R seconds '
complete -c watch -s t -l no-title -d 'Turn off the header showing the interval, command, and current time at the to…'
complete -c watch -s b -l beep -d 'Beep if command has a non-zero exit'
complete -c watch -s e -l errexit -d 'Freeze updates on command error, and exit after a key press'
complete -c watch -s g -l chgexit -d 'Exit when the output of  command changes'
complete -c watch -s c -l color -d 'Interpret ANSI color and style sequences'
complete -c watch -s x -l exec -d 'Pass  command to  exec (2) instead of  sh -c which reduces the need to use ex…'
complete -c watch -s w -l no-linewrap -d 'Turn off line wrapping'
complete -c watch -s h -l help -d 'Display help text and exit'
complete -c watch -s v -l version -d 'Display version information and exit.  EXIT STATUS 0 Success'

