# wc
# Autogenerated from man page /usr/share/man/man1/wc.1.gz
complete -c wc -s c -l bytes -d 'print the byte counts'
complete -c wc -s m -l chars -d 'print the character counts'
complete -c wc -s l -l lines -d 'print the newline counts'
complete -c wc -l files0-from -d 'read input from the files specified by NUL-terminated names in file F; If F i…'
complete -c wc -s L -l max-line-length -d 'print the maximum display width'
complete -c wc -s w -l words -d 'print the word counts'
complete -c wc -l help -d 'display this help and exit'
complete -c wc -l version -d 'output version information and exit AUTHOR Written by Paul Rubin and David Ma…'

