# whatis
# Autogenerated from man page /usr/share/man/man1/whatis.1.gz
complete -c whatis -s d -l debug -d 'Print debugging information'
complete -c whatis -s v -l verbose -d 'Print verbose warning messages'
complete -c whatis -s r -l regex -d 'Interpret each  name as a regular expression'
complete -c whatis -s w -l wildcard -d 'Interpret each  name as a pattern containing shell style wildcards'
complete -c whatis -s l -l long -d 'Do not trim output to the terminal width'
complete -c whatis -s s -d '--sections=list\\/, \\ --section=list Search only the given manual sections'
complete -c whatis -s m -d '--systems=system\\|[\\|,. \\|. \\|'
complete -c whatis -s M -l manpath -d 'Specify an alternate set of colon-delimited manual page hierarchies to search'
complete -c whatis -s L -l locale -d 'whatis will normally determine your current locale by a call to the C functio…'
complete -c whatis -s C -l config-file -d 'Use this user configuration file rather than the default of R ~/. manpath '
complete -c whatis -s '?' -l help -d 'Print a help message and exit'
complete -c whatis -l usage -d 'Print a short usage message and exit'
complete -c whatis -l sections
complete -c whatis -l section -d 'Search only the given manual sections'
complete -c whatis -l systems -d 'If this system has access to other operating systems\' manual page names, they…'
complete -c whatis -s V -l version -d 'Display version information.  EXIT STATUS'

