# wipefs
# Autogenerated from man page /usr/share/man/man8/wipefs.8.gz
complete -c wipefs -s a -l all
complete -c wipefs -s b -l backup
complete -c wipefs -s f -l force
complete -c wipefs -s h -l help
complete -c wipefs -s J -l json
complete -c wipefs -l lock
complete -c wipefs -s i -l noheadings
complete -c wipefs -s O -l output
complete -c wipefs -s n -l no-act
complete -c wipefs -s o -l offset
complete -c wipefs -s p -l parsable
complete -c wipefs -s q -l quiet
complete -c wipefs -s t -l types
complete -c wipefs -s V -l version

