# wrmsr
# Autogenerated from man page /usr/share/man/man1/wrmsr.1.gz
complete -c wrmsr -l help -s h -d 'Print a list of available options'
complete -c wrmsr -l version -s V -d 'Print current version'
complete -c wrmsr -l all -s a -d 'All processors'
complete -c wrmsr -l processor -s p -d 'Select processor number (default: 0)'

