# x-session-manager
# Autogenerated from man page /usr/share/man/man1/x-session-manager.1.gz
complete -c x-session-manager -l autostart -d 'The directory DIR to be searched for autostart . desktop files'
complete -c x-session-manager -l session -d 'Use the applications defined in SESSION. session.  If not specified, gnome'
complete -c x-session-manager -l builtin -d 'Use the legacy non-systemd method of managing the user session'
complete -c x-session-manager -l systemd -d 'Use the systemd method of managing the user session'
complete -c x-session-manager -l failsafe -d 'Run in fail-safe mode.  User-specified applications will not be started'
complete -c x-session-manager -l debug -d 'Enable debugging code'
complete -c x-session-manager -l whale -d 'Show the fail whale in a dialog for debugging it'

