# x86_64-linux-gnu-lto-dump-11
# Autogenerated from man page /usr/share/man/man1/x86_64-linux-gnu-lto-dump-11.1.gz
complete -c x86_64-linux-gnu-lto-dump-11 -o list -d 'Dumps list of details of functions and variables'
complete -c x86_64-linux-gnu-lto-dump-11 -o demangle -d 'Dump the demangled output'
complete -c x86_64-linux-gnu-lto-dump-11 -o defined-only -d 'Dump only the defined symbols'
complete -c x86_64-linux-gnu-lto-dump-11 -o print-value -d 'Dump initial values of the variables'
complete -c x86_64-linux-gnu-lto-dump-11 -o name-sort -d 'Sort the symbols alphabetically'
complete -c x86_64-linux-gnu-lto-dump-11 -o size-sort -d 'Sort the symbols according to size'
complete -c x86_64-linux-gnu-lto-dump-11 -o reverse-sort -d 'Dump the symbols in reverse order'
complete -c x86_64-linux-gnu-lto-dump-11 -o no-sort -d 'Dump the symbols in order of occurrence'
complete -c x86_64-linux-gnu-lto-dump-11 -o symbol -d 'Dump the details of specific symbol'
complete -c x86_64-linux-gnu-lto-dump-11 -o objects -d 'Dump the details of \\s-1LTO\\s0 objects'
complete -c x86_64-linux-gnu-lto-dump-11 -o type-stats -d 'Dump the statistics of tree types'
complete -c x86_64-linux-gnu-lto-dump-11 -o tree-stats -d 'Dump the statistics of trees'
complete -c x86_64-linux-gnu-lto-dump-11 -o gimple-stats -d 'Dump the statistics of gimple statements'
complete -c x86_64-linux-gnu-lto-dump-11 -o dump-level -d 'For deciding the optimization level of body'
complete -c x86_64-linux-gnu-lto-dump-11 -o dump-body -d 'Dump the specific gimple body'

