# x86_64-linux-gnu-python3
# Autogenerated from man page /usr/share/man/man1/x86_64-linux-gnu-python3.10-config.1.gz
complete -c x86_64-linux-gnu-python3 -l abiflags -d 'print the the ABI flags as specified by PEP 3149'
complete -c x86_64-linux-gnu-python3 -l cflags -d 'print the C compiler flags'
complete -c x86_64-linux-gnu-python3 -l ldflags -d 'print the flags that should be passed to the linker'
complete -c x86_64-linux-gnu-python3 -l includes -d 'similar to --cflags but only with -I options (path to python header files)'
complete -c x86_64-linux-gnu-python3 -l libs -d 'similar to --ldflags but only with -l options (used libraries)'
complete -c x86_64-linux-gnu-python3 -l prefix -d 'prints the prefix (base directory) under which python can be found'
complete -c x86_64-linux-gnu-python3 -l exec-prefix -d 'print the prefix used for executable program directories (such as bin, sbin, …'
complete -c x86_64-linux-gnu-python3 -l extension-suffix -d 'print the extension suffix used for binary extensions'
complete -c x86_64-linux-gnu-python3 -l help -d 'print the usage message'

