# xcalc
# Autogenerated from man page /usr/share/man/man1/xcalc.1.gz
complete -c xcalc -o stipple -d 'This option indicates that the background of the calculator should be drawn u…'
complete -c xcalc -o rpn -d 'This option indicates that Reverse Polish Notation should be used'

