# xdg-user-dirs-update
# Autogenerated from man page /usr/share/man/man1/xdg-user-dirs-update.1.gz
complete -c xdg-user-dirs-update -l help -d 'Print help output and exit'
complete -c xdg-user-dirs-update -l force -d 'Update existing user-dirs. dir, but force a full reset'
complete -c xdg-user-dirs-update -l dummy-output -d 'Write the configuration to PATH instead of the default configuration file'
complete -c xdg-user-dirs-update -l set -d 'Sets the XDG user dir with the given name'

