# xdg-settings
# Autogenerated from man page /usr/share/man/man1/xdg-settings.1.gz
complete -c xdg-settings -l help -d 'Show command synopsis'
complete -c xdg-settings -l list -d 'List all properties xdg-settings knows about'
complete -c xdg-settings -l manual -d 'Show this manual page'
complete -c xdg-settings -l version -d 'Show the xdg-utils version information'

