# xdg-screensaver
# Autogenerated from man page /usr/share/man/man1/xdg-screensaver.1.gz
complete -c xdg-screensaver -l help -d 'Show command synopsis'
complete -c xdg-screensaver -l manual -d 'Show this manual page'
complete -c xdg-screensaver -l version -d 'Show the xdg-utils version information'

