# xdg-desktop-menu
# Autogenerated from man page /usr/share/man/man1/xdg-desktop-menu.1.gz
complete -c xdg-desktop-menu -l noupdate -d 'Postpone updating the menu system'
complete -c xdg-desktop-menu -l novendor -d 'Normally, xdg-desktop-menu checks to ensure that any *. directory and *'
complete -c xdg-desktop-menu -l mode -d 'mode can be user or system'
complete -c xdg-desktop-menu -l help -d 'Show command synopsis'
complete -c xdg-desktop-menu -l manual -d 'Show this manual page'
complete -c xdg-desktop-menu -l version -d 'Show the xdg-utils version information'

