# xdg-dbus-proxy
# Autogenerated from man page /usr/share/man/man1/xdg-dbus-proxy.1.gz
complete -c xdg-dbus-proxy -l help -d 'Print help and exit'
complete -c xdg-dbus-proxy -l version -d 'Print version'
complete -c xdg-dbus-proxy -l fd -d 'Write to FD when the proxies are ready, and stop when it is closed'
complete -c xdg-dbus-proxy -l args -d 'Parse nul-separated arguments from the given file descriptor'
complete -c xdg-dbus-proxy -l filter -d 'Enable filtering'
complete -c xdg-dbus-proxy -l log -d 'Turn on logging'
complete -c xdg-dbus-proxy -l sloppy-names -d 'Make all unique names visible'
complete -c xdg-dbus-proxy -l see -d 'Set the SEE policy for the given name'
complete -c xdg-dbus-proxy -l talk -d 'Set the TALK policy for the given name'
complete -c xdg-dbus-proxy -l own -d 'Set the OWN policy for the given name'
complete -c xdg-dbus-proxy -l call -d 'Set a rule for calls on the given name'
complete -c xdg-dbus-proxy -l broadcast -d 'Set a rule for broadcast signals from the given name'

