# xdg-icon-resource
# Autogenerated from man page /usr/share/man/man1/xdg-icon-resource.1.gz
complete -c xdg-icon-resource -l noupdate -d 'Postpone updating the desktop icon system'
complete -c xdg-icon-resource -l novendor -d 'Normally, xdg-icon-resource checks to ensure that an icon file to be installe…'
complete -c xdg-icon-resource -l theme -d 'Installs or removes the icon file as part of theme'
complete -c xdg-icon-resource -l context -d 'Specifies the context for the icon'
complete -c xdg-icon-resource -l size -d 'Specifies the size of the icon.  All icons must be square'
complete -c xdg-icon-resource -l mode -d 'mode can be user or system'
complete -c xdg-icon-resource -l help -d 'Show command synopsis'
complete -c xdg-icon-resource -l manual -d 'Show this manual page'
complete -c xdg-icon-resource -l version -d 'Show the xdg-utils version information'

