# xdriinfo
# Autogenerated from man page /usr/share/man/man1/xdriinfo.1.gz
complete -c xdriinfo -o display -d 'Specifies X server to connect to'
complete -c xdriinfo -o version -d 'Print the program version and exit. PP Valid commands are:'

