# xev
# Autogenerated from man page /usr/share/man/man1/xev.1.gz
complete -c xev -o display -d 'This option specifies the X server to contact'
complete -c xev -o geometry -d 'This option specifies the size and/or location of the window, if a window is …'
complete -c xev -o bw -d 'This option specifies the border width for the window'
complete -c xev -o bs -d 'This option specifies what kind of backing store to give the window'
complete -c xev -o id -d 'This option specifies that the window with the given id should be monitored, …'
complete -c xev -o root -d 'This option specifies that the root window should be monitored, instead of cr…'
complete -c xev -s s -d 'This option specifies that save-unders should be enabled on the window'
complete -c xev -o name -d 'This option specifies the name to assign to the created window'
complete -c xev -o rv -d 'This option specifies that the window should be in reverse video'
complete -c xev -o event -d 'Select which events to display'
complete -c xev -o version -d 'This option prints the program version and exits'

