# xeyes
# Autogenerated from man page /usr/share/man/man1/xeyes.1.gz
complete -c xeyes -o fg -d 'choose a different color for the pupil of the eyes'
complete -c xeyes -o bg -d 'choose a different color for the background'
complete -c xeyes -o outline -d 'choose a different color for the outline of the eyes'
complete -c xeyes -o center -d 'choose a different color for the center of the eyes'
complete -c xeyes -o backing -d 'selects an appropriate level of backing store'
complete -c xeyes -o geometry -d 'define the initial window geometry; see X(7)'
complete -c xeyes -o display -d 'specify the display to use; see X(7)'
complete -c xeyes -o bd -d 'choose a different color for the window border'
complete -c xeyes -o bw -d 'choose a different width for the window border'
complete -c xeyes -o shape -d 'uses the SHAPE extension to shape the window.   This is the default'
complete -c xeyes -o render -d 'uses Xrender to draw anti-aliased eyes'
complete -c xeyes -o distance -d 'uses an alternative mapping, as if the eyes were set back from the screen, th…'

