# xfd
# Autogenerated from man page /usr/share/man/man1/xfd.1.gz
complete -c xfd -o fn -d 'This option specifies the core X server side font to be displayed'
complete -c xfd -o fa -d 'This option specifies a Xft font to be displayed'
complete -c xfd -o box -d 'This option indicates that a box should be displayed outlining the area that …'
complete -c xfd -o center -d 'This option indicates that each glyph should be centered in its grid'
complete -c xfd -o start -d 'This option specifies the glyph index of the upper left hand corner of the gr…'
complete -c xfd -o bc -d 'This option specifies the color to be used if ImageText boxes are drawn'
complete -c xfd -o rows -d 'This option specifies the number of rows in the grid'

