# xlogo
# Autogenerated from man page /usr/share/man/man1/xlogo.1.gz
complete -c xlogo -o render -d 'This option indicates that the logo should be drawn with anti-aliased edges u…'
complete -c xlogo -o sharp -d 'If -render is also specified, this forces the edges to be rendered in sharp m…'
complete -c xlogo -o shape -d 'This option indicates that the logo window should be shaped rather than recta…'

