# xmessage
# Autogenerated from man page /usr/share/man/man1/xmessage.1.gz
complete -c xmessage -o buttons -d 'This option will cause xmessage to create one button for each comma-separated…'
complete -c xmessage -o default -d 'Defines the button with a matching label to be the default'
complete -c xmessage -o file -d 'File to display.  The corresponding resource is file'
complete -c xmessage -o print -d 'This will cause the program to write the label of the button pressed to stand…'
complete -c xmessage -o center -d 'Pop up the window at the center of the screen'
complete -c xmessage -o nearmouse -d 'Pop up the window near the mouse cursor'
complete -c xmessage -o timeout -d 'Exit with status 0 after secs seconds if the user has not clicked on a button…'

