# xprintidle
# Autogenerated from man page /usr/share/man/man1/xprintidle.1.gz
complete -c xprintidle -s h -l help -d 'Output a usage message and exit'
complete -c xprintidle -s v -l version -d 'Output the version number and exit'

