# xstdcmap
# Autogenerated from man page /usr/share/man/man1/xstdcmap.1.gz
complete -c xstdcmap -o all -d 'This option indicates that all six standard colormap properties should be def…'
complete -c xstdcmap -o best -d 'This option indicates that the RGB_BEST_MAP should be defined'
complete -c xstdcmap -o blue -d 'This option indicates that the RGB_BLUE_MAP should be defined'
complete -c xstdcmap -o default -d 'This option indicates that the RGB_DEFAULT_MAP should be defined'
complete -c xstdcmap -o delete -d 'This option specifies that a specific standard colormap property, or all such…'
complete -c xstdcmap -o display -d 'This option specifies the host and display to use; see X(7)'
complete -c xstdcmap -o gray -d 'This option indicates that the RGB_GRAY_MAP should be defined'
complete -c xstdcmap -o green -d 'This option indicates that the RGB_GREEN_MAP should be defined'
complete -c xstdcmap -o help -d 'This option indicates that a brief description of the command line arguments …'
complete -c xstdcmap -o red -d 'This option indicates that the RGB_RED_MAP should be defined'
complete -c xstdcmap -o verbose -d 'This option indicates that xstdcmap should print logging information as it pa…'
complete -c xstdcmap -o version -d 'This option indicates that xstdcmap should print its version and exit'

