# xvidtune
# Autogenerated from man page /usr/share/man/man1/xvidtune.1.gz
complete -c xvidtune -o show -d 'Print the current settings to stdout in xorg. conf "Modeline" format and exit'
complete -c xvidtune -o prev -d 'Switch the Xserver to the previous video mode'
complete -c xvidtune -o next -d 'Switch the Xserver to the next video mode'
complete -c xvidtune -o unlock -d 'Normally, xvidtune will disable the switching of video modes via hot-keys whi…'

