# xvinfo
# Autogenerated from man page /usr/share/man/man1/xvinfo.1.gz
complete -c xvinfo -o display -d 'This argument allows you to specify the server to query; see X(7)'
complete -c xvinfo -o short -d 'Output less details, to reduce the amount of text'
complete -c xvinfo -o version -d 'Output program version, then exit'

