# xwd
# Autogenerated from man page /usr/share/man/man1/xwd.1.gz
complete -c xwd -o display -d 'This argument allows you to specify the server to connect to; see X(7). PP'
complete -c xwd -o help -d 'Print out the `Usage:\' command syntax summary. PP'
complete -c xwd -o nobdrs -d 'This argument specifies that the window dump should not include the pixels th…'
complete -c xwd -o out -d 'This argument allows the user to explicitly specify the output file on the co…'
complete -c xwd -o xy -d 'This option applies to color displays only'
complete -c xwd -o add -d 'This option specifies a signed value to be added to every pixel. PP'
complete -c xwd -o frame -d 'This option indicates that the window manager frame should be included when m…'
complete -c xwd -o root -d 'This option indicates that the root window should be selected for the window …'
complete -c xwd -o id -d 'This option indicates that the window with the specified resource id should b…'
complete -c xwd -o name -d 'This option indicates that the window with the specified WM_NAME property sho…'
complete -c xwd -o icmap -d 'Normally the colormap of the chosen window is used to obtain RGB values'
complete -c xwd -o screen -d 'This option indicates that the GetImage request used to obtain the image shou…'
complete -c xwd -o silent -d 'Operate silently, i. e'
complete -c xwd -o version -d 'This option indicates that xwd should print its version information and exit'

