# ypdomainname
# Autogenerated from man page /usr/share/man/man1/ypdomainname.1.gz
complete -c ypdomainname -s a -l alias -d 'Display the alias name of the host (if used)'
complete -c ypdomainname -s A -l all-fqdns -d 'Displays all FQDNs of the machine'
complete -c ypdomainname -s b -l boot -d 'Always set a hostname; this allows the file specified by -F to be non-existen…'
complete -c ypdomainname -s d -l domain -d 'Display the name of the DNS domain'
complete -c ypdomainname -s f -l fqdn -l long -d 'Display the FQDN (Fully Qualified Domain Name)'
complete -c ypdomainname -s F -l file -d 'Read the host name from the specified file'
complete -c ypdomainname -s i -l ip-address -d 'Display the network address(es) of the host name'
complete -c ypdomainname -s I -l all-ip-addresses -d 'Display all network addresses of the host'
complete -c ypdomainname -s s -l short -d 'Display the short host name.  This is the host name cut at the first dot'
complete -c ypdomainname -s V -l version -d 'Print version information on standard output and exit successfully'
complete -c ypdomainname -s y -l yp -l nis -d 'Display the NIS domain name'
complete -c ypdomainname -s h -l help -d 'Print a usage message and exit'

