# zcat
# Autogenerated from man page /usr/share/man/man1/zcat.1.gz
complete -c zcat -s a -l ascii -d 'Ascii text mode: convert end-of-lines using local conventions'
complete -c zcat -s c -l stdout -l to-stdout -d 'Write output on standard output; keep original files unchanged'
complete -c zcat -s d -l decompress -l uncompress -d Decompress
complete -c zcat -s f -l force -d 'Force compression or decompression even if the file has multiple links or the…'
complete -c zcat -s h -l help -d 'Display a help screen and quit'
complete -c zcat -s k -l keep -d 'Keep (don\'t delete) input files during compression or decompression'
complete -c zcat -s l -l list -d 'For each compressed file, list the following fields:      compressed size: si…'
complete -c zcat -s L -l license -d 'Display the  gzip license and quit'
complete -c zcat -s n -l no-name -d 'When compressing, do not save the original file name and timestamp by default'
complete -c zcat -s N -l name -d 'When compressing, always save the original file name and timestamp; this is t…'
complete -c zcat -s q -l quiet -d 'Suppress all warnings'
complete -c zcat -s r -l recursive -d 'Travel the directory structure recursively'
complete -c zcat -s S -l suffix -d 'When compressing, use suffix . suf instead of . gz'
complete -c zcat -l synchronous -d 'Use synchronous output'
complete -c zcat -s t -l test -d 'Test.  Check the compressed file integrity'
complete -c zcat -s v -l verbose -d Verbose
complete -c zcat -s V -l version -d 'Version.  Display the version number and compilation options then quit'
complete -c zcat -s '#' -l fast -l best -d 'Regulate the speed of compression using the specified digit R # , where  -1 o…'
complete -c zcat -s 1 -d or
complete -c zcat -s 9 -d or
complete -c zcat -s 6 -d '(that is, biased towards high compression at expense of speed)'
complete -c zcat -l rsyncable -d 'When you synchronize a compressed file between two computers, this option all…'

