# zdump
# Autogenerated from man page /usr/share/man/man8/zdump.8.gz
complete -c zdump -o '	-	-103126	LMT' -d '1896-01-13	12:01:26	-1030	HST 1933-04-30	03	-0930	HDT	1 1933-05-21	11	-1030	H…'
complete -c zdump -o '	-	+031212	LMT' -d '1924-04-30	23:47:48	+03 1930-06-21	01	+04 1981-04-01	01	+05		1 1981-09-30	23	…'

