# zerofree
# Autogenerated from man page /usr/share/man/man8/zerofree.8.gz
complete -c zerofree -s n -d 'Perform a dry run  (do not modify the file-system);'
complete -c zerofree -s v -d 'Be verbose: show the number of blocks modified by  zerofree (or that would be…'

