# zipcloak
# Autogenerated from man page /usr/share/man/man1/zipcloak.1.gz
complete -c zipcloak -s b
complete -c zipcloak -l temp-path -d 'Use the directory given by path for the temporary zip file'
complete -c zipcloak -s d
complete -c zipcloak -l decrypt -d 'Decrypt encrypted entries (copy if given wrong password)'
complete -c zipcloak -s h
complete -c zipcloak -l help -d 'Show a short help'
complete -c zipcloak -s L
complete -c zipcloak -l license -d 'Show software license'
complete -c zipcloak -s O
complete -c zipcloak -l output-file -d 'Write output to new archive zipfile, leaving original archive as is'
complete -c zipcloak -s q
complete -c zipcloak -l quiet -d 'Quiet operation.   Suppresses some informational messages'
complete -c zipcloak -s v
complete -c zipcloak -l version -d 'Show version information'

