# zipinfo
# Autogenerated from man page /usr/share/man/man1/zipinfo.1.gz
complete -c zipinfo -s 1 -d 'list filenames only, one per line'
complete -c zipinfo -s 2 -d 'list filenames only, one per line, but allow headers (-h), trailers (-t) and …'
complete -c zipinfo -s s -d 'list zipfile info in short Unix ``\\fCls -l\'\' format'
complete -c zipinfo -s m -d 'list zipfile info in medium Unix ``\\fCls -l\'\' format'
complete -c zipinfo -s l -d 'list zipfile info in long Unix ``\\fCls -l\'\' format'
complete -c zipinfo -s v -d 'list zipfile information in verbose, multi-page format'
complete -c zipinfo -s h -d 'list header line'
complete -c zipinfo -s M -d 'pipe all output through an internal pager similar to the Unix more(1) command'
complete -c zipinfo -s t -d 'list totals for files listed or for all files'
complete -c zipinfo -s T -d 'print the file dates and times in a sortable decimal format (yymmdd. hhmmss)'
complete -c zipinfo -s U -d '[UNICODE_SUPPORT only] modify or disable UTF-8 handling'
complete -c zipinfo -o UU -d 'encoded filenames'
complete -c zipinfo -s z -d 'include the archive comment (if any) in the listing'

