# zjsdecode
# Autogenerated from man page /usr/share/man/man1/zjsdecode.1.gz
complete -c zjsdecode -s d -d 'Basename of . pbm file for saving decompressed planes'
complete -c zjsdecode -s r -d 'Basename of . jbg file for saving raw planes'
complete -c zjsdecode -s h -d 'Print hex file offsets'
complete -c zjsdecode -s o -d 'Print file offsets'
complete -c zjsdecode -s p -d 'Don\'t do 4 byte padding'
complete -c zjsdecode -s D -d 'Set Debug level [0]'

