# zramctl
# Autogenerated from man page /usr/share/man/man8/zramctl.8.gz
complete -c zramctl -s a -l algorithm
complete -c zramctl -s f -l find
complete -c zramctl -s n -l noheadings
complete -c zramctl -s o -l output
complete -c zramctl -l output-all
complete -c zramctl -l raw
complete -c zramctl -s r -l reset
complete -c zramctl -s s -l size
complete -c zramctl -s t -l streams
complete -c zramctl -s V -l version
complete -c zramctl -s h -l help

