# zstdmt
# Autogenerated from man page /usr/share/man/man1/zstdmt.1.gz
complete -c zstdmt -s z -l compress -d Compress
complete -c zstdmt -s d -l decompress -l uncompress -d Decompress
complete -c zstdmt -s t -l test -d 'Test the integrity of compressed files'
complete -c zstdmt -o 'b#' -d 'Benchmark file(s) using compression level # '
complete -c zstdmt -l train -d 'Use FILEs as a training set to create a dictionary'

