# zstd
# Autogenerated from man page /usr/share/man/man1/zstd.1.gz
complete -c zstd -s z -l compress -d Compress
complete -c zstd -s d -l decompress -l uncompress -d Decompress
complete -c zstd -s t -l test -d 'Test the integrity of compressed files'
complete -c zstd -o 'b#' -d 'Benchmark file(s) using compression level # '
complete -c zstd -l train -d 'Use FILEs as a training set to create a dictionary'

