# zstdcat
# Autogenerated from man page /usr/share/man/man1/zstdcat.1.gz
complete -c zstdcat -s z -l compress -d Compress
complete -c zstdcat -s d -l decompress -l uncompress -d Decompress
complete -c zstdcat -s t -l test -d 'Test the integrity of compressed files'
complete -c zstdcat -o 'b#' -d 'Benchmark file(s) using compression level # '
complete -c zstdcat -l train -d 'Use FILEs as a training set to create a dictionary'

