# zsync
# Autogenerated from man page /usr/share/man/man1/zsync.1.gz
complete -c zsync -s A -d 'Specifies a username and password to be used with the given hostname'
complete -c zsync -s i -d 'Specifies (extra) input files'
complete -c zsync -s k -d 'Indicates that zsync should save the zsync file that it downloads, with the g…'
complete -c zsync -s o -d 'Override the default output file name'
complete -c zsync -s q -d 'Suppress the progress bar, download rate and ETA display'
complete -c zsync -s s -d 'Deprecated synonym for -q'
complete -c zsync -s u -d 'This specifies the referring URL.   If you have a '

